services:
  # Overrides api and indexer containers to configure them for e2e tests
  vechain-indexer:
    env_file: packages/e2e/indexer.env
    environment:
      - CONTRACT_NFT_BLACKLIST=${CONTRACT_NFT_BLACKLIST}
    networks:
      - vechain-e2e
      - vechain-thor-e2e
      - vechain-database

  vechain-indexer-api:
    env_file: packages/e2e/api.env
    networks:
      - vechain-e2e
      - vechain-thor-e2e
      - vechain-database

networks:
  vechain-e2e:
    driver: bridge
    name: vechain-e2e
  vechain-database:
    external: true
    name: vechain-database
  vechain-thor-e2e:
    external: true
    name: vechain-thor-e2e