services:
  # Overrides api and indexer containers to configure them for e2e tests
  vechain-indexer:
    env_file: packages/e2e/indexer.env
    environment:
      - BLACKLIST_CONTRACT_ADDRESS=${BLACKLIST_CONTRACT_ADDRESS}
    networks:
      - vechain
      - vechain-thor-e2e
      - vechain-database

  vechain-indexer-api:
    env_file: packages/e2e/api.env
    networks:
      - vechain
      - vechain-thor-e2e
      - vechain-database

networks:
  vechain-thor-e2e:
    external: true
    name: vechain-thor-e2e