server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /

logging:
  level:
    ROOT: INFO
    org:
      vechain: ${APP_LOG_LEVEL:INFO}
      springframework:
        data: INFO

timing:
  warn-threshold-ms: ${TIMING_WARN_THRESHOLD_MS:1000}
  very-slow-threshold-ms: ${TIMING_VERY_SLOW_THRESHOLD_MS:10000}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL:#{null}}

spring:
  application:
    name: vechain-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:nfts,transactions,transfers,history,stargate,authority-nodes,vevote-results,vevote-historic-proposals,b3tr,explorer,accounts,validator}
  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: 'health'
  endpoint:
    health:
      show-details: always

spring.data:
  mongodb:
    auto-index-creation: false
    uri: ${MONGO_URI:mongodb://api:password@localhost:27017/vechain?authSource=admin}

token:
  registry:
    url: ${TOKEN_REGISTRY_URL:https://vechain.github.io/token-registry}

thor:
  url: ${THOR_URL:https://testnet.vechain.org}

cache:
  max-size: ${CACHE_MAX_SIZE:1000}
  ttl-seconds: ${CACHE_TTL_SECONDS:300}
  caches:
    user_all_time_action_countByEntityType:
      max-size: ${CACHE_USER_ALL_TIME_COUNT_BY_ENTITY_TYPE_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_USER_ALL_TIME_COUNT_BY_ENTITY_TYPE_TTL_SECONDS:1200}
    user_all_time_action_countByTotalRewardAmountGreaterThanAndEntityType:
      max-size: ${CACHE_USER_ALL_TIME_COUNT_BY_REWARD_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_USER_ALL_TIME_COUNT_BY_REWARD_TTL_SECONDS:300}
    user_all_time_action_countByActionsRewardedGreaterThanAndEntityType:
      max-size: ${CACHE_USER_ALL_TIME_COUNT_BY_ACTIONS_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_USER_ALL_TIME_COUNT_BY_ACTIONS_TTL_SECONDS:300}
    app_all_time_action_countByAppId:
      max-size: ${CACHE_APP_ALL_TIME_COUNT_BY_APP_ID_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_APP_ALL_TIME_COUNT_BY_APP_ID_TTL_SECONDS:300}
    app_daily_action_countByAppIdAndDate:
      max-size: ${CACHE_APP_DAILY_COUNT_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_APP_DAILY_COUNT_TTL_SECONDS:300}
    app_round_countByAppIdAndRoundId:
      max-size: ${CACHE_APP_ROUND_COUNT_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_APP_ROUND_COUNT_TTL_SECONDS:300}
    user_daily_action_countByAppIdAndDate:
      max-size: ${CACHE_USER_DAILY_COUNT_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_USER_DAILY_COUNT_TTL_SECONDS:300}
    user_daily_action_countByActionsRewardedGreaterThanAndEntityTypeAndDate:
      max-size: ${CACHE_USER_DAILY_COUNT_BY_ACTIONS_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_USER_DAILY_COUNT_BY_ACTIONS_TTL_SECONDS:300}
    user_daily_action_countByEntityTypeAndDate:
      max-size: ${CACHE_USER_DAILY_COUNT_BY_ENTITY_TYPE_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_USER_DAILY_COUNT_BY_ENTITY_TYPE_TTL_SECONDS:300}
    user_round_countByTotalRewardAmountGreaterThanAndEntityTypeAndRoundId:
      max-size: ${CACHE_USER_ROUND_COUNT_BY_REWARD_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_USER_ROUND_COUNT_BY_REWARD_TTL_SECONDS:300}
    user_round_countByActionsRewardedGreaterThanAndEntityTypeAndRoundId:
      max-size: ${CACHE_USER_ROUND_COUNT_BY_ACTIONS_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_USER_ROUND_COUNT_BY_ACTIONS_TTL_SECONDS:300}
    user_round_countByEntityTypeAndRoundId:
      max-size: ${CACHE_USER_ROUND_COUNT_BY_ENTITY_TYPE_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_USER_ROUND_COUNT_BY_ENTITY_TYPE_TTL_SECONDS:300}
    official_token_addresses:
      max-size: ${CACHE_OFFICIAL_TOKEN_ADDRESSES_MAX_SIZE:10}
      ttl-seconds: ${CACHE_OFFICIAL_TOKEN_ADDRESSES_TTL_SECONDS:3600}
    gmNft_countByLevelAndOwnerNot:
      max-size: ${CACHE_GM_NFT_COUNT_MAX_SIZE:1000}
      ttl-seconds: ${CACHE_GM_NFT_COUNT_TTL_SECONDS:300}
