server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: 'health'
  endpoint:
    health:
      show-details: always

spring.data:
  mongodb:
    uri: ${MONGO_URI:mongodb://admin:password@localhost:27017/vechain?directConnection=true&authMechanism=SCRAM-SHA-1&authSource=admin}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG