version: "3.5"

services:

  vechain-indexer:
    build:
      context: .
      args:
        VEWORLD_PACKAGE: indexer
    restart: "no"
    env_file: ${ENV_FILE_NAME:-.env.local}
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    tty: true
    networks:
      - vechain
      - vechain-database
      - vechain-thor

  vechain-indexer-api:
    build:
      context: .
      args:
        VEWORLD_PACKAGE: api
    restart: "no"
    hostname: vechain-indexer-api
    env_file: ${ENV_FILE_NAME:-.env.local}
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    ports:
      - 8080:8080
    tty: true
    networks:
      - vechain
      - vechain-database
      - vechain-thor

networks:
  vechain:
    driver: bridge
    name: vechain
  vechain-database:
    external: true
    name: vechain-database
  vechain-thor:
    external: true
    name: vechain-thor
