FROM eclipse-temurin:19 AS builder

WORKDIR /opt/app

COPY gradle ./gradle
COPY gradlew ./

RUN ./gradlew

COPY build.gradle.kts ./
COPY settings.gradle.kts ./
COPY system.properties ./
COPY packages ./packages

RUN ./gradlew packages:api:build publishToMavenLocal -x test

FROM eclipse-temurin:19

WORKDIR /opt/app

COPY --from=builder /opt/app/packages/api/build/libs/*-SNAPSHOT.jar /opt/app/app.jar

ENTRYPOINT ["java", "-Djdk.tls.client.protocols=TLSv1.2", "-jar", "./app.jar", "-XX:+UseContainerSupport"]
