services:

  vechain-indexer:
    build:
      context: .
      args:
        PACKAGE_NAME: indexer
    container_name: vechain-indexer
    restart: "no"
    env_file: ${INDEXER_ENV_FILE_NAME:-packages/indexer/.env}
    healthcheck:
      test: "curl --fail localhost:8080/actuator/health"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    tty: true
    ports:
      - 8081:8080
    networks:
      - vechain
      - vechain-database
      - vechain-thor

  vechain-indexer-api:
    build:
      context: .
      args:
        PACKAGE_NAME: api
    container_name: vechain-indexer-api
    restart: "no"
    hostname: vechain-indexer-api
    env_file: ${API_ENV_FILE_NAME:-packages/api/.env}
    healthcheck:
      test: "curl --fail localhost:8080/actuator/health"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    ports:
      - 8080:8080
    tty: true
    networks:
      - vechain
      - vechain-database
      - vechain-thor

networks:
  vechain:
    driver: bridge
    name: vechain
  vechain-database:
    external: true
    name: vechain-database
  vechain-thor:
    external: true
    name: vechain-thor
