# syntax=docker/dockerfile:1

FROM amazoncorretto:21.0.12-alpine3.23
RUN apk --no-cache upgrade && apk add --no-cache curl
ARG PACKAGE_NAME
RUN test -n "$PACKAGE_NAME" || (echo "ERROR: PACKAGE_NAME build arg must be set and non-empty" >&2 && exit 1)
WORKDIR /usr/app
COPY packages/${PACKAGE_NAME}/build/libs/${PACKAGE_NAME}*.jar /usr/app/app.jar
CMD ["java", "-jar", "/usr/app/app.jar"]
