version: "3.5"

services:

  vechain-indexer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vechain-indexer
    restart: "no"
    env_file: .env.local
    networks:
      - vechain
      - vechain-database
      - vechain-thor

networks:
  vechain:
    driver: bridge
    name: vechain
  vechain-database:
    external: true
    name: vechain-database
  vechain-thor:
    external: true
    name: vechain-thor
