server:
  ssl:
    trusted-certificates: /etc/ssl/cert.pem
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: vechain-indexer
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:indexer,vevote-events,nft-events,transactions,transfer-events,history-events}
  output:
    ansi:
      enabled: always

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL:#{null}}

logging:
  level:
    ROOT: INFO
    org:
      vechain: ${APP_LOG_LEVEL:INFO}
      springframework:
        data: INFO

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: 'health'
  endpoint:
    health:
      show-details: always

spring.data:
  mongodb:
    uri: ${MONGO_URI:mongodb://indexer:password@localhost:27017/vechain?authSource=admin}

thor:
  url: ${THOR_URL:http://localhost:8669}

abis:
  path: ${ABI_PATH:abis}

businessEvents:
  path: ${BUSINESS_EVENTS_PATH:businessEvents}

veworld:
  contract:
    vevote:
      address: ${VEVOTE_CONTRACT:0x428BE069E21a584fBbAb934Fb4ad55AF346A3513}

indexer:
  startBlock:
    nfts: ${INDEXER_START_BLOCK_NFTS:0}
    nft_blacklist: ${INDEXER_START_BLOCK_NFT_BLACKLIST:0}
    transactions: ${INDEXER_START_BLOCK_TRANSACTIONS:0}
    transfers: ${INDEXER_START_BLOCK_TRANSFERS:0}
    history: ${INDEXER_START_BLOCK_HISTORY:0}
    vevote: ${INDEXER_START_BLOCK_VEVOTE:0}
  syncLogInterval:
    nfts: ${INDEXER_SYNC_LOGGER_INTERVAL_NFTS:1000}
    transactions: ${INDEXER_SYNC_LOGGER_INTERVAL_TRANSACTIONS:1000}
    transfers: ${INDEXER_SYNC_LOGGER_INTERVAL_TRANSFERS:1000}
    history: ${INDEXER_SYNC_LOGGER_INTERVAL_HISTORY:1000}
    vevote: ${INDEXER_SYNC_LOGGER_INTERVAL_VEVOTE:1000}
  syncBlockBatchSize:
    nfts: ${INDEXER_SYNC_BLOCK_BATCH_SIZE_NFTS:100}
    transfers: ${INDEXER_SYNC_BLOCK_BATCH_SIZE_TRANSFERS:100}
    vevote: ${INDEXER_SYNC_BLOCK_BATCH_SIZE_VEVOTE:1000}
  pruner:
    enabled: ${PRUNER_ENABLED:true}
    interval: ${PRUNER_INTERVAL:300000}
    initialDelay: ${PRUNER_INITIAL_DELAY:300000}
    removalChunkSize: ${PRUNER_REMOVAL_CHUNK_SIZE:10000}
  blacklist:
    contract_address: ${BLACKLIST_CONTRACT_ADDRESS:0x14091CC9Ae249f26EaF41a5A21207931162A2826}
    initialDelay: ${BLACKLIST_INITIAL_DELAY:1}
    interval: ${BLACKLIST_INTERVAL:1800000}
  version:
    nfts: ${VERSION_NFTS:1}
    transfers: ${VERSION_TRANSFERS:1}
    transactions: ${VERSION_TRANSACTIONS:1}
    history: ${VERSION_HISTORY:1}
    nft_blacklist: ${VERSION_NFT_BLACKLIST:1}
    vevote_comments: ${VERSION_VEVOTE_COMMENTS:1}

comments:
  minLength: ${MIN_COMMENT_LEN:10}
  language:
    confidence: ${LANGUAGE_CONFIDENCE:0.9}