server:
  ssl:
    trusted-certificates: /etc/ssl/cert.pem
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: vechain-indexer
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:indexer,nft-events,transactions,transfer-events,history-events}
  output:
    ansi:
      enabled: always

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL:#{null}}

logging:
  level:
    ROOT: INFO
    org:
      vechain: ${APP_LOG_LEVEL:INFO}
      springframework:
        data: INFO

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always

spring.data:
  mongodb:
    uri: ${MONGO_URI:mongodb://indexer:password@localhost:27017/vechain?authSource=admin}

thor:
  url: ${THOR_URL:http://localhost:8669}

abis:
  path: ${ABI_PATH:abis}

business-event:
  path: ${BUSINESS_EVENTS_PATH:business-events}
  substitutions:
    B3TR_CONTRACT: ${B3TR_CONTRACT:0x5ef79995fe8a89e0812330e4378eb2660cede699}
    VOT3_CONTRACT: ${VOT3_CONTRACT:0x76ca782b59c74d088c7d2cce2f211bc00836c602}
    B3TR_GOVERNOR_CONTRACT: ${B3TR_GOVERNOR_CONTRACT:0x1c65c25fabe2fc1bcb82f253fa0c916a322f777c}
    GM_NFT_CONTRACT: ${GM_NFT_CONTRACT:0x93b8cd34a7fc4f53271b9011161f7a2b5fea9d1f}
    X_ALLOC_VOTING_CONTRACT: ${X_ALLOC_VOTING_CONTRACT:0x89a00bb0947a30ff95beef77a66aede3842fe5b7}
    X2EARN_REWARDS_POOL_CONTRACT: ${X2EARN_REWARDS_POOL_CONTRACT:0x6bee7ddab6c99d5b2af0554eaea484ce18f52631}
    VOTER_REWARDS_CONTRACT: ${VOTER_REWARDS_CONTRACT:0x838a33af756a6366f93e201423e1425f67ec0fa7}
    TREASURY_CONTRACT: ${TREASURY_CONTRACT:0xd5903bcc66e439c753e525f8af2fec7be2429593}
    STARGATE_DELEGATION_CONTRACT: ${STARGATE_DELEGATION_CONTRACT:0x7240e3bc0d26431512d5b67dbd26d199205bffe8}
    STARGATE_NFT_CONTRACT: ${STARGATE_NFT_CONTRACT:0x1ec1d168574603ec35b9d229843b7c2b44bcb770}

veworld:
  contract:
    vevote:
      address: ${VEVOTE_CONTRACT:0x90a3c072CF8493cCDd9b86B1C9b5d18F86fdf3E0}
    authority_node:
      address: ${AUTHORITY_CONTRACT:0x0000000000000000000000417574686f72697479}

indexer:
  startBlock:
    nfts: ${INDEXER_START_BLOCK_NFTS:0}
    nft_blacklist: ${INDEXER_START_BLOCK_NFT_BLACKLIST:0}
    transactions: ${INDEXER_START_BLOCK_TRANSACTIONS:0}
    transfers: ${INDEXER_START_BLOCK_TRANSFERS:0}
    history: ${INDEXER_START_BLOCK_HISTORY:0}
    vevote: ${INDEXER_START_BLOCK_VEVOTE:0}
    authorityNodes: ${INDEXER_START_BLOCK_AUTHORITY_NODE:0}
    stargate: ${INDEXER_START_BLOCK_STARGATE:0}
  syncLogInterval:
    nfts: ${INDEXER_SYNC_LOGGER_INTERVAL_NFTS:1000}
    transactions: ${INDEXER_SYNC_LOGGER_INTERVAL_TRANSACTIONS:1000}
    transfers: ${INDEXER_SYNC_LOGGER_INTERVAL_TRANSFERS:1000}
    history: ${INDEXER_SYNC_LOGGER_INTERVAL_HISTORY:1000}
    vevote: ${INDEXER_SYNC_LOGGER_INTERVAL_VEVOTE:1000}
    authorityNodes: ${INDEXER_SYNC_LOGGER_AUTHORITY_NODE:1000}
    stargate: ${INDEXER_SYNC_LOGGER_INTERVAL_STARGATE:1000}
  syncBlockBatchSize:
    nfts: ${INDEXER_SYNC_BLOCK_BATCH_SIZE_NFTS:100}
    transfers: ${INDEXER_SYNC_BLOCK_BATCH_SIZE_TRANSFERS:100}
    vevote: ${INDEXER_SYNC_BLOCK_BATCH_SIZE_VEVOTE:1000}
    authorityNodes: ${INDEXER_SYNC_BLOCK_BATCH_SIZE_AUTHORITY_NODE:1000}
    stargate: ${INDEXER_SYNC_BLOCK_BATCH_SIZE_STARGATE:100}
  pruner:
    enabled: ${PRUNER_ENABLED:true}
    interval: ${PRUNER_INTERVAL:300000}
    initialDelay: ${PRUNER_INITIAL_DELAY:300000}
    removalChunkSize: ${PRUNER_REMOVAL_CHUNK_SIZE:10000}
  blacklist:
    contract_address: ${BLACKLIST_CONTRACT_ADDRESS:0x0f9b01618cd5e0030f8e26ff61bc1349cb9eb8d5}
    initialDelay: ${BLACKLIST_INITIAL_DELAY:1}
    interval: ${BLACKLIST_INTERVAL:1800000}
  version:
    nfts: ${VERSION_NFTS:1}
    transfers: ${VERSION_TRANSFERS:1}
    transactions: ${VERSION_TRANSACTIONS:1}
    history: ${VERSION_HISTORY:1}
    nft_blacklist: ${VERSION_NFT_BLACKLIST:1}
    vevote_comments: ${VERSION_VEVOTE_COMMENTS:1}
    vevote_results: ${VERSION_VEVOTE_RESULTS:1}
    stargate_vtho_claimed_by_block: ${VERSION_STARGATE_VTHO_CLAIMED_BY_BLOCK:1}
    stargate_vtho_claimed_by_account: ${VERSION_STARGATE_VTHO_CLAIMED_BY_ACCOUNT:1}
    stargate_nft_holders_by_block: ${VERSION_STARGATE_NFT_HOLDERS_BY_BLOCK:1}
    stargate_vet_staked_by_block: ${VERSION_STARGATE_VET_STAKED_BY_BLOCK:1}
    authority_node_endorser: ${VERSION_AUTHORITY_NODE_ENDORSER:1}

comments:
  minLength: ${MIN_COMMENT_LEN:10}
  language:
    confidence: ${LANGUAGE_CONFIDENCE:0.9}