server:
  ssl:
    trusted-certificates: /etc/ssl/cert.pem
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: vechain-indexer
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:indexer,vevote-events}
  output:
    ansi:
      enabled: always

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL:#{null}}

logging:
  level:
    ROOT: INFO
    org:
      vechain: ${APP_LOG_LEVEL:INFO}
      springframework:
        data: INFO

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: 'health'
  endpoint:
    health:
      show-details: always

spring.data:
  mongodb:
    uri: ${MONGO_URI:mongodb://indexer:password@localhost:27017/vechain?authSource=admin}

thor:
  url: ${THOR_URL:https://testnet.vechain.org}

abis:
  path: ${ABI_PATH:abis}

businessEvents:
  path: ${BUSINESS_EVENTS_PATH:businessEvents}

veworld:
  contract:
    vevote:
      address: ${VEVOTE_CONTRACT:0xfcc8f0d6ef2eef8d6fcf376ecf42d7851171a5cc}

indexer:
  startBlock:
    nfts: ${INDEXER_START_BLOCK_NFTS:20136054}
    transactions: ${INDEXER_START_BLOCK_TRANSACTIONS:20136054}
    transfers: ${INDEXER_START_BLOCK_TRANSFERS:20136054}
    history: ${INDEXER_START_BLOCK_HISTORY:20136054}
    vevote: ${INDEXER_START_BLOCK_VEVOTE:21432863}
  syncLogInterval:
    nfts: ${INDEXER_SYNC_LOGGER_INTERVAL_NFTS:1000}
    transactions: ${INDEXER_SYNC_LOGGER_INTERVAL_TRANSACTIONS:1000}
    transfers: ${INDEXER_SYNC_LOGGER_INTERVAL_TRANSFERS:1000}
    history: ${INDEXER_SYNC_LOGGER_INTERVAL_HISTORY:1000}
    vevote: ${INDEXER_SYNC_LOGGER_INTERVAL_VEVOTE:1000}
  syncBlockBatchSize:
    nfts: ${INDEXER_SYNC_BLOCK_BATCH_SIZE_NFTS:100}
    transfers: ${INDEXER_SYNC_BLOCK_BATCH_SIZE_TRANSFERS:100}
    vevote: ${INDEXER_SYNC_BLOCK_BATCH_SIZE_VEVOTE:100}
  pruner:
    enabled: ${PRUNER_ENABLED:true}
    interval: ${PRUNER_INTERVAL:300000}
    initialDelay: ${PRUNER_INITIAL_DELAY:300000}
    removalChunkSize: ${PRUNER_REMOVAL_CHUNK_SIZE:10000}

comments:
  minLength: ${MIN_COMMENT_LEN:10}