package org.vechain.indexer.accounts

import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.enums.ParameterIn
import io.swagger.v3.oas.annotations.tags.Tag
import org.springframework.context.annotation.Profile
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import org.vechain.indexer.constants.API_ROOT
import org.vechain.indexer.constants.API_VERSION
import org.vechain.indexer.docs.AddressParameter
import org.vechain.indexer.docs.AfterParameter
import org.vechain.indexer.docs.BeforeParameter
import org.vechain.indexer.docs.CommonApiResponses
import org.vechain.indexer.exception.ResourceNotFoundException
import org.vechain.indexer.rest.CacheFor
import org.vechain.indexer.rest.CachePolicy
import org.vechain.indexer.rest.cachedByAge
import org.vechain.indexer.thor.Address
import org.vechain.indexer.utils.TimeValidationUtils
import org.vechain.indexer.validation.ValidAddress
import org.vechain.indexer.validation.ValidNonNegativeLong

@Profile("accounts")
@Tag(name = "Accounts", description = "Account totals and the VTHO each account has earned.")
@Validated
@RestController
@RequestMapping(API_ROOT)
open class AccountsController(private val accountsService: AccountsService) {
    @GetMapping("/v2/accounts/totals")
    @Operation(
        summary = "Get the number of accounts over time",
        description =
            """
            Total number of accounts on VeChain over time, for charting.

            Each point is a running total, so subtract one point from the next to get the accounts
            added in between. Point spacing depends on the length of the range: every block for
            short ranges, then hourly, daily, weekly or monthly as it grows. The response also
            includes the last point at or before each end of the range, so a chart line reaches both
            edges.
            """,
    )
    @AfterParameter(name = "startTimestamp", required = true)
    @BeforeParameter(name = "endTimestamp", required = true)
    @CommonApiResponses
    @CacheFor(CachePolicy.VOLATILE)
    open fun getTotalAccountsV2(
        @ValidNonNegativeLong @RequestParam startTimestamp: Long,
        @ValidNonNegativeLong @RequestParam endTimestamp: Long,
    ): ResponseEntity<List<AccountTotalsSeries>> {
        TimeValidationUtils.validateTimestamps(
            startTimestamp,
            endTimestamp,
            "startTimestamp",
            "endTimestamp",
        )
        return cachedByAge(
            endTimestamp,
            accountsService.getTotalSeries(startTimestamp, endTimestamp),
        )
    }

    @GetMapping("/v2/accounts/total")
    @Operation(
        summary = "Get total accounts on VeChain",
        description = "The number of accounts that have appeared on VeChain so far.",
    )
    @CommonApiResponses
    @CacheFor(CachePolicy.TEN_MINUTES)
    open fun getTotalAccountsLatest(): Long =
        accountsService.getTotalAccountsLatest()
            ?: throw ResourceNotFoundException("Total accounts not found")

    @GetMapping("$API_VERSION/accounts/overview/{address}")
    @Operation(
        summary = "Get the VTHO an account has earned",
        description =
            """
            VTHO an account has earned, by source, with a total:

            - Block rewards, as an authority node before Hayabusa or as a validator after it
            - VTHO generated by holding VET (genesis to Hayabusa only)
            - VTHO claimed from Stargate delegation
            """,
    )
    @AddressParameter(
        name = "address",
        `in` = ParameterIn.PATH,
        required = true,
        description = "Account address.",
    )
    @CommonApiResponses
    @CacheFor(CachePolicy.TEN_MINUTES)
    open fun getOverview(@ValidAddress @PathVariable address: Address): AccountOverviewResponse =
        accountsService.getOverviewWithVthoEarnings(address)
            ?: throw ResourceNotFoundException("Account overview not found for address $address")
}
