version: "3"

services:

  influxdb:
    image: influxdb:1.8
    hostname: influxdb
    networks:
      - vechain
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    healthcheck:
      test: [ "CMD", "curl", "influxdb:8086/api/v2/ping" ]
      interval: 3s
      timeout: 10s
      retries: 30
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    networks:
      - vechain
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana-config:/var/lib/grafana
    healthcheck:
      test: [ "CMD", "grafana-cli", "plugins", "ls" ]
      interval: 3s
      timeout: 10s
      retries: 30

  k6-app-nfts:
    build:
      context: .
      dockerfile: Dockerfile
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/nfts-test.js
    environment:
      - API_URL=http://vechain-indexer-api:8080
    volumes:
      - ./.output:/app/.output
    networks:
      - vechain
      - vechain-database
    depends_on:
      influxdb:
        condition: service_healthy
      grafana:
        condition: service_healthy

  k6-app-transactions:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/transactions-test.js

networks:
  vechain:
    external: true
    name: vechain
  vechain-database:
    external: true
    name: vechain-database
  

volumes:
  influxdb: