version: "3"

services:

  influxdb:
    image: influxdb:1.8
    hostname: influxdb
    networks:
      - vechain
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    healthcheck:
      test: [ "CMD", "curl", "influxdb:8086/api/v2/ping" ]
      interval: 3s
      timeout: 10s
      retries: 30

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    networks:
      - vechain
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana-config:/var/lib/grafana
    healthcheck:
      test: [ "CMD", "grafana-cli", "plugins", "ls" ]
      interval: 3s
      timeout: 10s
      retries: 30

  k6-app-nfts:
    build:
      context: .
      dockerfile: Dockerfile
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/nfts-by-owner-test.js
    environment:
      - API_URL=https://veworld.mainnet.indexer.dev-vechain.org
    volumes:
      - ./.output:/app/.output
    networks:
      - vechain
    depends_on:
      influxdb:
        condition: service_healthy
      grafana:
        condition: service_healthy

  k6-app-nfts-by-owner-contract:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/nfts-by-owner-contract-address-test.js

  k6-app-nft-contracts:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/nfts-contracts-test.js

  k6-app-fungibles-contracts:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/fungible-tokens-contracts-by-owner-test.js

  k6-app-transactions-origin:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/transactions-by-origin-test.js

  k6-app-transactions-delegator:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/transactions-by-delegator-test.js

  k6-app-transactions-origin-delegator:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/transactions-by-origin-delegator-test.js

  k6-app-transfer-events-address:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/transfer-events-by-address-test.js

  k6-app-transfer-events-destination:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/transfer-events-by-destination-test.js

  k6-app-transfer-events-origin:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/transfer-events-by-origin-test.js

  k6-app-transfer-events-token-address:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/transfer-events-by-token-address-test.js

  k6-app-fungible-tokens-contracts-by-address:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/fungible-tokens-contracts-by-account-test.js

  k6-app-contracts-creator:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/contracts-by-creator-test.js

  k6-app-contracts-type:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/contracts-by-type-test.js

  k6-app-blocks:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/blocks-test.js

  k6-app-clauses:
    extends:
      service: k6-app-nfts
    command: run --out influxdb=http://influxdb:8086/k6 /app/dist/clauses-test.js

networks:
  vechain:
    #    external: true
    name: vechain

volumes:
  grafana:
  influxdb:
