image_tag:                       dev-latest
region:                          eu-west-1
common_ecr_repo_root:            veworld
environment:                     dev
application:                     veworld
root_domain:                     dev.vechain.org
slack_channel_id:                C05NA25LG78
slack_workspace_id:              T03L3PQD8GK
certificate_arn:                 arn:aws:acm:eu-west-1:937628727224:certificate/67184736-cc67-4d9c-990e-905e018a2d4e
azs:
  -                              eu-west-1a
  -                              eu-west-1b
  -                              eu-west-1c
cidr:                            172.31.0.0/20
public_subnets:
  -                              172.31.0.0/24
  -                              172.31.4.0/24
  -                              172.31.8.0/24
private_subnets:
  -                              172.31.1.0/24
  -                              172.31.5.0/24
  -                              172.31.9.0/24
database_subnets:
  -                              172.31.2.0/24
  -                              172.31.6.0/24
  -                              172.31.10.0/24
cloudwatch_alarms:               true
slack_alert_channel:             C05NA25LG78
slack_alert_workspace:           T03L3PQD8GK
mongoatlas_project_id:           64d6337acba67e1132a3a4e1
mongodb_secret_arn:              arn:aws:secretsmanager:eu-west-1:937628727224:secret:dev/mongo-atlas-api-WxcxJo
waf_profile:
  networks:
    testnet:
      origin_domain: indexer.testnet.vechain.org
      cnames:
        - cache.indexer.testnet.vechain.org
  logging_redacted_fields:
    - redactAuthorizationToken:
      all_query_arguments: null
      body: ""
      method: ""
      query_string: ""
      single_header: "user-agent"
      single_query_argument: ""
      uri_path: ""
  logging_filter:
    - default_behavior: "DROP"
      filter:
        - behavior: "KEEP"
          requirement: "MEETS_ALL"
          condition:
            - label_name_condition: "waf_glob_rl"
              action_condition: 
  rate_based_rules: 
    - name: "rate_limit_rule"
      priority: 1
      rate_based_statement:
        limit: 300
        aggregate_key_type: "IP"
        scope_down_statement:
          byte_match_statement:
            field_to_match:
              uri_path: {}
            positional_constraint: "STARTS_WITH"
            search_string: "/api/v1"
            text_transformation:
              priority: 1
              type: "LOWERCASE"
      action: "COUNT"
  managed_rule_group_statement_rules: 
    - managed_rule_group_statement:
      name: "RateBasedRule-IP-300-CreatedByCloudFront"
      vendor_name: "AWS"
      priority: 1
      override_action: "COUNT"
    - managed_rule_group_statement:
      name: "AWSManagedRulesAmazonIpReputationList"
      vendor_name: "AWS"
      priority: 2
      override_action: ""
    - managed_rule_group_statement:
      name: "AWSManagedRulesCommonRuleSet"
      vendor_name: "AWS"
      priority: 3
      excluded_rule:
        - name: "NoUserAgent_HEADER"
      override_action: ""
    - managed_rule_group_statement:
      name: "AWSManagedRulesKnownBadInputsRuleSet"
      vendor_name: "AWS"
      priority: 4
      override_action: ""
    - managed_rule_group_statement:
      name: "AWSManagedRulesSQLiRuleSet"
      vendor_name: "AWS"
      priority: 5
      override_action: ""
cdn_api_paths:
  - "/api/v1/stargate/nft-holders/historic/1-hour"
  - "/api/v1/stargate/nft-holders/historic/1-day"
  - "/api/v1/stargate/nft-holders/historic/1-week"
  - "/api/v1/stargate/nft-holders/historic/1-month"
  - "/api/v1/stargate/nft-holders/historic/1-year"
  - "/api/v1/stargate/nft-holders/historic/all"
