{
 "title": "Indexing Metrics",
 "tags": [
  "indexer",
  "processor"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "indexer",
    "label": "Indexer",
    "query": {
     "query": "label_values(indexer_sync_status_code_gauge,indexer_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Indexer Sync Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Best Block Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(deployment_scope) (thor_best_block_number_gauge)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events Per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(processor_events_counter_total{indexer_name=~\"$indexer\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Block Processing Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 * sum(increase(processor_duration_seconds_sum{indexer_name=~\"$indexer\"}[$__range])) / sum(increase(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[$__range])) and sum(increase(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_readable) (last_over_time(indexer_sync_status_gauge{indexer_name=~\"$indexer\"}[15m]) and on(instance,job) (up{job=~\"indexer|indexer-local\"} == 1))",
     "legendFormat": "{{status_readable}}"
    },
    {
     "expr": "label_replace(sum((((last_over_time(indexer_sync_status_code_gauge{indexer_name=~\"$indexer\"}[15m]) * 0) + 1) and on(instance,job) (up{job=~\"indexer|indexer-local\"} == 0))), \"status_readable\", \"Shut Down\", \"\", \"\")",
     "legendFormat": "{{status_readable}}"
    }
   ]
  },
  {
   "title": "Indexer Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "max by(indexer_name) ((last_over_time(indexer_sync_status_code_gauge{indexer_name=~\"$indexer\"}[15m]) and on(instance,job) (up{job=~\"indexer|indexer-local\"} == 1)) or (((last_over_time(indexer_sync_status_code_gauge{indexer_name=~\"$indexer\"}[15m]) * 0) + 5) and on(instance,job) (up{job=~\"indexer|indexer-local\"} == 0)))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(indexer_name) (last_over_time(indexer_sync_gap_gauge{indexer_name=~\"$indexer\"}[15m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(indexer_name) (indexer_sync_gap_gauge{indexer_name=~\"$indexer\"}) * on(indexer_name) group_left() (sum by(indexer_name) (increase(processor_cycle_time_seconds_sum{indexer_name=~\"$indexer\"}[$__range])) / sum by(indexer_name) (increase(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[$__range])) and sum by(indexer_name) (increase(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[$__range])) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 * sum by(indexer_name) (increase(processor_duration_seconds_sum{indexer_name=~\"$indexer\"}[$__range])) / sum by(indexer_name) (increase(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[$__range])) and sum by(indexer_name) (increase(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[$__range])) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(indexer_name) (increase(processor_events_counter_total{indexer_name=~\"$indexer\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000 * sum by(indexer_name) (increase(processor_cycle_time_seconds_sum{indexer_name=~\"$indexer\"}[$__range])) / sum by(indexer_name) (increase(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[$__range])) and sum by(indexer_name) (increase(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max by(indexer_name) (indexer_blocks_per_second_gauge{indexer_name=~\"$indexer\"})",
     "legendFormat": "{{indexer_name}}"
    }
   ]
  },
  {
   "title": "Processing Duration Per Block (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * sum by(indexer_name) (rate(processor_duration_seconds_sum{indexer_name=~\"$indexer\"}[5m])) / sum by(indexer_name) (rate(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[5m])) and sum by(indexer_name) (rate(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[5m])) > 0",
     "legendFormat": "{{indexer_name}}"
    }
   ]
  },
  {
   "title": "Processing Duration P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.95, sum by(le, indexer_name) (rate(processor_duration_seconds_bucket{indexer_name=~\"$indexer\"}[$__rate_interval])))",
     "legendFormat": "{{indexer_name}}"
    }
   ]
  },
  {
   "title": "Block Cycle Time Per Block (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * sum by(indexer_name) (rate(processor_cycle_time_seconds_sum{indexer_name=~\"$indexer\"}[5m])) / sum by(indexer_name) (rate(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[5m])) and sum by(indexer_name) (rate(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[5m])) > 0",
     "legendFormat": "{{indexer_name}}"
    }
   ]
  },
  {
   "title": "Block Cycle Time P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.95, sum by(le, indexer_name) (rate(processor_cycle_time_seconds_bucket{indexer_name=~\"$indexer\"}[$__rate_interval])))",
     "legendFormat": "{{indexer_name}}"
    }
   ]
  },
  {
   "title": "Avg Block Processing Time by Indexer",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(1000 * sum by(indexer_name) (increase(processor_duration_seconds_sum{indexer_name=~\"$indexer\"}[$__range])) / sum by(indexer_name) (increase(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[$__range])) and sum by(indexer_name) (increase(indexer_blocks_processed_total{indexer_name=~\"$indexer\"}[$__range])) > 0)",
     "legendFormat": "{{indexer_name}}"
    }
   ]
  },
  {
   "title": "Events by Indexer",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by(indexer_name) (increase(processor_events_counter_total{indexer_name=~\"$indexer\"}[$__range])))",
     "legendFormat": "{{indexer_name}}"
    }
   ]
  },
  {
   "title": "Events Processed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(indexer_name) (rate(processor_events_counter_total{indexer_name=~\"$indexer\"}[$__rate_interval]))",
     "legendFormat": "{{indexer_name}}"
    }
   ]
  }
 ]
}