package org.vechain.indexer.b3tr.challenges

import java.math.BigInteger
import org.web3j.utils.Convert

data class B3trChallengeResponse(
    val challengeId: Long,
    val kind: ChallengeKind,
    val visibility: ChallengeVisibility,
    val thresholdMode: ThresholdMode,
    val status: ChallengeStatus,
    val settlementMode: SettlementMode,
    val creator: String,
    val title: String,
    val description: String,
    val imageURI: String,
    val metadataURI: String,
    val stakeAmount: BigInteger,
    val startRound: Int,
    val endRound: Int,
    val duration: Int,
    val threshold: BigInteger,
    val allApps: Boolean,
    val totalPrize: BigInteger,
    val participantCount: Int,
    val invitedCount: Int,
    val declinedCount: Int,
    val selectedAppsCount: Int,
    val bestScore: BigInteger,
    val bestCount: Int,
    val qualifiedCount: Int,
    val payoutsClaimed: Int,
    val createdAtBlockNumber: Long,
    val createdAtBlockTimestamp: Long,
    val createdTxId: String,
) {
    companion object {
        fun from(challenge: B3trChallenge, status: ChallengeStatus): B3trChallengeResponse =
            B3trChallengeResponse(
                challengeId = challenge.challengeId,
                kind = challenge.kind,
                visibility = challenge.visibility,
                thresholdMode = challenge.thresholdMode,
                status = status,
                settlementMode = challenge.settlementMode,
                creator = challenge.creator,
                title = challenge.title,
                description = challenge.description,
                imageURI = challenge.imageURI,
                metadataURI = challenge.metadataURI,
                stakeAmount = challenge.stakeAmount,
                startRound = challenge.startRound,
                endRound = challenge.endRound,
                duration = challenge.duration,
                threshold = challenge.threshold,
                allApps = challenge.allApps,
                totalPrize = challenge.totalPrize,
                participantCount = challenge.participantCount,
                invitedCount = challenge.invitedCount,
                declinedCount = challenge.declinedCount,
                selectedAppsCount = challenge.selectedAppsCount,
                bestScore = challenge.bestScore,
                bestCount = challenge.bestCount,
                qualifiedCount = challenge.qualifiedCount,
                payoutsClaimed = challenge.payoutsClaimed,
                createdAtBlockNumber = challenge.createdAtBlockNumber,
                createdAtBlockTimestamp = challenge.createdAtBlockTimestamp,
                createdTxId = challenge.createdTxId,
            )
    }
}

data class B3trChallengeDetailResponse(
    val challengeId: Long,
    val createdAt: Long,
    val kind: ChallengeKind,
    val visibility: ChallengeVisibility,
    val thresholdMode: ThresholdMode,
    val status: ChallengeStatus,
    val settlementMode: SettlementMode,
    val creator: String,
    val title: String,
    val description: String,
    val imageURI: String,
    val metadataURI: String,
    val stakeAmount: String,
    val totalPrize: String,
    val startRound: Int,
    val endRound: Int,
    val duration: Int,
    val threshold: String,
    val allApps: Boolean,
    val participantCount: Int,
    val maxParticipants: Int,
    val invitedCount: Int,
    val declinedCount: Int,
    val selectedAppsCount: Int,
    val viewerStatus: ParticipantStatus,
    val isCreator: Boolean,
    val isJoined: Boolean,
    val isInvitationPending: Boolean,
    val canJoin: Boolean,
    val canLeave: Boolean,
    val canAccept: Boolean,
    val canDecline: Boolean,
    val canCancel: Boolean,
    val canAddInvites: Boolean,
    val canClaim: Boolean,
    val canRefund: Boolean,
    val canFinalize: Boolean,
    val participants: List<String>,
    val invited: List<String>,
    val declined: List<String>,
    val selectedApps: List<String>,
) {
    companion object {
        internal fun from(
            challenge: B3trChallenge,
            state: ChallengeUiState,
        ): B3trChallengeDetailResponse =
            B3trChallengeDetailResponse(
                challengeId = challenge.challengeId,
                createdAt = challenge.createdAtBlockTimestamp,
                kind = challenge.kind,
                visibility = challenge.visibility,
                thresholdMode = challenge.thresholdMode,
                status = state.status,
                settlementMode = challenge.settlementMode,
                creator = challenge.creator,
                title = challenge.title,
                description = challenge.description,
                imageURI = challenge.imageURI,
                metadataURI = challenge.metadataURI,
                stakeAmount = formatTokenAmount(challenge.stakeAmount),
                totalPrize = formatTokenAmount(challenge.totalPrize),
                startRound = challenge.startRound,
                endRound = challenge.endRound,
                duration = challenge.duration,
                threshold = challenge.threshold.toString(),
                allApps = challenge.allApps,
                participantCount = challenge.participantCount,
                maxParticipants = state.maxParticipants,
                invitedCount = challenge.invitedCount,
                declinedCount = challenge.declinedCount,
                selectedAppsCount = challenge.selectedAppsCount,
                viewerStatus = state.viewerStatus,
                isCreator = state.isCreator,
                isJoined = state.isJoined,
                isInvitationPending = state.isInvitationPending,
                canJoin = state.canJoin,
                canLeave = state.canLeave,
                canAccept = state.canAccept,
                canDecline = state.canDecline,
                canCancel = state.canCancel,
                canAddInvites = state.canAddInvites,
                canClaim = state.canClaim,
                canRefund = state.canRefund,
                canFinalize = state.canFinalize,
                participants = challenge.participants,
                invited = challenge.invited,
                declined = challenge.declined,
                selectedApps = challenge.selectedApps,
            )
    }
}

private fun formatTokenAmount(value: BigInteger): String =
    Convert.fromWei(value.toString(), Convert.Unit.ETHER).stripTrailingZeros().toPlainString()
