package org.vechain.indexer.b3tr.challenges

import java.math.BigInteger

data class B3trChallengeResponse(
    val challengeId: Long,
    val kind: ChallengeKind,
    val visibility: ChallengeVisibility,
    val thresholdMode: ThresholdMode,
    val status: ChallengeStatus,
    val settlementMode: SettlementMode,
    val creator: String,
    val stakeAmount: BigInteger,
    val startRound: Int,
    val endRound: Int,
    val duration: Int,
    val threshold: BigInteger,
    val allApps: Boolean,
    val totalPrize: BigInteger,
    val participantCount: Int,
    val invitedCount: Int,
    val declinedCount: Int,
    val selectedAppsCount: Int,
    val bestScore: BigInteger,
    val bestCount: Int,
    val qualifiedCount: Int,
    val payoutsClaimed: Int,
    val createdAtBlockNumber: Long,
    val createdAtBlockTimestamp: Long,
    val createdTxId: String,
) {
    companion object {
        fun from(challenge: B3trChallenge, status: ChallengeStatus): B3trChallengeResponse =
            B3trChallengeResponse(
                challengeId = challenge.challengeId,
                kind = challenge.kind,
                visibility = challenge.visibility,
                thresholdMode = challenge.thresholdMode,
                status = status,
                settlementMode = challenge.settlementMode,
                creator = challenge.creator,
                stakeAmount = challenge.stakeAmount,
                startRound = challenge.startRound,
                endRound = challenge.endRound,
                duration = challenge.duration,
                threshold = challenge.threshold,
                allApps = challenge.allApps,
                totalPrize = challenge.totalPrize,
                participantCount = challenge.participantCount,
                invitedCount = challenge.invitedCount,
                declinedCount = challenge.declinedCount,
                selectedAppsCount = challenge.selectedAppsCount,
                bestScore = challenge.bestScore,
                bestCount = challenge.bestCount,
                qualifiedCount = challenge.qualifiedCount,
                payoutsClaimed = challenge.payoutsClaimed,
                createdAtBlockNumber = challenge.createdAtBlockNumber,
                createdAtBlockTimestamp = challenge.createdAtBlockTimestamp,
                createdTxId = challenge.createdTxId,
            )
    }
}

data class B3trChallengeDetailResponse(
    val challengeId: Long,
    val kind: ChallengeKind,
    val visibility: ChallengeVisibility,
    val thresholdMode: ThresholdMode,
    val status: ChallengeStatus,
    val settlementMode: SettlementMode,
    val creator: String,
    val stakeAmount: BigInteger,
    val startRound: Int,
    val endRound: Int,
    val duration: Int,
    val threshold: BigInteger,
    val allApps: Boolean,
    val totalPrize: BigInteger,
    val participantCount: Int,
    val invitedCount: Int,
    val declinedCount: Int,
    val selectedAppsCount: Int,
    val bestScore: BigInteger,
    val bestCount: Int,
    val qualifiedCount: Int,
    val payoutsClaimed: Int,
    val participants: List<String>,
    val invited: List<String>,
    val declined: List<String>,
    val selectedApps: List<String>,
    val createdAtBlockNumber: Long,
    val createdAtBlockTimestamp: Long,
    val createdTxId: String,
) {
    companion object {
        fun from(challenge: B3trChallenge, status: ChallengeStatus): B3trChallengeDetailResponse =
            B3trChallengeDetailResponse(
                challengeId = challenge.challengeId,
                kind = challenge.kind,
                visibility = challenge.visibility,
                thresholdMode = challenge.thresholdMode,
                status = status,
                settlementMode = challenge.settlementMode,
                creator = challenge.creator,
                stakeAmount = challenge.stakeAmount,
                startRound = challenge.startRound,
                endRound = challenge.endRound,
                duration = challenge.duration,
                threshold = challenge.threshold,
                allApps = challenge.allApps,
                totalPrize = challenge.totalPrize,
                participantCount = challenge.participantCount,
                invitedCount = challenge.invitedCount,
                declinedCount = challenge.declinedCount,
                selectedAppsCount = challenge.selectedAppsCount,
                bestScore = challenge.bestScore,
                bestCount = challenge.bestCount,
                qualifiedCount = challenge.qualifiedCount,
                payoutsClaimed = challenge.payoutsClaimed,
                participants = challenge.participants,
                invited = challenge.invited,
                declined = challenge.declined,
                selectedApps = challenge.selectedApps,
                createdAtBlockNumber = challenge.createdAtBlockNumber,
                createdAtBlockTimestamp = challenge.createdAtBlockTimestamp,
                createdTxId = challenge.createdTxId,
            )
    }
}
