package org.vechain.indexer.performance.vthoGenerated

import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.beans.factory.annotation.Value
import org.springframework.test.context.ActiveProfiles
import org.vechain.indexer.BlockIndexer
import org.vechain.indexer.IndexerFactory
import org.vechain.indexer.IndexerNames
import org.vechain.indexer.IndexingResult
import org.vechain.indexer.checkpoint.CheckpointService
import org.vechain.indexer.config.metrics.ProcessorMetrics
import org.vechain.indexer.performance.BasePerformanceTest
import org.vechain.indexer.performance.DetailedProfiler
import org.vechain.indexer.stargate.StargateUtils
import org.vechain.indexer.stargate.vthoGenerated.VthoGeneratedByBlockProcessor
import org.vechain.indexer.stargate.vthoGenerated.VthoGeneratedByBlockRepository
import org.vechain.indexer.stargate.vthoGenerated.VthoGeneratedByBlockService

@Disabled("Performance test - run explicitly with --tests when needed")
@ActiveProfiles("vtho-generated-by-block")
class VthoGeneratedByBlockProcessorPerformanceTest : BasePerformanceTest() {

    @Autowired lateinit var vthoGeneratedByBlockRepository: VthoGeneratedByBlockRepository
    @Autowired lateinit var vthoGeneratedByBlockService: VthoGeneratedByBlockService
    @Autowired lateinit var checkpointService: CheckpointService
    @Autowired lateinit var processorMetrics: ProcessorMetrics

    @Value("\${business-event.substitutions.BUILTIN_STAKER_CONTRACT}")
    lateinit var stakerContract: String

    @Test
    fun `Performance test - 1000 blocks from mainnet`() {
        // Clear database to start fresh
        vthoGeneratedByBlockRepository.deleteAll()
        println("✓ Cleared VTHO generated by block database")

        // Create profiler for detailed timing analysis
        val profiler = DetailedProfiler()

        val config =
            PerformanceTestConfig(
                indexerName = IndexerNames.VTHO_GENERATED_BY_BLOCK.NAME,
                startBlock = 23430500L,
                blockCount = 1000,
                warmupBlocks = 0,
            )

        val metrics =
            runPerformanceTest(
                config = config,
                indexerBuilder = { startBlock ->
                    createVthoGeneratedByBlockIndexer(startBlock, profiler)
                },
                profiler = profiler,
            )

        // Print errors if any (for debugging)
        if (metrics.errors.isNotEmpty()) {
            println("\n⚠️  ERRORS ENCOUNTERED (${metrics.errors.size}):")
            metrics.errors.forEach { println("  - $it") }
            println()
        }

        // Assert performance targets
        assert(metrics.blocksPerSecond > 1.0) {
            "Performance too slow: ${metrics.blocksPerSecond} blocks/sec"
        }
    }

    private fun createVthoGeneratedByBlockIndexer(
        startBlock: Long,
        profiler: DetailedProfiler? = null,
    ): BlockIndexer {
        // Create profiled service and processor when profiler is provided
        val serviceToUse =
            if (profiler != null) {
                ProfiledVthoGeneratedByBlockService(
                    repository = vthoGeneratedByBlockRepository,
                    profiler = profiler,
                )
            } else {
                vthoGeneratedByBlockService
            }

        val processor =
            if (profiler != null) {
                ProfiledVthoGeneratedByBlockProcessor(
                    service = serviceToUse,
                    repository = vthoGeneratedByBlockRepository,
                    profiler = profiler,
                    checkpointService = checkpointService,
                    processorMetrics = processorMetrics,
                )
            } else {
                VthoGeneratedByBlockProcessor(
                    service = serviceToUse,
                    repository = vthoGeneratedByBlockRepository,
                    checkpointService = checkpointService,
                    processorMetrics = processorMetrics,
                )
            }

        return IndexerFactory()
            .name(IndexerNames.VTHO_GENERATED_BY_BLOCK.NAME)
            .thorClient(thorClient)
            .processor(processor)
            .startBlock(startBlock)
            .syncLoggerInterval(100L)
            .blockBatchSize(1L)
            .callDataClauses(StargateUtils.buildIssuanceClause(stakerContract))
            .includeFullBlock()
            .build()
    }

    /** Profiled wrapper for VthoGeneratedByBlockProcessor */
    private class ProfiledVthoGeneratedByBlockProcessor(
        service: VthoGeneratedByBlockService,
        repository: VthoGeneratedByBlockRepository,
        private val profiler: DetailedProfiler,
        checkpointService: CheckpointService,
        processorMetrics: ProcessorMetrics,
    ) :
        VthoGeneratedByBlockProcessor(
            service = service,
            repository = repository,
            checkpointService = checkpointService,
            processorMetrics = processorMetrics,
        ) {
        override suspend fun processEntry(entry: IndexingResult) {
            profiler.time("    VthoGeneratedByBlockProcessor.process (per block)") {
                super.processEntry(entry)
            }
        }
    }
}
