------------------------------------------------------------
-- STARGATE VTHO GENERATED BY BLOCK TABLE (non-versioned time-series)
------------------------------------------------------------
-- Tracks VTHO generated per block with time rollup calculations

CREATE TABLE IF NOT EXISTS stargate_vtho_generated_by_block (
    block_number BIGINT PRIMARY KEY,
    block_id TEXT NOT NULL,
    block_timestamp BIGINT NOT NULL,
    hour_of_day BIGINT NOT NULL,
    day_of_month BIGINT NOT NULL,
    week_of_year BIGINT NOT NULL,
    month BIGINT NOT NULL,
    year BIGINT NOT NULL,
    time_frames TEXT[] NOT NULL DEFAULT '{}',
    block_total NUMERIC,
    hour_total NUMERIC,
    day_total NUMERIC,
    week_total NUMERIC,
    month_total NUMERIC,
    year_total NUMERIC,
    total NUMERIC NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_vtho_generated_block_timestamp
    ON stargate_vtho_generated_by_block (block_timestamp);
CREATE INDEX IF NOT EXISTS idx_vtho_generated_time_frames
    ON stargate_vtho_generated_by_block USING GIN (time_frames);
