version: "3.7"

services:
  thor-solo:
    build:
      dockerfile: Dockerfile
      context: ./
    user: root
    ports:
      - "8669:8669"
      - "11235:11235"
    healthcheck:
      test: curl --fail 0.0.0.0:8669/blocks/0 || exit 1
      interval: 2s
      retries: 30
    volumes:
      - thor-volume:/data/thor
    networks:
      - vechain-thor

  thor-tx-script:
    hostname: thor-tx-script
    image: ghcr.io/vechainfoundation/thor-transactions-script:06057e4809a5424594701b05419d4ce6513c399c
    user: root
    depends_on:
      thor-solo:
        condition: service_healthy
    environment:
      # The node to point to, defaults to http://localhost:8669
      - NODE_URL=http://thor-solo:8669
      # The mnemonic to use. Defaults to Thor solo mnemonic
      - MNEMONIC_WORDS=denial kitchen pet squirrel other broom bar gas better priority spoil cross
      # How many times to iterate the mints and transfers. Defaults to 5
      - ITERATE_TX_AMOUNT=1
    volumes:
      - ./.output/:/app/.output
    networks:
      - vechain-thor

volumes:
  thor-volume:

networks:
  vechain-thor:
    driver: bridge
    name: vechain-thor
