version: '3.5'

services:
  mongo-node1:
    hostname: mongo-node1
    image: mongo:6
    #    command: mongod --replSet rs0
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    volumes:
      - vechain-data-1:/data/db
    deploy:
      resources:
        limits:
          memory: 4096m
        reservations:
          memory: 1024m
    networks:
      - vechain-database

networks:
  vechain-database:
    driver: bridge
    name: vechain-database

volumes:
  vechain-data-1:
