# NB: some manual assembly required.
# 1. appoint a target slack channel and add AWS Chatbot integration to it {channel setup->add apps->AWS Chatbot}
# 2. Enable AWS Chatbot in the AWS account and configure a new slack client for Vechain Foundation
# 3. under the new slack client configure a slack channel, private, selecting the target slack channel id
# with a role holding the ReadOnlyAccess policy, and a region local SNS notification topic
# latter two will be generated by terraform if a double pass apply is done

locals {
  sns_topic_enabled = var.sns_topic_enabled ? true : false
}

resource "aws_sns_topic" "sns_topic" {
  count = local.sns_topic_enabled ? 1 : 0

  name = var.topic_name
  # Add other SNS topic configuration as needed
}

data "aws_sns_topic" "sns" {
  count = local.sns_topic_enabled ? 0 : 1
  name  = var.topic_name
}

resource "aws_sns_topic_subscription" "email_subscription" {
  count     = local.sns_topic_enabled ? length(var.email_subscriptions) : 0
  topic_arn = aws_sns_topic.sns_topic[0].arn
  protocol  = "email"
  endpoint  = var.email_subscriptions[count.index]
}

resource "awscc_chatbot_slack_channel_configuration" "slack_integration" {
  count = var.create_slack_integration ? 1 : 0

  configuration_name = var.configuration_name
  slack_channel_id   = var.slack_channel_id
  slack_workspace_id = var.slack_workspace_id
  iam_role_arn       = aws_iam_role.cloudwatch_read[count.index].arn
  guardrail_policies = ["arn:aws:iam::aws:policy/ReadOnlyAccess"]
  sns_topic_arns     = local.sns_topic_enabled ? [aws_sns_topic.sns_topic[0].arn] : [data.aws_sns_topic.sns[0].arn]

}

resource "aws_cloudwatch_metric_alarm" "simple" {
  for_each = { for alarm_key, alarm_value in var.simple_alarms : alarm_key => alarm_value if alarm_value.alarm_name != null }

  alarm_name          = each.value.alarm_name
  comparison_operator = each.value.comparison_operator
  evaluation_periods  = each.value.evaluation_periods
  metric_name         = each.value.metric_name
  namespace           = each.value.namespace
  period              = each.value.period
  statistic           = each.value.statistic
  threshold           = each.value.threshold
  alarm_description   = each.value.alarm_description
  alarm_actions       = local.sns_topic_enabled ? [aws_sns_topic.sns_topic[0].arn] : [data.aws_sns_topic.sns[0].arn]
  dimensions          = each.value.dimensions != null ? each.value.dimensions : {}
}

resource "aws_cloudwatch_metric_alarm" "expression" {

  for_each = { for alarm_key, alarm_value in var.expression_alarms : alarm_key => alarm_value if alarm_value.alarm_name != null }

  alarm_name          = each.value.alarm_name
  comparison_operator = each.value.comparison_operator
  evaluation_periods  = each.value.evaluation_periods
  threshold           = each.value.threshold
  alarm_description   = each.value.alarm_description
  alarm_actions       = local.sns_topic_enabled ? [aws_sns_topic.sns_topic[0].arn] : [data.aws_sns_topic.sns[0].arn]

  dynamic "metric_query" {
    for_each = each.value.metric_query != null ? each.value.metric_query : []
    content {
      id          = metric_query.value.id
      expression  = lookup(metric_query.value, "expression", null)
      label       = lookup(metric_query.value, "label", null)
      return_data = lookup(metric_query.value, "return_data", null)

      dynamic "metric" {
        for_each = metric_query.value.metric != null ? metric_query.value.metric : []
        content {
          metric_name = metric.value.metric_name
          namespace   = metric.value.namespace
          period      = metric.value.period
          stat        = metric.value.stat
          unit        = metric.value.unit

          dimensions = metric.value.dimensions != null ? metric.value.dimensions : {}

        }
      }
    }
  }
}

resource "aws_iam_policy" "cloudwatch_policy" {
  count = var.create_slack_integration ? 1 : 0

  name        = "${var.configuration_name}-AwsChatBot-Slack-CloudWatch-ReadOnly"
  description = "IAM policy for CloudWatch access"

  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
              "logs:GetDataProtectionPolicy",
              "logs:GetDelivery",
              "logs:GetLogRecord",
              "logs:Describe*",
              "logs:List*",
              "logs:StartQuery",
              "logs:Unmask",
              "logs:GetDeliveryDestinationPolicy",
              "cloudwatch:List*",
              "logs:StopQuery",
              "logs:TestMetricFilter",
              "logs:GetDeliveryDestination",
              "logs:GetLogAnomalyDetector",
              "cloudwatch:Describe*",
              "logs:GetLogDelivery",
              "logs:GetDeliverySource",
              "logs:GetQueryResults",
              "logs:StartLiveTail",
              "logs:StopLiveTail",
              "logs:GetLogEvents",
              "logs:FilterLogEvents",
              "cloudwatch:Get*",
              "logs:GetLogGroupFields"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
EOF
}

resource "aws_iam_role" "cloudwatch_read" {
  count = var.create_slack_integration ? 1 : 0

  name = "${var.configuration_name}-AwsChatBot-Slack-CloudWatch-ReadOnly"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "chatbot.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_iam_role_policy_attachment" "attachment" {
  count      = var.create_slack_integration ? 1 : 0
  role       = aws_iam_role.cloudwatch_read[count.index].name
  policy_arn = aws_iam_policy.cloudwatch_policy[count.index].arn
}
