image_tag:                       dev-latest
region:                          eu-west-1
project:                         veworld
environment:                     dev
application:                     veworld
root_domain:                     vechain.org
slack_channel_id:                C05NA25LG78
slack_workspace_id:              T03L3PQD8GK
certificate_arn:                 arn:aws:acm:eu-west-1:937628727224:certificate/67184736-cc67-4d9c-990e-905e018a2d4e
azs:
  -                              eu-west-1a
  -                              eu-west-1b
  -                              eu-west-1c
cidr:                            172.31.0.0/20
public_subnets:
  -                              172.31.0.0/24
  -                              172.31.4.0/24
  -                              172.31.8.0/24
private_subnets:
  -                              172.31.1.0/24
  -                              172.31.5.0/24
  -                              172.31.9.0/24
database_subnets:
  -                              172.31.2.0/24
  -                              172.31.6.0/24
  -                              172.31.10.0/24
rate_limit:                      5000
rate_limit_exception_list:
  -                              185.57.113.46/32
  -                              81.39.47.171/32
  -                              90.26.60.41/32
cloudwatch_alarms:               true
mongoatlas_project_id:           67ee682c537792244670fa74
slack_secret_arn:                arn:aws:secretsmanager:eu-west-1:937628727224:secret:veworld-mongodb-alerts/slack/api-token-1z19Ev
datadog:
  secret_arn:                       arn:aws:secretsmanager:eu-west-1:937628727224:secret:dev/datadog_keys-oLrGKU
enabled_nets:
  main:
    image_version:                  dev-latest
    thor_url:                       https://mainnet.vechain.org
    api:
      cpu:                          256
      memory:                       512
      max_capacity:                 1
      spring_profile:               nft-events,transactions,transfer-events,history-events,vevote-comments,vevote-results,stargate
      ecr_common_repo:              937628727224.dkr.ecr.eu-west-1.amazonaws.com/veworld/api
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
    indexer:
      cpu:                          1024
      memory:                       2048
      enabled:                      true
      spring_profile:               "indexer,nft-events,transactions,transfer-events,history-events,vevote-comments,vevote-results,stargate"
      ecr_common_repo:              "937628727224.dkr.ecr.eu-west-1.amazonaws.com/veworld/indexer"
      slack_webhook_url:            ""
      start_block:
        nfts:                       '21300000'
        nft_blacklist:              '21300000'
        transactions:               '21300000'
        transfers:                  '21300000'
        history:                    '21300000'
        vevote:                     '21432703'
        stargate:                   '22044000'
      sync_logger_interval:
        nfts:                       '1000'
        transactions:               '1000'
        transfers:                  '1000'
        history:                    '1000'
        vevote:                     '1000'
        stargate:                   '1000'
      sync_block_batch_size:
        nfts:                       '400'
        transfers:                  '400'
        stargate:                   '10'
        vevote:                     '100'
      pruner:
        enabled: true
        interval: 300000
        initial_delay: 300000
        removal_chunk_size: 2000
      blacklist:
        contract_address:           '0x0f9b01618cd5e0030f8e26ff61bc1349cb9eb8d5'
        interval:                   '180000'
        initial_delay:              '60000'
      version:
        nfts:                       '3'
        transfers:                  '2'
        transactions:               '2'
        history:                    '6'
        nft_blacklist:              '3'
        vevote_comments:            '1'
        vevote_results:             '1'
        stargate_vtho_claimed_by_block: '4'
        stargate_vtho_claimed_by_account: '4'
        stargate_nft_holders_by_account: '4'
        stargate_vet_staked_by_account: '4'
      business-event:
        substitutions:
          B3TR_CONTRACT: '0x5ef79995fe8a89e0812330e4378eb2660cede699'
          VOT3_CONTRACT: '0x76ca782b59c74d088c7d2cce2f211bc00836c602'
          B3TR_GOVERNOR_CONTRACT: '0x1c65c25fabe2fc1bcb82f253fa0c916a322f777c'
          GM_NFT_CONTRACT: '0x93b8cd34a7fc4f53271b9011161f7a2b5fea9d1f'
          X_ALLOC_VOTING_CONTRACT: '0x89a00bb0947a30ff95beef77a66aede3842fe5b7'
          X2EARN_REWARDS_POOL_CONTRACT: '0x6bee7ddab6c99d5b2af0554eaea484ce18f52631'
          VOTER_REWARDS_CONTRACT: '0x838a33af756a6366f93e201423e1425f67ec0fa7'
          TREASURY_CONTRACT: '0xd5903bcc66e439c753e525f8af2fec7be2429593'
          STARGATE_DELEGATION_CONTRACT: '0x4cb1c9ef05b529c093371264fab2c93cc6cddb0e'
          STARGATE_NFT_CONTRACT: '0x1856c533ac2d94340aaa8544d35a5c1d4a21dee7'
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
        - name: "REORG"
          pattern: "REORG Detected"
          threshold: 1
    comments:
      minLength: 10
      language:
        confidence: '0.9'
    veworld:
      contract:
        vevote:
          address:                 '0x90a3c072cf8493ccdd9b86b1c9b5d18f86fdf3e0'
    mongodb:
      type:                         atlas
      fqdn:                         mainnet.imcfs.mongodb.net
      proto:                        mongodb+srv
      opts:                         retryWrites=true&w=majority
      cluster_tier:                 M40
      disk_size_gb:                 450
      iops:                         1000
      secret_arn:                   arn:aws:secretsmanager:eu-west-1:937628727224:secret:dev/mongo-atlas-api-WxcxJo
      auto_scaling_compute_max_instance_size: M50
      auto_scaling_compute_min_instance_size: M30
  # uncomment following top level label if testnet not required
  # disabled_nets:
  test:
    image_version:                  dev-latest
    thor_url:                       https://testnet.vechain.org
    api:
      cpu:                          256
      memory:                       512
      max_capacity:                 1
      spring_profile:               nft-events,transactions,transfer-events,history-events,vevote-comments,vevote-results,stargate
      ecr_common_repo:              937628727224.dkr.ecr.eu-west-1.amazonaws.com/veworld/api
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
    indexer:
      cpu:                          1024
      memory:                       2048
      enabled:                      true
      spring_profile:               "indexer,nft-events,transactions,transfer-events,history-events,vevote-comments,vevote-results,stargate"
      ecr_common_repo:              "937628727224.dkr.ecr.eu-west-1.amazonaws.com/veworld/indexer"
      slack_webhook_url:            ""
      start_block:
        nfts:                       '21300000'
        nft_blacklist:              '21300000'
        transactions:               '21300000'
        transfers:                  '21300000'
        history:                    '21300000'
        vevote:                     '21432703'
        stargate:                   '22087000'
      sync_logger_interval:
        nfts:                       '1000'
        transactions:               '1000'
        transfers:                  '1000'
        history:                    '1000'
        vevote:                     '1000'
        stargate:                   '1000'
      sync_block_batch_size:
        nfts:                       '400'
        transfers:                  '400'
        vevote:                     '10'
        stargate:                   '100'
      pruner:
        enabled: true
        interval: 300000
        initial_delay: 300000
        removal_chunk_size: 2000
      blacklist:
        contract_address:           '0x9405c18c384dd448f82c11136e188a147186ea3a'
        interval:                   '180000'
        initial_delay:              '60000'
      version:
        nfts:                       '3'
        transfers:                  '2'
        transactions:               '2'
        history:                    '6'
        nft_blacklist:              '3'
        vevote_comments:            '1'
        vevote_results:             '1'
        stargate_vtho_claimed_by_block: '4'
        stargate_vtho_claimed_by_account: '4'
        stargate_nft_holders_by_account: '4'
        stargate_vet_staked_by_account: '4'
      business-event:
        substitutions:
          B3TR_CONTRACT:             '0xbf64cf86894ee0877c4e7d03936e35ee8d8b864f'
          VOT3_CONTRACT:             '0xa704c45971995467696ee9544da77dd42bc9706e'
          B3TR_GOVERNOR_CONTRACT:    '0xdf5e114d391cac840529802fe8d01f6bdebe41ec'
          GM_NFT_CONTRACT:    '0xcf73039913e05aa1838d5869e72290d2b454c1e8'
          X_ALLOC_VOTING_CONTRACT:    '0x5859ff910d8b0c127364c98e24233b0af7443c1c'
          X2EARN_REWARDS_POOL_CONTRACT: '0x5f8f86b8d0fa93cdae20936d150175df0205fb38'
          VOTER_REWARDS_CONTRACT:    '0x2e47fc4aabb3403037fb5e1f38995e7a91ce8ed2'
          TREASURY_CONTRACT:         '0x039893ebe092a2d22b08e2b029735d211bff7f50'
          STARGATE_DELEGATION_CONTRACT: '0x7240e3bc0d26431512d5b67dbd26d199205bffe8'
          STARGATE_NFT_CONTRACT: '0x1ec1d168574603ec35b9d229843b7c2b44bcb770'
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
        - name: "REORG"
          pattern: "REORG Detected"
          threshold: 1
    comments:
      minLength: 10
      language:
        confidence: "0.9"
    veworld:
      contract:
        vevote:
          address:                "0x90a3c072cf8493ccdd9b86b1c9b5d18f86fdf3e0"
    mongodb:
      type:                         atlas
      fqdn:                         testnet.imcfs.mongodb.net
      proto:                        mongodb+srv
      opts:                         retryWrites=true&w=majority
      cluster_tier:                 M30
      disk_size_gb:                 125
      iops:                         1000
      secret_arn:                   arn:aws:secretsmanager:eu-west-1:937628727224:secret:dev/mongo-atlas-api-WxcxJo
      auto_scaling_compute_max_instance_size: M40
      auto_scaling_compute_min_instance_size: M30
