region:                          eu-west-1
project:                         veworld
environment:                     prod-green
certificate_arn:                 arn:aws:acm:eu-west-1:905964754131:certificate/695573a6-698a-4309-a427-28dd94fe7633
azs:
  -                              eu-west-1a
  -                              eu-west-1b
  -                              eu-west-1c
cidr:                            172.31.0.0/16
public_subnets:
  -                              172.31.96.0/20
  -                              172.31.112.0/20
  -                              172.31.0.0/20
private_subnets:
  -                              172.31.64.0/20
  -                              172.31.32.0/20
  -                              172.31.80.0/20
database_subnets:                null



rate_limit:                      '5000'
rate_limit_exception_list:
  -                              185.57.113.46/32
  -                              81.39.47.171/32
  -                              90.26.60.41/32
cloudwatch_alarms:               true
mongoatlas_project_id:           64d6337acba67e1132a3a4e1
slack_secret_arn:                arn:aws:secretsmanager:eu-west-1:905964754131:secret:veworld-mongodb-alerts/slack/api-token-NvxUZd
datadog:
  secret_arn:                       arn:aws:secretsmanager:eu-west-1:905964754131:secret:prod/datadog_keys-NFBO6v
enabled_nets:
  main:
    image_version:                  latest
    thor_url:                       https://mainnet.vechain.org
    api:
      cpu:                          512
      memory:                       1024
      max_capacity:                 4
      spring_profile:               nft-events,transactions,transfer-events,history-events
      ecr_common_repo:              905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/api
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
    indexer:
      cpu: 1024
      memory: 2048
      enabled: true
      spring_profile: indexer,nft-events,transactions,transfer-events,history-events
      ecr_common_repo: 905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/indexer
      slack_webhook_url: https://hooks.slack.com/services/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
      start_block:
        nfts:                       '1304112'
        nft_blacklist:              '21245914'
        transactions:               '751'
        transfers:                  '37840'
        history:                    '751'
        vevote:                     '21432703'
      sync_logger_interval:
        nfts:                       '1000'
        transactions:               '1000'
        transfers:                  '1000'
        history:                    '1000'
        vevote:                     '1000'
      sync_block_batch_size:
        nfts:                       '100'
        transfers:                  '100'
        vevote:                     '100'
      pruner:
        enabled: true
        interval:                   '43200000'
        initial_delay:              '300000'
        removal_chunk_size:         '2000'
      blacklist:
        contract_address:           '0x14091CC9Ae249f26EaF41a5A21207931162A2826'
        interval:                   '180000'
        initial_delay:              '60000'
      version:
        nfts:                       '2'
        transfers:                  '1'
        transactions:               '1'
        history:                    '2'
        nft_blacklist:              '1'
        vevote_comments:            '1'
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
        - name: "REORG"
          pattern: "REORG Detected"
          threshold: 1
    comments:
      minLength: 10
      language:
        confidence:                 '0.9'
    veworld:
      contract:
        vevote:
          address:                  '0x428BE069E21a584fBbAb934Fb4ad55AF346A3513'
    mongodb:
      type: atlas
      fqdn: mainnet.rsmhw.mongodb.net
      proto: mongodb+srv
      opts: retryWrites=true&w=majority
      cluster_tier: M40
      disk_size_gb: 256
      iops: 2000
      secret_arn: arn:aws:secretsmanager:eu-west-1:905964754131:secret:prod/mongo-atlas-api-NTfIGT
      auto_scaling_compute_max_instance_size: M50
      auto_scaling_compute_min_instance_size: M30
  test:
    image_version: latest
    thor_url: https://testnet.vechain.org
    api:
      cpu: 512
      memory: 1024
      max_capacity: 2
      spring_profile: nft-events,transactions,transfer-events,history-events
      ecr_common_repo: 905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/api
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
    indexer:
      cpu: 1024
      memory: 2048
      enabled: true
      spring_profile: indexer,nft-events,transactions,transfer-events,history-events
      ecr_common_repo: 905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/indexer
      slack_webhook_url: https://hooks.slack.com/services/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
      start_block:
        nfts:                       '1042259'
        nft_blacklist:              '21294907'
        transactions:               '15034'
        transfers:                  '15034'
        history:                    '15034'
        vevote:                     '21432703'
      sync_logger_interval:
        nfts:                       '1000'
        transactions:               '1000'
        transfers:                  '1000'
        history:                    '1000'
        vevote:                     '1000'
      sync_block_batch_size:
        nfts:                       '100'
        transfers:                  '100'
        vevote:                     '100'
      pruner:
        enabled: true
        interval:                   '43200000'
        initial_delay:              '300000'
        removal_chunk_size:         '2000'
      blacklist:
        contract_address:           '0x07310cECa66aD36A0dc02A142dF28B81a653107E'
        interval:                   '180000'
        initial_delay:              '60000'
      version:
        nfts:                       '2'
        transfers:                  '1'
        transactions:               '1'
        history:                    '2'
        nft_blacklist:              '1'
        vevote_comments:            '1'
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
        - name: "REORG"
          pattern: "REORG Detected"
          threshold: 1
    comments:
      minLength: 10
      language:
        confidence:                 '0.9'
    veworld:
      contract:
        vevote:
          address:                  '0x428BE069E21a584fBbAb934Fb4ad55AF346A3513'
    mongodb:
      type: atlas
      fqdn: testnet.rsmhw.mongodb.net
      proto: mongodb+srv
      opts: retryWrites=true&w=majority
      cluster_tier: M20
      disk_size_gb: 119
      iops: 1000
      secret_arn: arn:aws:secretsmanager:eu-west-1:905964754131:secret:prod/mongo-atlas-api-NTfIGT
      auto_scaling_compute_max_instance_size: M30
      auto_scaling_compute_min_instance_size: M10
