region:                          eu-west-1
project:                         veworld
environment:                     prod-blue
certificate_arn:                 arn:aws:acm:eu-west-1:905964754131:certificate/695573a6-698a-4309-a427-28dd94fe7633
azs:
  -                              eu-west-1a
  -                              eu-west-1b
  -                              eu-west-1c
cidr:                            172.31.0.0/16
public_subnets:
  -                              172.31.96.0/20
  -                              172.31.112.0/20
  -                              172.31.0.0/20
private_subnets:
  -                              172.31.64.0/20
  -                              172.31.32.0/20
  -                              172.31.80.0/20
database_subnets:                null



rate_limit:                      '5000'
rate_limit_exception_list:
  -                              185.57.113.46/32
  -                              81.39.47.171/32
  -                              90.26.60.41/32
cloudwatch_alarms:               true
mongoatlas_project_id:           64d6337acba67e1132a3a4e1
slack_secret_arn:                arn:aws:secretsmanager:eu-west-1:905964754131:secret:veworld-mongodb-alerts/slack/api-token-NvxUZd
datadog:
  secret_arn:                       arn:aws:secretsmanager:eu-west-1:905964754131:secret:prod/datadog_keys-NFBO6v
enabled_nets:
  main:
    image_version:                  latest
    thor_url:                       https://mainnet.vechain.org
    api:
      cpu:                          512
      memory:                       1024
      max_capacity:                 4
      spring_profile:               nft-events,transactions,transfer-events,history-events,stargate
      ecr_common_repo:              905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/api
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
    indexer:
      cpu: 4096
      memory: 8192
      enabled: true
      spring_profile: indexer,nft-events,transactions,transfer-events,history-events,stargate
      ecr_common_repo: 905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/indexer
      slack_webhook_url: https://hooks.slack.com/services/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
      start_block:
        nfts:                       '1304112'
        nft_blacklist:              '21774168'
        transactions:               '751'
        transfers:                  '37840'
        history:                    '751'
        vevote:                     '21432703'
        stargate:                   '22044000'
      sync_logger_interval:
        nfts:                       '1000'
        transactions:               '1000'
        transfers:                  '1000'
        history:                    '1000'
        vevote:                     '1000'
        stargate:                   '1000'
      sync_block_batch_size:
        nfts:                       '500'
        transfers:                  '500'
        vevote:                     '500'
        stargate:                   '500'
      pruner:
        enabled:                    true
        interval:                   '43200000'
        initial_delay:              '300000'
        removal_chunk_size:         '2000'
      blacklist:
        contract_address:           '0x0f9b01618cd5e0030f8e26ff61bc1349cb9eb8d5'
        interval:                   '180000'
        initial_delay:              '60000'
      version:
        nfts:                       '3'
        transfers:                  '2'
        transactions:               '2'
        history:                    '6'
        nft_blacklist:              '3'
        vevote_comments:            '1'
        vevote_results:             '1'
        stargate_vtho_claimed_by_block: '4'
        stargate_vtho_claimed_by_account: '4'
        stargate_nft_holders_by_account: '4'
        stargate_vet_staked_by_account: '4'
      business-event:
        substitutions:
          B3TR_CONTRACT: '0x5ef79995fe8a89e0812330e4378eb2660cede699'
          VOT3_CONTRACT: '0x76ca782b59c74d088c7d2cce2f211bc00836c602'
          B3TR_GOVERNOR_CONTRACT: '0x1c65c25fabe2fc1bcb82f253fa0c916a322f777c'
          GM_NFT_CONTRACT: '0x93b8cd34a7fc4f53271b9011161f7a2b5fea9d1f'
          X_ALLOC_VOTING_CONTRACT: '0x89a00bb0947a30ff95beef77a66aede3842fe5b7'
          X2EARN_REWARDS_POOL_CONTRACT: '0x6bee7ddab6c99d5b2af0554eaea484ce18f52631'
          VOTER_REWARDS_CONTRACT: '0x838a33af756a6366f93e201423e1425f67ec0fa7'
          TREASURY_CONTRACT: '0xd5903bcc66e439c753e525f8af2fec7be2429593'
          STARGATE_DELEGATION_CONTRACT: '0x4cb1c9ef05b529c093371264fab2c93cc6cddb0e'
          STARGATE_NFT_CONTRACT: '0x1856c533ac2d94340aaa8544d35a5c1d4a21dee7'
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
        - name: "REORG"
          pattern: "REORG Detected"
          threshold: 1
    comments:
      minLength: 10
      language:
        confidence:                 '0.9'
    veworld:
      contract:
        vevote:
          address:                  '0x90a3c072cf8493ccdd9b86b1c9b5d18f86fdf3e0'
    mongodb:
      type:                         atlas
      fqdn:                         mainnet.rsmhw.mongodb.net
      proto:                        mongodb+srv
      opts:                         retryWrites=true&w=majority
      cluster_tier:                 M40
      disk_size_gb:                 350
      iops:                         2000
      secret_arn:                   arn:aws:secretsmanager:eu-west-1:905964754131:secret:prod/mongo-atlas-api-NTfIGT
      auto_scaling_compute_max_instance_size: M50
      auto_scaling_compute_min_instance_size: M30
  test:
    image_version:                  latest
    thor_url:                       https://testnet.vechain.org
    api:
      cpu:                          512
      memory:                       1024
      max_capacity:                 2
      spring_profile:               nft-events,transactions,transfer-events,history-events,vevote-comments,vevote-results,stargate
      ecr_common_repo:              905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/api
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
    indexer:
      cpu: 2048
      memory: 4096
      enabled: true
      spring_profile: indexer,nft-events,transactions,transfer-events,history-events,vevote-comments,vevote-results,stargate
      ecr_common_repo: 905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/indexer
      slack_webhook_url: https://hooks.slack.com/services/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
      start_block:
        nfts:                       '1042259'
        nft_blacklist:              '21823565'
        transactions:               '15034'
        transfers:                  '15034'
        history:                    '15034'
        vevote:                     '21432703'
        stargate:                   '22087000'
      sync_logger_interval:
        nfts:                       '1000'
        transactions:               '1000'
        transfers:                  '1000'
        history:                    '1000'
        vevote:                     '1000'
        stargate:                   '1000'
      sync_block_batch_size:
        nfts:                       '100'
        transfers:                  '100'
        vevote:                     '100'
        stargate:                   '100'
      pruner:
        enabled:                    true
        interval:                   '43200000'
        initial_delay:              '300000'
        removal_chunk_size:         '2000'
      blacklist:
        contract_address:           '0x9405c18c384dd448f82c11136e188a147186ea3a'
        interval:                   '180000'
        initial_delay:              '60000'
      version:
        nfts:                       '3'
        transfers:                  '2'
        transactions:               '2'
        history:                    '6'
        nft_blacklist:              '3'
        vevote_comments:            '1'
        vevote_results:             '1'
        stargate_vtho_claimed_by_block: '4'
        stargate_vtho_claimed_by_account: '4'
        stargate_nft_holders_by_account: '4'
        stargate_vet_staked_by_account: '4'
      business-event:
        substitutions:
          B3TR_CONTRACT: '0xbf64cf86894ee0877c4e7d03936e35ee8d8b864f'
          VOT3_CONTRACT: '0xa704c45971995467696ee9544da77dd42bc9706e'
          B3TR_GOVERNOR_CONTRACT: '0xdf5e114d391cac840529802fe8d01f6bdebe41ec'
          GM_NFT_CONTRACT: '0xcf73039913e05aa1838d5869e72290d2b454c1e8'
          X_ALLOC_VOTING_CONTRACT: '0x5859ff910d8b0c127364c98e24233b0af7443c1c'
          X2EARN_REWARDS_POOL_CONTRACT: '0x5f8f86b8d0fa93cdae20936d150175df0205fb38'
          VOTER_REWARDS_CONTRACT: '0x2e47fc4aabb3403037fb5e1f38995e7a91ce8ed2'
          TREASURY_CONTRACT: '0x039893ebe092a2d22b08e2b029735d211bff7f50'
          STARGATE_DELEGATION_CONTRACT: '0x7240e3bc0d26431512d5b67dbd26d199205bffe8'
          STARGATE_NFT_CONTRACT: '0x1ec1d168574603ec35b9d229843b7c2b44bcb770'
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
        - name: "REORG"
          pattern: "REORG Detected"
          threshold: 1
    comments:
      minLength: 10
      language:
        confidence:                 '0.9'
    veworld:
      contract:
        vevote:
          address:                  '0x90a3c072cf8493ccdd9b86b1c9b5d18f86fdf3e0'
    mongodb:
      type:                         atlas
      fqdn:                         testnet.rsmhw.mongodb.net
      proto:                        mongodb+srv
      opts:                         retryWrites=true&w=majority
      cluster_tier:                 M20
      disk_size_gb:                 119
      iops:                         1000
      secret_arn:                   arn:aws:secretsmanager:eu-west-1:905964754131:secret:prod/mongo-atlas-api-NTfIGT
      auto_scaling_compute_max_instance_size: M30
      auto_scaling_compute_min_instance_size: M10
