region:                          eu-west-1
project:                         veworld
environment:                     prod-blue
certificate_arn:                 arn:aws:acm:eu-west-1:905964754131:certificate/57fc89c7-5577-4cc6-9c07-22fff2265028
azs:
  -                              eu-west-1a
  -                              eu-west-1b
  -                              eu-west-1c
cidr:                            172.31.0.0/16
public_subnets:
  -                              172.31.96.0/20
  -                              172.31.112.0/20
  -                              172.31.0.0/20
private_subnets:
  -                              172.31.64.0/20
  -                              172.31.32.0/20
  -                              172.31.80.0/20
database_subnets:                null



rate_limit:                      '5000'
rate_limit_exception_list:
  -                              185.57.113.46/32
  -                              81.39.47.171/32
  -                              90.26.60.41/32
cloudwatch_alarms:               true

# ALB Configuration
alb:
  # Listener Rules Configuration
  is_rule_4_required: false
  https_listener:
    default_action: "fixed-response"
  listener_rules:
    - name: "api-rules"
      path_patterns: [ "/api/v*", "/api-docs", "/api-docs/*" ]
      priority: 0
    - name: "swagger-ui"
      path_patterns: ["/swagger-ui/*"]
      priority: 1
      enabled: true
      use_default_tg_group: true

  # Target Groups Configuration


  # Authentication Configuration
  authentication:
    okta_auth_server_base_url: "https://vechaineu.okta.com"
    secret_id: "arn:aws:secretsmanager:eu-west-1:905964754131:secret:prod/veworld/okta-AHB6D3"

  # Health Check Configuration
  healthcheck:
    path: "/actuator/health"
  waf:
    waf_rate_limit: 5000
    waf_rate_limit_exception_list:
      - "37.187.71.209/32"
      - "49.12.121.61/32"
      - "83.34.211.88/32"
      - "162.19.91.134/32"
      - "136.243.78.172/32"
      - "141.94.193.149/32"
      - "185.57.113.46/32"
      - "81.39.47.171/32"
      - "90.26.60.41/32"

mongoatlas_project_id:           64d6337acba67e1132a3a4e1
slack_secret_arn:                arn:aws:secretsmanager:eu-west-1:905964754131:secret:veworld-mongodb-alerts/slack/api-token-NvxUZd
datadog:
  secret_arn:                       arn:aws:secretsmanager:eu-west-1:905964754131:secret:prod/datadog_keys-NFBO6v
  indexer:
    api_key_arn:                 arn:aws:secretsmanager:eu-west-1:905964754131:secret:/prod/indexer/datadog-api-key-YHxcKv
    app_key_arn:                 arn:aws:secretsmanager:eu-west-1:905964754131:secret:/prod/indexer/datadog-application-key-jZB5jk
enabled_nets:
  main:
    image_version:                  latest
    thor_url:                       https://mainnet.vechain.org
    api:
      cpu:                          1024
      memory:                       2048
      max_capacity:                 8
      spring_profile:             nfts,transactions,transfers,history,vevote-results,vevote-historic-proposals,stargate,authority-nodes,b3tr,explorer,validator,accounts,contracts
      ecr_common_repo:              905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/api
      logging:
        app-log-level: 'INFO'
      timing:
        warn-threshold-ms: '1000'
        very-slow-threshold-ms: '10000'
      cache:
        max-size: '1000'
        ttl-seconds: '300'
        user-all-time-count-by-entity-type:
          max-size: '1000'
          ttl-seconds: '1200'
        user-all-time-count-by-reward:
          max-size: '1000'
          ttl-seconds: '300'
        user-all-time-count-by-actions:
          max-size: '1000'
          ttl-seconds: '300'
        app-all-time-count-by-app-id:
          max-size: '1000'
          ttl-seconds: '300'
        app-daily-count:
          max-size: '1000'
          ttl-seconds: '300'
        app-round-count:
          max-size: '1000'
          ttl-seconds: '300'
        user-daily-count:
          max-size: '1000'
          ttl-seconds: '300'
        user-daily-count-by-actions:
          max-size: '1000'
          ttl-seconds: '300'
        user-daily-count-by-entity-type:
          max-size: '1000'
          ttl-seconds: '300'
        user-round-count-by-reward:
          max-size: '1000'
          ttl-seconds: '300'
        user-round-count-by-actions:
          max-size: '1000'
          ttl-seconds: '300'
        user-round-count-by-entity-type:
          max-size: '1000'
          ttl-seconds: '300'
        official-token-addresses:
          max-size: '10'
          ttl-seconds: '3600'
        gm-nft-count:
          max-size: '1000'
          ttl-seconds: '300'
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
    indexer:
      cpu: 8192
      memory: 16384
      enabled: true
      spring_profile: indexer,nfts,transactions,transfers,history,vevote-results,stargate,authority-nodes,b3tr,explorer,validator,token-reward,accounts,vevote-historic-proposals,contracts
      ecr_common_repo: 905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/indexer
      logging:
        app-log-level: 'INFO'
        timing-log-level: 'INFO'
        pruner-log-level: 'INFO'
      timing:
        warn-threshold-ms: '1000'
        very-slow-threshold-ms: '10000'
      slack_webhook_url: https://hooks.slack.com/services/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
      start-block:
        nfts:                       '1304112'
        nft-blacklist:              '21774168'
        transactions:               '751'
        transfers:                  '37840'
        history:                    '751'
        vevote:                     '22331866'
        stargate:                   '22044000'
        historic-proposals:       '4510483'
        b3tr:                       '18868500'
        b3tr-x-alloc-result:        '18926115'
        b3tr-sustainable-actions:   '19122233'
        b3tr-proposal:              '19036184'
        validator:                  '23414400'
        delegation:                 '23415258'
      start-round:
        b3tr-sustainable-actions:   '4'
      sync-log-interval: '20'
      sync-block-batch-size:
        contracts:                 '250'
        vet-balance:               '250'
        nfts:                       '250'
        transfers:                  '250'
        vevote:                     '250'
        stargate:                   '250'
        authority-nodes:            '250'
        b3tr:                       '250'
        historic-proposals:       '250'
      channel-batch-size:           '100'
      pruner:
        interval: '60480'
        removal-chunk-size: '5000'
        record-limit: '1000000'
      blacklist:
        contract-address:           '0x0f9b01618cd5e0030f8e26ff61bc1349cb9eb8d5'
      healthcheck:
        inactive-threshold-syncing: '120'
        inactive-threshold-not-syncing: '600'
      version:
        contracts: '1'
        vet-balance: '1'
        nfts: '2'
        transfers: '1'
        fungible-token-interactions: '1'
        transactions: '1'
        history: '1'
        nft-blacklist: '1'
        vevote-comments: '1'
        vevote-results: '1'
        authority-node-endorser: '1'
        stargate-vtho-claimed-by-block: '4'
        stargate-vtho-generated-by-block: '7'
        stargate-vtho-claimed-by-account: '3'
        stargate-nft-holders-by-block: '5'
        stargate-vet-staked-by-block: '5'
        stargate-vet-delegated-by-block: '5'
        b3tr-proposal-comments: '1'
        b3tr-proposal-results: '3'
        b3tr-app-all-time-action-summary: '2'
        b3tr-app-round-action-summary: '2'
        b3tr-app-daily-action-summary: '2'
        b3tr-user-all-time-action-summary: '2'
        b3tr-user-round-action-summary: '2'
        b3tr-user-daily-action-summary: '2'
        b3tr-x-alloc-result: '1'
        b3tr-gm-nft: '1'
        b3tr-gm-nft-level-overview: '1'
        block-usage: '1'
        historic-proposals: '2'
        validator: '1'
        validator-rewards: '3'
        stargate-token: '3'
        token-rewards: '2'
        delegation: '2'
        total-accounts: '1'
        account-overview: '1'
      business-event:
        substitutions:
          B3TR_CONTRACT: '0x5ef79995fe8a89e0812330e4378eb2660cede699'
          EMISSIONS_CONTRACT: '0xdf94739bd169c84fe6478d8420bb807f1f47b135'
          VOT3_CONTRACT: '0x76ca782b59c74d088c7d2cce2f211bc00836c602'
          B3TR_GOVERNOR_CONTRACT: '0x1c65c25fabe2fc1bcb82f253fa0c916a322f777c'
          B3TR_DBA_POOL_CONTRACT: '0x98c1d097c39969bb5de754266f60d22bd105b368'
          GM_NFT_CONTRACT: '0x93b8cd34a7fc4f53271b9011161f7a2b5fea9d1f'
          X_ALLOC_VOTING_CONTRACT: '0x89a00bb0947a30ff95beef77a66aede3842fe5b7'
          X_ALLOC_POOL_CONTRACT: '0x4191776F05f4bE4848d3f4d587345078B439C7d3'
          X2EARN_REWARDS_POOL_CONTRACT: '0x6bee7ddab6c99d5b2af0554eaea484ce18f52631'
          VOTER_REWARDS_CONTRACT: '0x838a33af756a6366f93e201423e1425f67ec0fa7'
          TREASURY_CONTRACT: '0xd5903bcc66e439c753e525f8af2fec7be2429593'
          NODE_MANAGEMENT_CONTRACT: '0xB0EF9D89C6b49CbA6BBF86Bf2FDf0Eee4968c6AB'
          STARGATE_DELEGATION_CONTRACT: '0x4cb1c9ef05b529c093371264fab2c93cc6cddb0e'
          STARGATE_NFT_CONTRACT: '0x1856c533ac2d94340aaa8544d35a5c1d4a21dee7'
          VEVOTE_CONTRACT: '0x7d812e8e544bb0c7898ea656b70173e7ef426b4c'
          STARGATE_CONTRACT: '0x03c557be98123fdb6fad325328ac6eb77de7248c'
          BUILTIN_STAKER_CONTRACT: '0x00000000000000000000000000005374616B6572'
          GET_ALL_VALIDATORS_CONTRACT: '0xcf9daaa9e3c0385b4c55846501ac3545f58d68ad'
          RELAYER_REWARDS_POOL_CONTRACT: '0x34b56f892c9e977b9ba2e43ba64c27d368ab3c86'
          BLACKLIST_CONTRACT_ADDRESS: '0x0f9b01618cd5e0030f8e26ff61bc1349cb9eb8d5'
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
        - name: "REORG"
          pattern: "REORG Detected"
          threshold: 1
    comments:
      min-length: 10
      language:
        confidence:                 '0.9'
    veworld:
      contract:
        vevote:
          address:                  '0x7d812e8e544bb0c7898ea656b70173e7ef426b4c'
        authority-node:
          address:                  '0x0000000000000000000000417574686f72697479'
        historic-proposals:
          steering-committee:       '0x7E54f0790153647Ec0651c35cEd28171Adb5D44A'
          all-stakeholders:         '0xA6416A72F816d3a69f33D0814700545C8E3fe4BE'
    mongodb:
      type: atlas
      fqdn: mainnet.rsmhw.mongodb.net
      proto: mongodb+srv
      opts: retryWrites=true&w=majority
      cluster_tier: M50
      disk_size_gb: 1000
      iops: 2000
      secret_arn: arn:aws:secretsmanager:eu-west-1:905964754131:secret:prod/mongo-atlas-api-NTfIGT
      auto_scaling_compute_max_instance_size: M60
      auto_scaling_compute_min_instance_size: M40
  test:
    image_version: latest
    thor_url: https://testnet.vechain.org
    api:
      cpu: 512
      memory: 1024
      max_capacity: 2
      spring_profile: nfts,transactions,transfers,history,vevote-results,vevote-historic-proposals,stargate,authority-nodes,b3tr,explorer,validator,accounts
      ecr_common_repo: 905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/api
      logging:
        app-log-level: 'INFO'
      timing:
        warn-threshold-ms: '1000'
        very-slow-threshold-ms: '10000'
      cache:
        max-size: '1000'
        ttl-seconds: '300'
        user-all-time-count-by-entity-type:
          max-size: '1000'
          ttl-seconds: '1200'
        user-all-time-count-by-reward:
          max-size: '1000'
          ttl-seconds: '300'
        user-all-time-count-by-actions:
          max-size: '1000'
          ttl-seconds: '300'
        app-all-time-count-by-app-id:
          max-size: '1000'
          ttl-seconds: '300'
        app-daily-count:
          max-size: '1000'
          ttl-seconds: '300'
        app-round-count:
          max-size: '1000'
          ttl-seconds: '300'
        user-daily-count:
          max-size: '1000'
          ttl-seconds: '300'
        user-daily-count-by-actions:
          max-size: '1000'
          ttl-seconds: '300'
        user-daily-count-by-entity-type:
          max-size: '1000'
          ttl-seconds: '300'
        user-round-count-by-reward:
          max-size: '1000'
          ttl-seconds: '300'
        user-round-count-by-actions:
          max-size: '1000'
          ttl-seconds: '300'
        user-round-count-by-entity-type:
          max-size: '1000'
          ttl-seconds: '300'
        official-token-addresses:
          max-size: '10'
          ttl-seconds: '3600'
        gm-nft-count:
          max-size: '1000'
          ttl-seconds: '300'
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
    indexer:
      cpu: 4096
      memory: 8192
      enabled: true
      spring_profile: indexer,nfts,transactions,transfers,history,vevote-results,stargate,authority-nodes,b3tr,explorer,validator,token-reward,accounts,contracts
      ecr_common_repo: 905964754131.dkr.ecr.eu-west-1.amazonaws.com/veworld/indexer
      logging:
        app-log-level: 'INFO'
        timing-log-level: 'INFO'
        pruner-log-level: 'INFO'
      timing:
        warn-threshold-ms: '1000'
        very-slow-threshold-ms: '10000'
      slack_webhook_url: https://hooks.slack.com/services/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
      start-block:
        nfts:                       '1042259'
        nft-blacklist:              '21823565'
        transactions:               '15034'
        transfers:                  '15034'
        history:                    '15034'
        vevote:                     '22331866'
        stargate:                   '23188260'
        b3tr:                       '22126050'
        b3tr-x-alloc-result:        '22126050'
        b3tr-sustainable-actions:   '22126050'
        b3tr-proposal:              '22126050'
        historic-proposals:         '22087000'
        validator:                  '23221800'
        delegation:                 '23222706'
      start-round:
        b3tr-sustainable-actions:   '4'
      sync-log-interval: '100'
      sync-block-batch-size:
        contracts:                 '200'
        vet-balance:               '200'
        nfts:                       '200'
        transfers:                  '200'
        vevote:                     '200'
        stargate:                   '200'
        authority-nodes:            '200'
        b3tr:                       '200'
        historic-proposals:         '200'
      channel-batch-size:           '100'
      pruner:
        interval: '60480'
        removal-chunk-size: '5000'
        record-limit: '1000000'
      blacklist:
        contract-address:           '0x9405c18c384dd448f82c11136e188a147186ea3a'
      healthcheck:
        inactive-threshold-syncing: '120'
        inactive-threshold-not-syncing: '600'
      version:
        contracts: '1'
        vet-balance: '1'
        nfts: '2'
        transfers: '1'
        fungible-token-interactions: '1'
        transactions: '1'
        history: '1'
        nft-blacklist: '1'
        vevote-comments: '1'
        vevote-results: '1'
        authority-node-endorser: '1'
        stargate-vtho-claimed-by-block: '6'
        stargate-vtho-generated-by-block: '7'
        stargate-vtho-claimed-by-account: '5'
        stargate-nft-holders-by-block: '5'
        stargate-vet-staked-by-block: '5'
        stargate-vet-delegated-by-block: '5'
        b3tr-proposal-comments: '1'
        b3tr-proposal-results: '3'
        b3tr-app-all-time-action-summary: '2'
        b3tr-app-round-action-summary: '2'
        b3tr-app-daily-action-summary: '2'
        b3tr-user-all-time-action-summary: '2'
        b3tr-user-round-action-summary: '2'
        b3tr-user-daily-action-summary: '2'
        b3tr-x-alloc-result: '1'
        b3tr-gm-nft: '1'
        b3tr-gm-nft-level-overview: '1'
        block-usage: '1'
        historic-proposals: '1'
        validator: '1'
        validator-rewards: '3'
        stargate-token: '4'
        token-rewards: '1'
        delegation: '1'
        total-accounts: '1'
        account-overview: '1'
      business-event:
        substitutions:
          B3TR_CONTRACT: '0x95761346d18244bb91664181bf91193376197088'
          EMISSIONS_CONTRACT: '0x66898f98409db20ed6a1bf0021334b7897eb0688'
          VOT3_CONTRACT: '0x6e8b4a88d37897fc11f6ba12c805695f1c41f40e'
          B3TR_GOVERNOR_CONTRACT: '0xc30b4d0837f7e3706749655d8bde0c0f265dd81b'
          B3TR_DBA_POOL_CONTRACT: '0x328710f4925c3e4c04961882b96c50cc7cd9d958'
          GM_NFT_CONTRACT: '0x38a59fa7fd7039884465a0ff285b8c4b6fe394ca'
          X_ALLOC_VOTING_CONTRACT: '0x8800592c463f0b21ae08732559ee8e146db1d7b2'
          X_ALLOC_POOL_CONTRACT: '0x6f7b4bc19b4dc99005b473b9c45ce2815bbe7533'
          X2EARN_REWARDS_POOL_CONTRACT: '0x2d2a2207c68a46fc79325d7718e639d1047b0d8b'
          VOTER_REWARDS_CONTRACT: '0x851ef91801899a4e7e4a3174a9300b3e20c957e8'
          TREASURY_CONTRACT: '0x3d531a80c05099c71b02585031f86a2988e0caca'
          STARGATE_DELEGATION_CONTRACT: '0x32cb945dc25f4fc4214df63e3825045d6088b096'
          STARGATE_NFT_CONTRACT: '0x887d9102f0003f1724d8fd5d4fe95a11572fcd77'
          VEVOTE_CONTRACT: '0x3f5E298CaEa8843e88D5E1c4F34C7c79387B9ec6'
          NODE_MANAGEMENT_CONTRACT: '0xde17d0a516c38c168d37685bb71465f656aa256e'
          STARGATE_CONTRACT: '0x1e02b2953adefec225cf0ec49805b1146a4429c1'
          BUILTIN_STAKER_CONTRACT: '0x00000000000000000000000000005374616B6572'
          GET_ALL_VALIDATORS_CONTRACT: '0x168fc982338b399598c10f8467bc66fb1b49aae7'
          RELAYER_REWARDS_POOL_CONTRACT: '0x92b5a7484970d9b2ad981e8135ff14e6f996dc04'
          BLACKLIST_CONTRACT_ADDRESS: '0x9405c18c384dd448f82c11136e188a147186ea3a'
      log_metric_filters:
        - name: "AppUnhealthy"
          pattern: "Application is UNHEALTHY"
          threshold: 2
        - name: "REORG"
          pattern: "REORG Detected"
          threshold: 1
    comments:
      min-length: 10
      language:
        confidence:                 '0.9'
    veworld:
      contract:
        authority-node:
          address:                  '0x0000000000000000000000417574686f72697479'
        historic-proposals:
          steering-committee:       '0x7E54f0790153647Ec0651c35cEd28171Adb5D44A'
          all-stakeholders:         '0xA6416A72F816d3a69f33D0814700545C8E3fe4BE'
    mongodb:
      type: atlas
      fqdn: testnet.rsmhw.mongodb.net
      proto: mongodb+srv
      opts: retryWrites=true&w=majority
      cluster_tier: M30
      disk_size_gb: 250
      iops: 1000
      secret_arn: arn:aws:secretsmanager:eu-west-1:905964754131:secret:prod/mongo-atlas-api-NTfIGT
      auto_scaling_compute_max_instance_size: M50
      auto_scaling_compute_min_instance_size: M20
