#!/usr/bin/env python3
"""CLI tool for managing Datadog pipeline and dashboard configurations.

Subcommands:
    get                  Fetch pipeline from Datadog API, save to pipeline.json
    get-dashboard        Fetch dashboard from Datadog API, save to dashboard.json
    push-pipeline        Push pipeline.json back to Datadog
    push-dashboard       Push dashboard.json back to Datadog
    update-categories    Parse api-docs.json, regenerate category processor in pipeline.json
    validate-categories  Compare pipeline.json categories against api-docs.json

The api-docs.json file is generated by running the API with embedded MongoDB:
    ./gradlew :packages:api:generateOpenApiSpec
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

import requests
from dotenv import load_dotenv

# Paths relative to repository root
SCRIPT_DIR = Path(__file__).resolve().parent
DATADOG_DIR = SCRIPT_DIR.parent
CONFIG_PATH = DATADOG_DIR / "config.json"
PIPELINE_PATH = DATADOG_DIR / "pipeline.json"
APP_PIPELINE_PATH = DATADOG_DIR / "app-pipeline.json"
DASHBOARD_PATH = DATADOG_DIR / "dashboard.json"
OPENAPI_PATH = DATADOG_DIR / "api-docs.json"

# Read-only fields that Datadog rejects on PUT
READONLY_FIELDS = ("id", "type", "is_read_only")


def load_config():
    """Load config.json with pipeline/dashboard identifiers."""
    with open(CONFIG_PATH) as f:
        return json.load(f)


def get_dd_headers():
    """Return Datadog API headers from environment variables."""
    load_dotenv(DATADOG_DIR / ".env")
    load_dotenv()

    api_key = os.getenv("DD_API_KEY")
    app_key = os.getenv("DD_APP_KEY")

    if not api_key or not app_key:
        print("Error: DD_API_KEY and DD_APP_KEY must be set.", file=sys.stderr)
        sys.exit(1)

    return {
        "DD-API-KEY": api_key,
        "DD-APPLICATION-KEY": app_key,
        "Content-Type": "application/json",
    }


def get_dd_site():
    """Return the Datadog site from environment."""
    return os.getenv("DD_SITE", "datadoghq.eu")


# ---------------------------------------------------------------------------
# Subcommand: get
# ---------------------------------------------------------------------------


def cmd_get(args):
    """Fetch the pipeline from Datadog and save to pipeline.json."""
    config = load_config()
    headers = get_dd_headers()
    site = get_dd_site()
    pipeline_name = config["pipeline_name"]

    base_url = f"https://api.{site}/api/v1/logs/config/pipelines"
    print(f"Fetching pipelines from {base_url} ...")

    resp = requests.get(base_url, headers=headers)
    resp.raise_for_status()
    pipelines = resp.json()

    matches = [p for p in pipelines if p["name"] == pipeline_name]
    if not matches:
        print(f"Error: No pipeline found with name: {pipeline_name}", file=sys.stderr)
        sys.exit(1)

    pipeline = matches[0]
    pipeline_id = pipeline["id"]
    print(f"Found pipeline: {pipeline['name']} (id={pipeline_id})")

    with open(PIPELINE_PATH, "w") as f:
        json.dump(pipeline, f, indent=2)
        f.write("\n")

    print(f"Saved to {PIPELINE_PATH}")


# ---------------------------------------------------------------------------
# Subcommand: get-dashboard
# ---------------------------------------------------------------------------


def cmd_get_dashboard(args):
    """Fetch the dashboard from Datadog and save to dashboard.json."""
    config = load_config()
    headers = get_dd_headers()
    site = get_dd_site()
    dashboard_title = config["dashboard_title"]

    print(f"Searching for dashboard '{dashboard_title}' ...")

    # List all dashboards and find by title
    search_url = f"https://api.{site}/api/v1/dashboard"
    resp = requests.get(search_url, headers=headers)
    resp.raise_for_status()
    data = resp.json()

    dashboards = data.get("dashboards", [])
    matches = [d for d in dashboards if d.get("title") == dashboard_title]
    if not matches:
        print(
            f"Error: No dashboard found with title: {dashboard_title}", file=sys.stderr
        )
        sys.exit(1)

    dashboard_id = matches[0]["id"]
    print(f"Found dashboard: {dashboard_title} (id={dashboard_id})")

    # Fetch full dashboard definition
    detail_url = f"https://api.{site}/api/v1/dashboard/{dashboard_id}"
    resp = requests.get(detail_url, headers=headers)
    resp.raise_for_status()
    dashboard = resp.json()

    with open(DASHBOARD_PATH, "w") as f:
        json.dump(dashboard, f, indent=2)
        f.write("\n")

    print(f"Saved to {DASHBOARD_PATH}")


# ---------------------------------------------------------------------------
# Subcommand: push-pipeline
# ---------------------------------------------------------------------------


def cmd_push_pipeline(args):
    """Push pipeline.json back to Datadog."""
    if not PIPELINE_PATH.exists():
        print(f"Error: {PIPELINE_PATH} not found. Run 'get' first.", file=sys.stderr)
        sys.exit(1)

    headers = get_dd_headers()
    site = get_dd_site()

    with open(PIPELINE_PATH) as f:
        pipeline = json.load(f)

    pipeline_id = pipeline.get("id")
    if not pipeline_id:
        print(
            "Error: pipeline.json has no 'id' field. Run 'get' first.", file=sys.stderr
        )
        sys.exit(1)

    # Strip read-only fields for the PUT body
    body = {k: v for k, v in pipeline.items() if k not in READONLY_FIELDS}

    url = f"https://api.{site}/api/v1/logs/config/pipelines/{pipeline_id}"
    print(f"Pushing pipeline to {url} ...")

    resp = requests.put(url, headers=headers, json=body)
    if resp.status_code != 200:
        print(f"Error: Datadog returned {resp.status_code}", file=sys.stderr)
        print(resp.text, file=sys.stderr)
        sys.exit(1)

    print("Pipeline updated successfully.")


# ---------------------------------------------------------------------------
# Subcommand: get-app-pipeline
# ---------------------------------------------------------------------------


def cmd_get_app_pipeline(args):
    """Fetch the app pipeline from Datadog and save to app-pipeline.json."""
    config = load_config()
    headers = get_dd_headers()
    site = get_dd_site()
    pipeline_name = config["app_pipeline_name"]

    base_url = f"https://api.{site}/api/v1/logs/config/pipelines"
    print(f"Fetching pipelines from {base_url} ...")

    resp = requests.get(base_url, headers=headers)
    resp.raise_for_status()
    pipelines = resp.json()

    matches = [p for p in pipelines if p["name"] == pipeline_name]
    if not matches:
        print(f"Error: No pipeline found with name: {pipeline_name}", file=sys.stderr)
        sys.exit(1)

    pipeline = matches[0]
    pipeline_id = pipeline["id"]
    print(f"Found pipeline: {pipeline['name']} (id={pipeline_id})")

    with open(APP_PIPELINE_PATH, "w") as f:
        json.dump(pipeline, f, indent=2)
        f.write("\n")

    print(f"Saved to {APP_PIPELINE_PATH}")


# ---------------------------------------------------------------------------
# Subcommand: push-app-pipeline
# ---------------------------------------------------------------------------


def cmd_push_app_pipeline(args):
    """Push app-pipeline.json back to Datadog (creates if no id present)."""
    if not APP_PIPELINE_PATH.exists():
        print(
            f"Error: {APP_PIPELINE_PATH} not found.", file=sys.stderr
        )
        sys.exit(1)

    headers = get_dd_headers()
    site = get_dd_site()

    with open(APP_PIPELINE_PATH) as f:
        pipeline = json.load(f)

    pipeline_id = pipeline.get("id")

    if pipeline_id:
        # Update existing pipeline
        body = {k: v for k, v in pipeline.items() if k not in READONLY_FIELDS}
        url = f"https://api.{site}/api/v1/logs/config/pipelines/{pipeline_id}"
        print(f"Updating app pipeline at {url} ...")

        resp = requests.put(url, headers=headers, json=body)
        if resp.status_code != 200:
            print(f"Error: Datadog returned {resp.status_code}", file=sys.stderr)
            print(resp.text, file=sys.stderr)
            sys.exit(1)

        print("App pipeline updated successfully.")
    else:
        # Create new pipeline
        body = {k: v for k, v in pipeline.items() if k not in READONLY_FIELDS}
        url = f"https://api.{site}/api/v1/logs/config/pipelines"
        print(f"Creating app pipeline at {url} ...")

        resp = requests.post(url, headers=headers, json=body)
        if resp.status_code not in (200, 201):
            print(f"Error: Datadog returned {resp.status_code}", file=sys.stderr)
            print(resp.text, file=sys.stderr)
            sys.exit(1)

        created = resp.json()
        pipeline["id"] = created["id"]

        with open(APP_PIPELINE_PATH, "w") as f:
            json.dump(pipeline, f, indent=2)
            f.write("\n")

        print(f"App pipeline created (id={created['id']}). Saved id to {APP_PIPELINE_PATH}")


# ---------------------------------------------------------------------------
# Subcommand: push-dashboard
# ---------------------------------------------------------------------------

# Fields managed by Datadog that should not be sent in PUT body
DASHBOARD_READONLY_FIELDS = ("id", "author_handle", "author_name", "created_at", "modified_at")


def cmd_push_dashboard(args):
    """Push dashboard.json back to Datadog."""
    if not DASHBOARD_PATH.exists():
        print(f"Error: {DASHBOARD_PATH} not found. Run 'get-dashboard' first.", file=sys.stderr)
        sys.exit(1)

    headers = get_dd_headers()
    site = get_dd_site()

    with open(DASHBOARD_PATH) as f:
        dashboard = json.load(f)

    dashboard_id = dashboard.get("id")
    if not dashboard_id:
        print(
            "Error: dashboard.json has no 'id' field. Run 'get-dashboard' first.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Strip read-only fields for the PUT body
    body = {k: v for k, v in dashboard.items() if k not in DASHBOARD_READONLY_FIELDS}

    url = f"https://api.{site}/api/v1/dashboard/{dashboard_id}"
    print(f"Pushing dashboard to {url} ...")

    resp = requests.put(url, headers=headers, json=body)
    if resp.status_code != 200:
        print(f"Error: Datadog returned {resp.status_code}", file=sys.stderr)
        print(resp.text, file=sys.stderr)
        sys.exit(1)

    print("Dashboard updated successfully.")


# ---------------------------------------------------------------------------
# Endpoint detection from OpenAPI spec
# ---------------------------------------------------------------------------

# Attribute name used in ELB logs for the request URL
ELB_URL_ATTR = "@http.url_details.path"

# Endpoint groups to exclude (test-only)
EXCLUDED_GROUPS = {"e2e"}


def load_openapi_spec():
    """Load the api-docs.json file."""
    if not OPENAPI_PATH.exists():
        print(
            f"Error: {OPENAPI_PATH} not found. Generate it with:\n"
            "  ./gradlew :packages:api:generateOpenApiSpec",
            file=sys.stderr,
        )
        sys.exit(1)

    with open(OPENAPI_PATH) as f:
        return json.load(f)


def extract_endpoint_groups(spec):
    """Extract endpoint groups from OpenAPI spec paths.

    Groups paths by the segment after /api/v{N}/ and returns a dict mapping
    group names to sets of base path prefixes.
    e.g. {"accounts": {"/api/v1/accounts"}, "b3tr": {"/api/v1/b3tr", "/api/v2/b3tr"}}
    """
    groups = {}

    for path in spec.get("paths", {}):
        m = re.match(r"/api/v\d+/([^/]+)", path)
        if not m:
            continue

        group = m.group(1)
        if group in EXCLUDED_GROUPS:
            continue

        # Store the base path up to and including the group segment
        base = re.match(r"(/api/v\d+/[^/]+)", path).group(1)
        groups.setdefault(group, set()).add(base)

    return groups


def build_categories(groups):
    """Build Datadog category processor categories from grouped paths.

    Each category uses the ELB log URL attribute to match requests.
    """
    categories = []

    for group_name in sorted(groups.keys()):
        base_paths = sorted(groups[group_name])
        # Build filter query: match any of the base paths with wildcard
        conditions = [f"{ELB_URL_ATTR}:{path}*" for path in base_paths]
        if len(conditions) == 1:
            query = conditions[0]
        else:
            query = " OR ".join(conditions)

        categories.append({"filter": {"query": query}, "name": group_name})

    # Add catch-all "unknown" category last
    categories.append({"filter": {"query": "*"}, "name": "unknown"})

    return categories


def detect_categories():
    """Load OpenAPI spec and return the categories that should exist."""
    spec = load_openapi_spec()
    groups = extract_endpoint_groups(spec)
    return build_categories(groups)


# ---------------------------------------------------------------------------
# Subcommand: update-categories
# ---------------------------------------------------------------------------


def cmd_update_categories(args):
    """Parse api-docs.json, regenerate category processor in pipeline.json."""
    if not PIPELINE_PATH.exists():
        print(f"Error: {PIPELINE_PATH} not found. Run 'get' first.", file=sys.stderr)
        sys.exit(1)

    config = load_config()
    processor_name = config["category_processor_name"]

    with open(PIPELINE_PATH) as f:
        pipeline = json.load(f)

    categories = detect_categories()

    # Find the category processor by name
    processors = pipeline.get("processors", [])
    found = False
    for proc in processors:
        if (
            proc.get("type") == "category-processor"
            and proc.get("name") == processor_name
        ):
            proc["categories"] = categories
            found = True
            print(f"Updated existing category processor '{processor_name}'")
            break

    if not found:
        # Create a new category processor
        new_proc = {
            "type": "category-processor",
            "name": processor_name,
            "is_enabled": True,
            "categories": categories,
            "target": "endpoint_group",
        }
        processors.append(new_proc)
        pipeline["processors"] = processors
        print(f"Created new category processor '{processor_name}'")

    with open(PIPELINE_PATH, "w") as f:
        json.dump(pipeline, f, indent=2)
        f.write("\n")

    print(f"\nCategories ({len(categories)}):")
    for cat in categories:
        print(f"  {cat['name']:25s} -> {cat['filter']['query']}")

    print(f"\nSaved to {PIPELINE_PATH}")


# ---------------------------------------------------------------------------
# Subcommand: validate-categories
# ---------------------------------------------------------------------------


def cmd_validate_categories(args):
    """Compare pipeline.json categories against api-docs.json. Exit 1 if out of sync."""
    if not PIPELINE_PATH.exists():
        print(f"Error: {PIPELINE_PATH} not found. Run 'get' first.", file=sys.stderr)
        sys.exit(1)

    config = load_config()
    processor_name = config["category_processor_name"]

    with open(PIPELINE_PATH) as f:
        pipeline = json.load(f)

    # Find current categories in pipeline.json
    current_categories = None
    for proc in pipeline.get("processors", []):
        if (
            proc.get("type") == "category-processor"
            and proc.get("name") == processor_name
        ):
            current_categories = proc.get("categories", [])
            break

    if current_categories is None:
        print(
            f"Error: No category processor '{processor_name}' found in pipeline.json",
            file=sys.stderr,
        )
        sys.exit(1)

    # Detect expected categories from OpenAPI spec
    expected_categories = detect_categories()

    # Normalize for comparison
    def normalize(cats):
        return [(c["name"], c["filter"]["query"]) for c in cats]

    current_norm = normalize(current_categories)
    expected_norm = normalize(expected_categories)

    if current_norm == expected_norm:
        print("Categories are in sync.")
        sys.exit(0)

    # Show diff
    current_names = {c[0] for c in current_norm}
    expected_names = {c[0] for c in expected_norm}

    missing = expected_names - current_names
    extra = current_names - expected_names

    if missing:
        print(f"Missing categories: {', '.join(sorted(missing))}")
    if extra:
        print(f"Extra categories: {', '.join(sorted(extra))}")

    # Check query differences for shared categories
    current_map = dict(current_norm)
    expected_map = dict(expected_norm)
    for name in sorted(current_names & expected_names):
        if current_map[name] != expected_map[name]:
            print(f"Category '{name}' query differs:")
            print(f"  pipeline.json: {current_map[name]}")
            print(f"  api-docs.json: {expected_map[name]}")

    # Check ordering
    if current_norm != expected_norm and set(current_norm) == set(expected_norm):
        print("Category ordering differs (unknown must be last)")

    print("\nCategories are out of sync. Run 'update-categories' to fix.")
    sys.exit(1)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Manage Datadog pipeline and dashboard configurations.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser(
        "get", help="Fetch pipeline from Datadog, save to pipeline.json"
    )
    subparsers.add_parser(
        "get-dashboard", help="Fetch dashboard from Datadog, save to dashboard.json"
    )
    subparsers.add_parser(
        "push-pipeline", help="Push pipeline.json back to Datadog"
    )
    subparsers.add_parser(
        "get-app-pipeline",
        help="Fetch app pipeline from Datadog, save to app-pipeline.json",
    )
    subparsers.add_parser(
        "push-app-pipeline",
        help="Push app-pipeline.json to Datadog (creates if new)",
    )
    subparsers.add_parser(
        "push-dashboard", help="Push dashboard.json back to Datadog"
    )
    subparsers.add_parser(
        "update-categories",
        help="Auto-detect endpoints from api-docs.json, update category processor",
    )
    subparsers.add_parser(
        "validate-categories",
        help="Validate pipeline categories match api-docs.json endpoints",
    )

    args = parser.parse_args()

    commands = {
        "get": cmd_get,
        "get-app-pipeline": cmd_get_app_pipeline,
        "get-dashboard": cmd_get_dashboard,
        "push-pipeline": cmd_push_pipeline,
        "push-app-pipeline": cmd_push_app_pipeline,
        "push-dashboard": cmd_push_dashboard,
        "update-categories": cmd_update_categories,
        "validate-categories": cmd_validate_categories,
    }

    commands[args.command](args)


if __name__ == "__main__":
    main()
