#!/usr/bin/env python3
"""CLI tool for managing Datadog pipeline and dashboard configurations.

Subcommands:
    get                  Fetch pipeline from Datadog API, save to pipeline.json
    get-app-pipeline     Fetch app pipeline from Datadog API, save to app-pipeline.json
    get-dashboard        Fetch dashboard from Datadog API, save to dashboard.json
    push-pipeline        Push pipeline.json back to Datadog
    push-app-pipeline    Push app-pipeline.json to Datadog (creates or updates idempotently)
    push-dashboard       Push dashboard.json back to Datadog
    update-categories    Parse api-docs.json, regenerate category processor in pipeline.json
    validate-categories  Compare pipeline.json categories against api-docs.json

The api-docs.json file is generated by running the API with embedded MongoDB:
    ./gradlew :packages:api:generateOpenApiSpec
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

import requests
from dotenv import load_dotenv

# Paths relative to repository root
SCRIPT_DIR = Path(__file__).resolve().parent
DATADOG_DIR = SCRIPT_DIR.parent
CONFIG_PATH = DATADOG_DIR / "config.json"
PIPELINE_PATH = DATADOG_DIR / "pipeline.json"
APP_PIPELINE_PATH = DATADOG_DIR / "app-pipeline.json"
DASHBOARD_PATH = DATADOG_DIR / "dashboard.json"
OPENAPI_PATH = DATADOG_DIR / "api-docs.json"

# Read-only fields that Datadog rejects on PUT
READONLY_FIELDS = ("id", "type", "is_read_only")


def load_config():
    """Load config.json with pipeline/dashboard identifiers."""
    with open(CONFIG_PATH) as f:
        return json.load(f)


def get_dd_headers():
    """Return Datadog API headers from environment variables."""
    load_dotenv(DATADOG_DIR / ".env")
    load_dotenv()

    api_key = os.getenv("DD_API_KEY")
    app_key = os.getenv("DD_APP_KEY")

    if not api_key or not app_key:
        print("Error: DD_API_KEY and DD_APP_KEY must be set.", file=sys.stderr)
        sys.exit(1)

    return {
        "DD-API-KEY": api_key,
        "DD-APPLICATION-KEY": app_key,
        "Content-Type": "application/json",
    }


def get_dd_site():
    """Return the Datadog site from environment."""
    return os.getenv("DD_SITE", "datadoghq.eu")


# ---------------------------------------------------------------------------
# Subcommand: get
# ---------------------------------------------------------------------------


def cmd_get(args):
    """Fetch the pipeline from Datadog and save to pipeline.json."""
    config = load_config()
    headers = get_dd_headers()
    site = get_dd_site()
    pipeline_name = config["pipeline_name"]

    base_url = f"https://api.{site}/api/v1/logs/config/pipelines"
    print(f"Fetching pipelines from {base_url} ...")

    resp = requests.get(base_url, headers=headers)
    resp.raise_for_status()
    pipelines = resp.json()

    matches = [p for p in pipelines if p["name"] == pipeline_name]
    if not matches:
        print(f"Error: No pipeline found with name: {pipeline_name}", file=sys.stderr)
        sys.exit(1)

    pipeline = matches[0]
    pipeline_id = pipeline["id"]
    print(f"Found pipeline: {pipeline['name']} (id={pipeline_id})")

    with open(PIPELINE_PATH, "w") as f:
        json.dump(pipeline, f, indent=2)
        f.write("\n")

    print(f"Saved to {PIPELINE_PATH}")


# ---------------------------------------------------------------------------
# Subcommand: get-dashboard
# ---------------------------------------------------------------------------


def cmd_get_dashboard(args):
    """Fetch the dashboard from Datadog and save to dashboard.json."""
    config = load_config()
    headers = get_dd_headers()
    site = get_dd_site()
    dashboard_title = config["dashboard_title"]

    print(f"Searching for dashboard '{dashboard_title}' ...")

    # List all dashboards and find by title
    search_url = f"https://api.{site}/api/v1/dashboard"
    resp = requests.get(search_url, headers=headers)
    resp.raise_for_status()
    data = resp.json()

    dashboards = data.get("dashboards", [])
    matches = [d for d in dashboards if d.get("title") == dashboard_title]
    if not matches:
        print(
            f"Error: No dashboard found with title: {dashboard_title}", file=sys.stderr
        )
        sys.exit(1)

    dashboard_id = matches[0]["id"]
    print(f"Found dashboard: {dashboard_title} (id={dashboard_id})")

    # Fetch full dashboard definition
    detail_url = f"https://api.{site}/api/v1/dashboard/{dashboard_id}"
    resp = requests.get(detail_url, headers=headers)
    resp.raise_for_status()
    dashboard = resp.json()

    with open(DASHBOARD_PATH, "w") as f:
        json.dump(dashboard, f, indent=2)
        f.write("\n")

    print(f"Saved to {DASHBOARD_PATH}")


# ---------------------------------------------------------------------------
# Subcommand: push-pipeline
# ---------------------------------------------------------------------------


def cmd_push_pipeline(args):
    """Push pipeline.json back to Datadog."""
    if not PIPELINE_PATH.exists():
        print(f"Error: {PIPELINE_PATH} not found. Run 'get' first.", file=sys.stderr)
        sys.exit(1)

    headers = get_dd_headers()
    site = get_dd_site()

    with open(PIPELINE_PATH) as f:
        pipeline = json.load(f)

    pipeline_id = pipeline.get("id")
    if not pipeline_id:
        print(
            "Error: pipeline.json has no 'id' field. Run 'get' first.", file=sys.stderr
        )
        sys.exit(1)

    # Strip read-only fields for the PUT body
    body = {k: v for k, v in pipeline.items() if k not in READONLY_FIELDS}

    url = f"https://api.{site}/api/v1/logs/config/pipelines/{pipeline_id}"
    print(f"Pushing pipeline to {url} ...")

    resp = requests.put(url, headers=headers, json=body)
    if resp.status_code != 200:
        print(f"Error: Datadog returned {resp.status_code}", file=sys.stderr)
        print(resp.text, file=sys.stderr)
        sys.exit(1)

    print("Pipeline updated successfully.")


# ---------------------------------------------------------------------------
# Subcommand: get-app-pipeline
# ---------------------------------------------------------------------------


def cmd_get_app_pipeline(args):
    """Fetch the app pipeline from Datadog and save to app-pipeline.json."""
    config = load_config()
    headers = get_dd_headers()
    site = get_dd_site()
    pipeline_name = config["app_pipeline_name"]

    base_url = f"https://api.{site}/api/v1/logs/config/pipelines"
    print(f"Fetching pipelines from {base_url} ...")

    resp = requests.get(base_url, headers=headers)
    resp.raise_for_status()
    pipelines = resp.json()

    matches = [p for p in pipelines if p["name"] == pipeline_name]
    if not matches:
        print(f"Error: No pipeline found with name: {pipeline_name}", file=sys.stderr)
        sys.exit(1)

    pipeline = matches[0]
    pipeline_id = pipeline["id"]
    print(f"Found pipeline: {pipeline['name']} (id={pipeline_id})")

    with open(APP_PIPELINE_PATH, "w") as f:
        json.dump(pipeline, f, indent=2)
        f.write("\n")

    print(f"Saved to {APP_PIPELINE_PATH}")


# ---------------------------------------------------------------------------
# Subcommand: push-app-pipeline
# ---------------------------------------------------------------------------


def _find_pipeline_by_name(headers, site, name):
    """Look up a pipeline by name. Returns the id if found, None otherwise."""
    url = f"https://api.{site}/api/v1/logs/config/pipelines"
    resp = requests.get(url, headers=headers)
    resp.raise_for_status()
    matches = [p for p in resp.json() if p["name"] == name]
    return matches[0]["id"] if matches else None


def cmd_push_app_pipeline(args):
    """Push app-pipeline.json to Datadog (creates or updates idempotently)."""
    if not APP_PIPELINE_PATH.exists():
        print(
            f"Error: {APP_PIPELINE_PATH} not found. Run 'get-app-pipeline' first.",
            file=sys.stderr,
        )
        sys.exit(1)

    config = load_config()
    headers = get_dd_headers()
    site = get_dd_site()

    with open(APP_PIPELINE_PATH) as f:
        pipeline = json.load(f)

    pipeline_id = pipeline.get("id")

    # If no id in the file, check if the pipeline already exists by name
    if not pipeline_id:
        pipeline_name = config["app_pipeline_name"]
        print(f"No id in app-pipeline.json, looking up '{pipeline_name}' ...")
        pipeline_id = _find_pipeline_by_name(headers, site, pipeline_name)
        if pipeline_id:
            print(f"Found existing pipeline (id={pipeline_id})")

    body = {k: v for k, v in pipeline.items() if k not in READONLY_FIELDS}

    if pipeline_id:
        # Update existing pipeline
        url = f"https://api.{site}/api/v1/logs/config/pipelines/{pipeline_id}"
        print(f"Updating app pipeline at {url} ...")

        resp = requests.put(url, headers=headers, json=body)
        if resp.status_code != 200:
            print(f"Error: Datadog returned {resp.status_code}", file=sys.stderr)
            print(resp.text, file=sys.stderr)
            sys.exit(1)

        print("App pipeline updated successfully.")
    else:
        # Create new pipeline
        url = f"https://api.{site}/api/v1/logs/config/pipelines"
        print(f"Creating app pipeline at {url} ...")

        resp = requests.post(url, headers=headers, json=body)
        if resp.status_code not in (200, 201):
            print(f"Error: Datadog returned {resp.status_code}", file=sys.stderr)
            print(resp.text, file=sys.stderr)
            sys.exit(1)

        created = resp.json()
        print(f"App pipeline created (id={created['id']})")


# ---------------------------------------------------------------------------
# Subcommand: push-dashboard
# ---------------------------------------------------------------------------

# Fields managed by Datadog that should not be sent in PUT body
DASHBOARD_READONLY_FIELDS = ("id", "author_handle", "author_name", "created_at", "modified_at")


def cmd_push_dashboard(args):
    """Push dashboard.json back to Datadog."""
    if not DASHBOARD_PATH.exists():
        print(f"Error: {DASHBOARD_PATH} not found. Run 'get-dashboard' first.", file=sys.stderr)
        sys.exit(1)

    headers = get_dd_headers()
    site = get_dd_site()

    with open(DASHBOARD_PATH) as f:
        dashboard = json.load(f)

    dashboard_id = dashboard.get("id")
    if not dashboard_id:
        print(
            "Error: dashboard.json has no 'id' field. Run 'get-dashboard' first.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Strip read-only fields for the PUT body
    body = {k: v for k, v in dashboard.items() if k not in DASHBOARD_READONLY_FIELDS}

    url = f"https://api.{site}/api/v1/dashboard/{dashboard_id}"
    print(f"Pushing dashboard to {url} ...")

    resp = requests.put(url, headers=headers, json=body)
    if resp.status_code != 200:
        print(f"Error: Datadog returned {resp.status_code}", file=sys.stderr)
        print(resp.text, file=sys.stderr)
        sys.exit(1)

    print("Dashboard updated successfully.")


# ---------------------------------------------------------------------------
# Endpoint detection from OpenAPI spec
# ---------------------------------------------------------------------------

# Attribute name used in ELB logs for the request URL
ELB_URL_ATTR = "@http.url_details.path"
API_CATEGORY_TARGET = "http.url_details.api_category"
ENDPOINT_GROUP_TARGET = "endpoint_group"
API_CATEGORY_PROCESSOR_NAME_FALLBACK = "Categorising the api calls"

# Endpoint groups to exclude (test-only)
EXCLUDED_GROUPS = {"e2e"}
EXTRA_ENDPOINT_PATHS = ("/api-docs",)


def load_openapi_spec():
    """Load the api-docs.json file."""
    if not OPENAPI_PATH.exists():
        print(
            f"Error: {OPENAPI_PATH} not found. Generate it with:\n"
            "  ./gradlew :packages:api:generateOpenApiSpec",
            file=sys.stderr,
        )
        sys.exit(1)

    with open(OPENAPI_PATH) as f:
        return json.load(f)


def get_endpoint_group_processor_name(config):
    """Return the endpoint group processor name from config."""
    return config.get(
        "endpoint_group_processor_name", config["category_processor_name"]
    )


def get_api_category_processor_name(config):
    """Return the API category processor name from config."""
    return config.get(
        "api_category_processor_name", API_CATEGORY_PROCESSOR_NAME_FALLBACK
    )


def iter_api_paths(spec):
    """Yield OpenAPI paths that should participate in Datadog endpoint categories."""
    for path in spec.get("paths", {}):
        m = re.match(r"/api/v\d+/([^/]+)", path)
        if m and m.group(1) in EXCLUDED_GROUPS:
            continue
        yield path


def endpoint_sort_key(path):
    """Sort exact routes before parameterized ones, keeping deeper paths first."""
    segments = path.strip("/").split("/")
    return (path.count("{"), -len(segments), path)


def to_datadog_path_query(path):
    """Convert an OpenAPI path to a Datadog log query."""
    normalized_path = re.sub(r"\{[^/]+\}", "*", path)
    if "{" in path:
        return f"{ELB_URL_ATTR}:{normalized_path}"
    return f'{ELB_URL_ATTR}:"{normalized_path}"'


def extract_endpoint_paths(spec):
    """Return all endpoint paths that should be mapped in the API category processor."""
    paths = set(iter_api_paths(spec))
    paths.update(EXTRA_ENDPOINT_PATHS)
    return sorted(paths, key=endpoint_sort_key)


def build_api_category_categories(paths):
    """Build the detailed API endpoint categories."""
    categories = [
        {"filter": {"query": to_datadog_path_query(path)}, "name": path}
        for path in paths
    ]
    categories.append({"filter": {"query": f"{ELB_URL_ATTR}:/*"}, "name": "Unknown"})
    return categories


def extract_endpoint_groups(spec):
    """Extract version-qualified API groups from OpenAPI spec paths."""
    groups = {}

    for path in iter_api_paths(spec):
        match = re.match(r"/api/(v\d+)/([^/]+)", path)
        if not match:
            continue

        version = match.group(1)
        group = match.group(2)
        base = f"/api/{version}/{group}"
        groups[f"{version}-{group}"] = base

    return groups


def build_endpoint_group_categories(groups):
    """Build Datadog endpoint group categories from version-qualified base paths."""
    categories = [
        {
            "filter": {"query": f"{ELB_URL_ATTR}:{base_path}*"},
            "name": group_name,
        }
        for group_name, base_path in sorted(groups.items())
    ]
    categories.append({"filter": {"query": "*"}, "name": "unknown"})
    return categories


def build_expected_category_processors(config):
    """Load OpenAPI spec and build both expected category processors."""
    spec = load_openapi_spec()
    return [
        {
            "name": get_api_category_processor_name(config),
            "target": API_CATEGORY_TARGET,
            "categories": build_api_category_categories(extract_endpoint_paths(spec)),
        },
        {
            "name": get_endpoint_group_processor_name(config),
            "target": ENDPOINT_GROUP_TARGET,
            "categories": build_endpoint_group_categories(extract_endpoint_groups(spec)),
        },
    ]


def upsert_category_processor(processors, name, target, categories):
    """Replace an existing category processor or append it if missing."""
    for proc in processors:
        if proc.get("type") == "category-processor" and proc.get("name") == name:
            proc["categories"] = categories
            return True

    processors.append(
        {
            "type": "category-processor",
            "name": name,
            "is_enabled": True,
            "categories": categories,
            "target": target,
        }
    )
    return False


def find_category_processor(pipeline, name):
    """Return the named category processor from the pipeline definition."""
    for proc in pipeline.get("processors", []):
        if proc.get("type") == "category-processor" and proc.get("name") == name:
            return proc
    return None


def normalize_categories(categories):
    """Return comparable tuples for category definitions."""
    return [(c["name"], c["filter"]["query"]) for c in categories]


def print_categories(name, categories):
    """Print a category processor summary."""
    print(f"\n{name} categories ({len(categories)}):")
    for cat in categories:
        print(f"  {cat['name']:35s} -> {cat['filter']['query']}")


def report_category_diff(name, current_categories, expected_categories):
    """Print category differences. Returns True when categories differ."""
    current_norm = normalize_categories(current_categories)
    expected_norm = normalize_categories(expected_categories)
    if current_norm == expected_norm:
        return False

    print(f"\nProcessor '{name}' is out of sync:")

    current_names = {c[0] for c in current_norm}
    expected_names = {c[0] for c in expected_norm}

    missing = expected_names - current_names
    extra = current_names - expected_names

    if missing:
        print(f"  Missing categories: {', '.join(sorted(missing))}")
    if extra:
        print(f"  Extra categories: {', '.join(sorted(extra))}")

    current_map = dict(current_norm)
    expected_map = dict(expected_norm)
    for category_name in sorted(current_names & expected_names):
        if current_map[category_name] != expected_map[category_name]:
            print(f"  Category '{category_name}' query differs:")
            print(f"    pipeline.json: {current_map[category_name]}")
            print(f"    api-docs.json: {expected_map[category_name]}")

    if current_norm != expected_norm and set(current_norm) == set(expected_norm):
        print("  Category ordering differs")

    return True


# ---------------------------------------------------------------------------
# Subcommand: update-categories
# ---------------------------------------------------------------------------


def cmd_update_categories(args):
    """Parse api-docs.json, regenerate category processors in pipeline.json."""
    if not PIPELINE_PATH.exists():
        print(f"Error: {PIPELINE_PATH} not found. Run 'get' first.", file=sys.stderr)
        sys.exit(1)

    config = load_config()

    with open(PIPELINE_PATH) as f:
        pipeline = json.load(f)

    processors = pipeline.get("processors", [])
    processor_defs = build_expected_category_processors(config)

    for processor_def in processor_defs:
        found = upsert_category_processor(
            processors,
            processor_def["name"],
            processor_def["target"],
            processor_def["categories"],
        )
        action = "Updated existing" if found else "Created new"
        print(f"{action} category processor '{processor_def['name']}'")

    pipeline["processors"] = processors

    with open(PIPELINE_PATH, "w") as f:
        json.dump(pipeline, f, indent=2)
        f.write("\n")

    for processor_def in processor_defs:
        print_categories(processor_def["name"], processor_def["categories"])

    print(f"\nSaved to {PIPELINE_PATH}")


# ---------------------------------------------------------------------------
# Subcommand: validate-categories
# ---------------------------------------------------------------------------


def cmd_validate_categories(args):
    """Compare pipeline.json categories against api-docs.json. Exit 1 if out of sync."""
    if not PIPELINE_PATH.exists():
        print(f"Error: {PIPELINE_PATH} not found. Run 'get' first.", file=sys.stderr)
        sys.exit(1)

    config = load_config()

    with open(PIPELINE_PATH) as f:
        pipeline = json.load(f)

    out_of_sync = False
    for processor_def in build_expected_category_processors(config):
        processor = find_category_processor(pipeline, processor_def["name"])
        if processor is None:
            print(
                (
                    f"Error: No category processor '{processor_def['name']}' found in "
                    "pipeline.json"
                ),
                file=sys.stderr,
            )
            out_of_sync = True
            continue

        out_of_sync = (
            report_category_diff(
                processor_def["name"],
                processor.get("categories", []),
                processor_def["categories"],
            )
            or out_of_sync
        )

    if not out_of_sync:
        print("Categories are in sync.")
        sys.exit(0)

    print("\nCategories are out of sync. Run 'update-categories' to fix.")
    sys.exit(1)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Manage Datadog pipeline and dashboard configurations.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser(
        "get", help="Fetch pipeline from Datadog, save to pipeline.json"
    )
    subparsers.add_parser(
        "get-dashboard", help="Fetch dashboard from Datadog, save to dashboard.json"
    )
    subparsers.add_parser(
        "push-pipeline", help="Push pipeline.json back to Datadog"
    )
    subparsers.add_parser(
        "get-app-pipeline",
        help="Fetch app pipeline from Datadog, save to app-pipeline.json",
    )
    subparsers.add_parser(
        "push-app-pipeline",
        help="Push app-pipeline.json to Datadog (creates if new)",
    )
    subparsers.add_parser(
        "push-dashboard", help="Push dashboard.json back to Datadog"
    )
    subparsers.add_parser(
        "update-categories",
        help="Auto-detect endpoints from api-docs.json, update category processor",
    )
    subparsers.add_parser(
        "validate-categories",
        help="Validate pipeline categories match api-docs.json endpoints",
    )

    args = parser.parse_args()

    commands = {
        "get": cmd_get,
        "get-app-pipeline": cmd_get_app_pipeline,
        "get-dashboard": cmd_get_dashboard,
        "push-pipeline": cmd_push_pipeline,
        "push-app-pipeline": cmd_push_app_pipeline,
        "push-dashboard": cmd_push_dashboard,
        "update-categories": cmd_update_categories,
        "validate-categories": cmd_validate_categories,
    }

    commands[args.command](args)


if __name__ == "__main__":
    main()
