#!/bin/sh

echo "Running spotless check: "
./gradlew spotlessCheck || echo "\n\n   Spotless check failed. See above for details. To fix the issue: \n\n       ./gradlew spotlessApply \n\n   and then git add/commit again. \n\n"
