package org.vechain.indexer

/** Shared indexer names reused by processors and configs. */
object IndexerNames {
    const val APP_ALL_TIME_ACTION_SUMMARY = "AppAllTimeActionSummaryIndexer"
    const val APP_DAILY_ACTION_SUMMARY = "AppDailyActionSummaryIndexer"
    const val APP_ROUND_ACTION_SUMMARY = "AppRoundActionSummaryIndexer"
    const val AUTHORITY_NODE = "AuthorityNodeIndexer"
    const val GM_NFT = "GmNftIndexer"
    const val HISTORIC_PROPOSALS = "HistoricProposalsIndexer"
    const val HISTORIC_PROPOSALS_VOTE = "HistoricProposalsVoteIndexer"
    const val HISTORY = "HistoryIndexer"
    const val NFT = "NftIndexer"
    const val NFT_BLACKLIST = "NftBlacklistIndexer"
    const val NFT_HOLDERS_BY_BLOCK = "NftHoldersByBlockIndexer"
    const val PROPOSAL_COMMENT = "ProposalCommentIndexer"
    const val PROPOSAL_RESULT = "ProposalResultIndexer"
    const val TRANSACTION = "TransactionIndexer"
    const val TRANSFER = "TransferIndexer"
    const val USER_ALL_TIME_ACTION_SUMMARY = "UserAllTimeActionSummaryIndexer"
    const val USER_DAILY_ACTION_SUMMARY = "UserDailyActionSummaryIndexer"
    const val USER_ROUND_ACTION_SUMMARY = "UserRoundActionSummaryIndexer"
    const val VEVOTE_COMMENT = "VeVoteCommentIndexer"
    const val VEVOTE_RESULT = "VeVoteResultIndexer"
    const val VET_STAKED_BY_BLOCK = "VetStakedByBlockIndexer"
    const val VTHO_CLAIMED_BY_ACCOUNT = "VthoClaimedByAccountIndexer"
    const val VTHO_CLAIMED_BY_BLOCK = "VthoClaimedByBlockIndexer"
    const val X_ALLOC_RESULT = "XAllocResultIndexer"
    const val VALIDATOR = "ValidatorIndexer"
    const val DELEGATION = "DelegationIndexer"
    const val VTHO_GENERATED_BY_BLOCK = "VthoGeneratedByBlockIndexer"
    const val VALIDATOR_REWARD = "ValidatorRewardIndexer"
}
