name: Codebase Versioning

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions: {}

jobs:
  semantic-versioning:
    uses: vechain/github-actions-public/.github/workflows/semantic-versioning.yaml@f54f69d33344b241b5ec901d3d5e1b02d44a1b96 # v2.3.0
    secrets:
      DEPLOY_KEY: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}
