name: Deploy devnet

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to deploy (format v.X.Y.Z-dev)
        required: true
        type: string
        default: v.0.0.0-dev

# Required for authentication through GitHub OIDC
permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-devnet
  cancel-in-progress: false

env:
  ENVIRONMENT: devnet

jobs:
  apply-devnet:
    name: Apply Terraform - Devnet
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/devnet

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Validate version input
        env:
          VERSION_INPUT: ${{ inputs.version }}
        run: |
          if [[ ! "$VERSION_INPUT" =~ ^v\.[0-9]+\.[0-9]+\.[0-9]+-dev$ ]]; then
            echo "Version must match v.X.Y.Z-dev"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.DEV_AWS_ACC_ROLE }}

      # Required for Terraform to source modules from other vechain repositories
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.9.8
          terraform_wrapper: true

      - name: Terraform Initialize
        run: terraform init -backend-config="environments/${{ env.ENVIRONMENT }}.config"

      - name: Terraform Workspace
        run: terraform workspace select ${{ env.ENVIRONMENT }}

      - name: Terraform Validate
        run: terraform validate

      - name: Update image_version
        env:
          VERSION_INPUT: ${{ inputs.version }}
        run: |
          sed -i "/dev:/,/image_version:/s/image_version:.*/image_version: $VERSION_INPUT/" environments/${{ env.ENVIRONMENT }}.yml
          cat environments/${{ env.ENVIRONMENT }}.yml

      - name: Terraform Plan
        run: terraform plan -out "apply.plan"

      - name: Terraform Apply
        run: terraform apply "apply.plan"
