name: Deploy to ECS

on:
  workflow_call:
    inputs:
      indexerImageTag:
        description: "Indexer image tag to deploy"
        required: true
        type: string
      apiImageTag:
        description: "API image tag to deploy"
        required: true
        type: string
      dbSetupTag:
        description: "Mongo setup image tag to deploy"
        required: true
        type: string
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      indexerImageTag:
        description: "Indexer image tag to deploy"
        required: true
        type: string
        default: dev-latest
      apiImageTag:
        description: "API image tag to deploy"
        required: true
        type: string
        default: dev-latest
      dbSetupTag:
        description: "Mongo setup image tag to deploy"
        required: true
        type: string
        default: dev-latest
      environment:
        description: "Environment to deploy to"
        default: dev
        required: true
        type: string

permissions:
  contents: write

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Devops Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEVOPS_REPO_R_W_CONTENT_11_12_2024 }}
          repository: vechainfoundation/devops
          event-type: deploy-veworld-indexer
          client-payload: |
            { 
                "indexerImageTag":  "${{ inputs.indexerImageTag || 'dev-latest' }}", 
                "apiImageTag":      "${{ inputs.apiImageTag     || 'dev-latest' }}",
                "dbSetupTag":       "${{ inputs.dbSetupTag      || 'dev-latest' }}",
                "environment":      "${{ inputs.environment     || 'dev' }}"
            }
