name: Deploy devnet

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to deploy (format v.X.Y.Z-dev)
        required: true
        type: string
        default: v.0.0.0-dev

# Required for authentication through GitHub OIDC
permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: devnet

jobs:
  apply-devnet:
    name: Apply Terraform - Devnet
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/devnet

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Validate version input
        run: |
          if [[ ! "${{ inputs.version }}" =~ ^v\.[0-9]+\.[0-9]+\.[0-9]+-dev$ ]]; then
            echo "Version must match v.X.Y.Z-dev"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.DEV_AWS_ACC_ROLE }}

      # Required for Terraform to source modules from other vechain repositories
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@d4b9b8ff72958532804b70bbe600ad43b36d5f2e # v0.8.0
        with:
          ssh-private-key: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: 1.9.8
          terraform_wrapper: true

      - name: Terraform Initialize
        run: terraform init -backend-config="environments/${{ env.ENVIRONMENT }}.config"

      - name: Terraform Workspace
        run: terraform workspace select ${{ env.ENVIRONMENT }}

      - name: Terraform Validate
        run: terraform validate

      - name: Update image_version
        run: |
          sed -i '/dev:/,/image_version:/s/image_version:.*/image_version: ${{ inputs.version }}/' environments/${{ env.ENVIRONMENT }}.yml
          cat environments/${{ env.ENVIRONMENT }}.yml

      - name: Terraform Plan
        run: terraform plan -out "apply.plan"

      - name: Terraform Apply
        run: terraform apply "apply.plan"
