name: Destroy Dead Environment

on:
  workflow_dispatch:

# Prevent parallel deploy/destroy of the node cluster infrastructure in the same workspace
concurrency: 1

# Required for authentication through GitHub OIDC
permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read   # This is required for actions/checkout

env:
  INDEXER: "veworld"

jobs:
  identify-live-color:
    name: "Identify live and dead colors"
    uses: ./.github/workflows/identify-live-color.yml
    with:
      dns_record_mainnet_name: mainnet.live.prod.${{ env.INDEXER }}.vechain.org.
      dns_record_testnet_name: testnet.live.prod.${{ env.INDEXER }}.vechain.org.
      hosted_zone_id: Z08093993BM56HB3DD4U4
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  destroy-lingering-resources:
    name: Destroy Lingering Resources
    needs: [identify-live-color]
    runs-on: ubuntu-latest
    env:
      dead_color: ${{ needs.identify-live-color.outputs.mainnet_dead_color }}
    steps:
      - name: Check mainnet and testnet on same colour
        id: check-net-color
        run: |
          if [ "${{ needs.identify-live-color.outputs.mainnet_dead_color }}" != "${{ needs.identify-live-color.outputs.testnet_dead_color }}" ]; then
            echo "Mainnet and Testnet colours are not the same, aborting destruction."
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: eu-west-1
            role-to-assume: ${{ secrets.AWS_ACC_ROLE }}

      - name: Destroy Lingering Secrets
        run: |
          echo "Deleting lingering secrets..."
          aws secretsmanager delete-secret --secret-id /${{ env.dead_color }}/${{ env.INDEXER }}/mongo_api_password --force-delete-without-recovery || true
          aws secretsmanager delete-secret --secret-id /${{ env.dead_color }}/${{ env.INDEXER }}/mongo_indexer_password --force-delete-without-recovery || true

      - name: "Destroy LB Logs S3 Buckets"
        run: |
          echo "Deleting LB logs S3 buckets..."
          buckets=("s3://${{ env.dead_color }}-${{ env.INDEXER }}-main-api-ecs-lb-bucket" "s3://${{ env.dead_color }}-${{ env.INDEXER }}-test-api-ecs-lb-bucket")
          for bucket in "${buckets[@]}"; do
            if aws s3 ls "${bucket}" 2>&1 | grep -q 'NoSuchBucket'; then
              echo "Bucket $bucket not found, skipping."
            else
              echo "Bucket $bucket found, deleting..."
              aws s3 rb "$bucket" --force
            fi
          done

      - name: "Destroy Load Balancers"
        run: |
          echo "Fetching load balancer ARNs..."
          dead_main_api_lb_arn=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?contains(LoadBalancerName, '${{ env.dead_color }}-main-api-${{ env.INDEXER }}-alb')].LoadBalancerArn" --output text) || true
          dead_test_api_lb_arn=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?contains(LoadBalancerName, '${{ env.dead_color }}-test-api-${{ env.INDEXER }}-alb')].LoadBalancerArn" --output text) || true

          if [ ! -z "$dead_main_api_lb_arn" ]; then
            echo "Disabling deletion protection for main API load balancer..."
            aws elbv2 modify-load-balancer-attributes --load-balancer-arn $dead_main_api_lb_arn --attributes Key=deletion_protection.enabled,Value=false || true
            echo "Destroying main API load balancer..."
            aws elbv2 delete-load-balancer --load-balancer-arn $dead_main_api_lb_arn || true
          fi

          if [ ! -z "$dead_test_api_lb_arn" ]; then
            echo "Disabling deletion protection for test API load balancer..."
            aws elbv2 modify-load-balancer-attributes --load-balancer-arn $dead_test_api_lb_arn --attributes Key=deletion_protection.enabled,Value=false || true
            echo "Destroying test API load balancer..."
            aws elbv2 delete-load-balancer --load-balancer-arn $dead_test_api_lb_arn || true
          fi

  destroy-environment:
    name: "Destroy Terraform Infrastructure"
    runs-on: ubuntu-latest
    needs: [identify-live-color, destroy-lingering-resources]
    env:
      dead_color: ${{ needs.identify-live-color.outputs.mainnet_dead_color }}

    defaults:
      run:
        working-directory: terraform/api

    steps:
      - name: Show dead color
        run: echo "destroying dead environment - ${{ env.dead_color }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: eu-west-1
            role-to-assume: ${{ secrets.AWS_ACC_ROLE }}

      # Required for Terraform to source modules from other vechain repositories
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3
          terraform_wrapper: true

      - name: Terraform initialize
        id: init
        run: terraform init -backend-config="environments/${{ env.dead_color }}.config" -reconfigure

      - name: Terraform workspace
        id: workspace
        run: terraform workspace select ${{ env.dead_color }}

      - name: Show s3 lifecycle config from state- name: Show s3 lifecycle config from state
        run: terraform state list | grep aws_s3_bucket_lifecycle_configuration

      - name: Delete s3 lifecycle config from state file if found
        run: |
          if terraform state list | grep -q aws_s3_bucket_lifecycle_configuration; then
            echo "Deleting s3 lifecycle configuration from state file..."
            terraform state rm 'module.ecs-lb-service-api["main"].aws_s3_bucket_lifecycle_configuration.lb_logs'
            terraform state rm 'module.ecs-lb-service-api["test"].aws_s3_bucket_lifecycle_configuration.lb_logs'
          else
            echo "No s3 lifecycle configuration found in state file."
          fi
      - name: Show resources to be destroyed
        run: terraform state list
      - name: Plan terraform destroy
        id: plan
        run: terraform plan -out "destroy.plan" -destroy

      - name: Terraform destroy
        id: destroy
        run: terraform apply "destroy.plan"
