name: Gradle Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-build-test
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

jobs:
  gradle-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ api, common, indexer, e2e ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Gradle Test
        run: ./gradlew :package:${{ matrix.package }}:cleanTest :package:${{ matrix.package }}:test

      - name: Copy HTML Test Report
        run: |
          mkdir -p static/${{ matrix.package }}
          cp -r packages/${{ matrix.package }}/build/reports/jacoco/test/html static/${{ matrix.package }}/coverage
          cp -r packages/${{ matrix.package }}/build/reports/tests/test static/${{ matrix.package }}/tests

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        #        if: github.ref == 'refs/heads/main'
        with:
          name: test-results-${{ github.head_ref || github.ref_name }}
          retention-days: 1
          path: static/${{ matrix.package }}

  publish-test-html:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Publish HTML
    #    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: gradle-test
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Static HTML
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.head_ref || github.ref_name }}-${{ github.sha }}-serenity-report

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
