name: Gradle Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-build-test
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ api, common, indexer ]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Gradle Test
        run: ./gradlew {{ matrix.package }}:clean {{ matrix.package }}:test