name: Upload Images

on:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-docker-api
  cancel-in-progress: true

jobs:
  upload-image-to-ecr:
    uses: vechainfoundation/devops/Actions/aws/push-to-ecr.yml@2c80387e0b8d6ebb16ff48ab8bfda3b432404be6
    strategy:
      matrix:
        package: [ api, indexer ]
    with:
      repository: veworld/${{ matrix.package }}
      imageTag: ${{ github.sha }}
      buildCommand: docker build --build-arg VEWORLD_PACKAGE=${{ matrix.package }}

