name: Test, Publish & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  test-gradle:
    uses: ./.github/workflows/test-gradle.yml
    permissions:
      packages: write
  publish-test-report:
    uses: ./.github/workflows/publish-test-results.yml
    needs: test-gradle
    permissions:
      contents: read
      pages: write
      id-token: write
      packages: write
  publish-image-to-ecr:
    uses: ./.github/workflows/publish-ecr-image.yml
    needs: test-gradle
    with:
      imageTag: ${{ github.sha }}
    secrets: inherit
