name: Main Merge - Publish Images & Deploy Dead Color (if exists)

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  test-gradle:
    uses: ./.github/workflows/test-gradle.yml

  publish-test-results:
    uses: ./.github/workflows/publish-test-results.yml
    needs: test-gradle

  vulnerability-scan:
    uses: ./.github/workflows/vulnerability-scan.yml

  publish-images-to-ecr:
    name: Build Images & Publish to ECR
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        env: [dev, prod]
        application: [ indexer, api ]
    uses: ./.github/workflows/publish-ecr-image.yml
    with:
      latestTag: ${{ matrix.env }}-latest
      imageTag: ${{ github.sha }}
      buildArgs: |
        VEWORLD_PACKAGE=${{ matrix.application }}
      workingDirectory: ./
      packageName: ${{ matrix.application }}
      imagePlatform: linux/arm64
      env: ${{ matrix.env }}

  identify-live-color:
    name: Identify Live Color
    uses: ./.github/workflows/identify-live-color.yml
    with:
      dns_record_name: mainnet.live.prod.veworld.vechain.org
      hosted_zone_id: Z074702037Q8JBHKIAYSD
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  deploy-dead-color:
    name: Deploy Dead Color (if env exists)
    # Can be used as testing/dev environment, deployed only if environment already exists
    uses: ./.github/workflows/plan-or-deploy-environment.yml
    needs: [publish-images-to-ecr, identify-live-color]
    with:
      environment: prod
      workspace: ${{ needs.identify-live-color.outputs.dead_color }}
    permissions:
      packages: read
      contents: read
      id-token: write
    secrets: inherit
