name: Test, Publish & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test-gradle:
    uses: ./.github/workflows/test-gradle.yml

  publish-test-results:
    uses: ./.github/workflows/publish-test-results.yml
    needs: test-gradle

  publish-images-to-ecr-dev:
    uses: ./.github/workflows/publish-images.yml
    needs: [test-gradle]
    with:
      imageTag: ${{ github.sha }}
      latestTag: dev-latest
      env: dev
    secrets: inherit

  publish-images-to-ecr-prod:
    uses: ./.github/workflows/publish-images.yml
    needs: [test-gradle]
    with:
      imageTag: ${{ github.sha }}
      latestTag: prod-latest
      env: prod
    secrets: inherit

  deploy-veworld-stack-dev:
    # Will only deploy if dev ECS cluster already exists
    uses: ./.github/workflows/veworld-stack.yml
    with:
      environment: dev
    needs: [publish-images-to-ecr-dev]
    permissions:
      packages: read
      pull-requests: read
      contents: read
    secrets: inherit
