name: Publish (Release)

on:
  release:
    types: [ published ]

jobs:
  publish-to-ecr:
    uses: ./.github/workflows/publish-ecr-image.yml
    with:
      imageTag: ${{ github.ref_name }}
    secrets: inherit