name: On Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-build-test
  cancel-in-progress: true

jobs:
  test-gradle:
    uses: ./.github/workflows/test-gradle.yml

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Gradle Spotless
        run: ./gradlew spotlessCheck

  vulnerability-scan:
    uses: ./.github/workflows/vulnerability-scan.yml

  terraform-plan-dev:
    uses: ./.github/workflows/plan-or-deploy-environment.yml
    with:
      environment: dev
    permissions:
      packages: read
      contents: read
      id-token: write
    secrets: inherit

  terraform-plan-prod-blue:
    uses: ./.github/workflows/plan-or-deploy-environment.yml
    with:
      environment: prod
      workspace: prod-blue
    permissions:
      packages: read
      contents: read
      id-token: write
    secrets: inherit

  terraform-plan-prod-green:
    uses: ./.github/workflows/plan-or-deploy-environment.yml
    with:
      environment: prod
      workspace: prod-green
    permissions:
      packages: read
      contents: read
      id-token: write
    secrets: inherit

  test-live-color-identification:
    uses: ./.github/workflows/identify-live-color.yml
    with:
      dns_record_name: indexer.mainnet.vechain.org.
      hosted_zone_id: Z058676337BU4AOFL6DMM
    permissions:
      contents: read
      id-token: write
    secrets: inherit
