name: On Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-build-test
  cancel-in-progress: true

# Required for authentication through GitHub OIDC
permissions:
  id-token: write # Required for requesting the JWT
  contents: read # Required for actions/checkout
  packages: write # Required for test gradle
  checks: write # Required for test gradle

jobs:
  test-gradle:
    uses: ./.github/workflows/test-gradle.yml

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Gradle Spotless
        run: ./gradlew spotlessCheck

  terraform-plan-dev:
    uses: ./.github/workflows/veworld-stack.yml
    with:
      environment: "dev"
    permissions:
      packages: read
      contents: read
      pull-requests: read
    secrets: inherit

  terraform-plan-prod:
    uses: ./.github/workflows/veworld-stack.yml
    with:
      environment: "prod"
    permissions:
      packages: read
      contents: read
      pull-requests: read
    secrets: inherit
