name: On Pull Request

on:
  push:
    branches:
      - '*'

jobs:
  publish-image-to-ecr:
    uses: ./.github/workflows/publish-ecr-image.yml
    with:
      imageTag: dev-latest
    secrets: inherit
