name: Plan or Apply Terraform

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: Which environment to plan/deploy to
        required: true
        type: environment
  workflow_call:
    inputs:
      environment:
        description: Which environment to plan/deploy to
        required: true
        type: string
      mainnet_version:
        description: The version of this release
        required: false
        type: string
      testnet_version:
        description: The version of this release
        required: false
        type: string
      force:
        description: Whether to force apply
        required: false
        default: false
        type: boolean

# Required for authentication through GitHub OIDC
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  identify-live-color:
    if: ${{ github.event_name == 'pull_request' }}
    name: Identify Live and Dead Colors
    uses: ./.github/workflows/identify-live-color.yml
    with:
      dns_record_mainnet_name: mainnet.live.prod.veworld.vechain.org.
      dns_record_testnet_name: testnet.live.prod.veworld.vechain.org.
      hosted_zone_id: Z08093993BM56HB3DD4U4
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  deploy:
    needs: identify-live-color
    if: always() && needs.identify-live-color.result == 'success' || needs.identify-live-color.result == 'skipped'
    name: "Plan/deploy VeWorld-Indexer terraform - ${{ inputs.environment }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || needs.identify-live-color.outputs.mainnet_live_color }}
    env:
      COLOR: ${{ inputs.environment || needs.identify-live-color.outputs.mainnet_live_color }}

    defaults:
      run:
        working-directory: terraform/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Label
        id: label
        run: echo "running ${{ env.COLOR }} with M ${{ inputs.mainnet_version }} +T ${{ inputs.testnet_version }} F ${{ inputs.force }} for ${{ inputs.environment }}"

      - name: Determine AWS account ID and role
        id: account
        run: |
            if [ "${{ env.account }}" == "prod" ]; then
              echo "role_arn=${{ secrets.PROD_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
            else
              echo "role_arn=${{ secrets.DEV_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
            fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ steps.account.outputs.role_arn }}

      # Required for Terraform to source modules from other vechain repositories
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3
          terraform_wrapper: true

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Initialize
        id: init
        run: terraform init -backend-config="environments/${{ env.COLOR }}.config"

      - name: Terraform Workspace
        id: workspace
        run: terraform workspace select ${{ env.COLOR }}

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Update image_tag
        id: update-image-tag
        if: inputs.mainnet_version && inputs.testnet_version
        run: |
          sed -i '/main:/,/image_version:/s/image_version:.*/image_version: ${{ inputs.mainnet_version }}/' environments/${{ env.COLOR }}.yaml
          sed -i '/test:/,/image_version:/s/image_version:.*/image_version: ${{ inputs.testnet_version }}/' environments/${{ env.COLOR }}.yaml
          cat environments/${{ env.COLOR }}.yaml
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        run: terraform plan -out "apply.plan"

      - name: Should proceed with deployment? (PR builds will never deploy)
        if: github.ref == 'refs/heads/main' || inputs.force
        id: check-env
        run: |
          cluster_services=$(aws ecs list-services --cluster ${{ env.COLOR }}-veworld-cluster --query 'length(serviceArns)' --output text 2>/dev/null || echo "0")
          if [ "${{ inputs.force }}" == "true" ]; then
            echo "Force apply enabled, proceeding with deployment"
          elif (( $cluster_services > 0 )); then
            echo "env_exists=true" >> $GITHUB_OUTPUT
            echo "The ${{ env.COLOR }} environment exists, proceeding with deployment"
          else
            echo "env_exists=false" >> $GITHUB_OUTPUT
            echo "The ${{ env.COLOR }} environment doesn't exist. Please create it manually first, or enable force apply"
          fi

      - name: Terraform Apply
        if: (github.ref == 'refs/heads/main' && steps.check-env.outputs.env_exists == 'true') || inputs.force
        id: apply
        run: terraform apply "apply.plan"

      # - name: Slack Notification
      #   if: steps.apply.outcome == 'success'
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_COLOR: ${{ job.status }}
      #     SLACK_MESSAGE: Deployed VeWorld-Indexer to *${{ env.COLOR }}* environment
      #     SLACK_TITLE: VeWorld-Indexer Infrastructure Deployment
