name: Publish Docker Image

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-docker-api
  cancel-in-progress: true

jobs:
  build-push-scan:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [ api, indexer ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: eu-west-1

      - name: Login To Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check ECR Repository
        id: check-ecr-repo
        env:
          REPOSITORY: veworld/${{ matrix.package }}
        run: |
          if 
            aws ecr describe-repositories --repository-names $REPOSITORY 
          then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Create ECR Repository
        env:
          REPOSITORY: veworld/${{ matrix.package }}
        if: steps.check-ecr-repo.outputs.exists == 'false'
        run: |
          aws ecr create-repository --repository-name $REPOSITORY

      - name: Build & Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: veworld/${{ matrix.package }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ECR_IMAGE=$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          ECR_IMAGE_LATEST=$ECR_REGISTRY/$REPOSITORY:dev-latest
          docker build --build-arg VEWORLD_PACKAGE=${{ matrix.package }} -t $ECR_IMAGE -t $ECR_IMAGE_LATEST .
          docker push $ECR_IMAGE
          docker push $ECR_IMAGE_LATEST

      - name: Scan Docker Image
        id: docker-scan
        uses: alexjurkiewicz/ecr-scan-image@v2.0.0
        with:
          repository: veworld/${{ matrix.package }}
          tag: ${{ github.sha }}
          fail_threshold: high
      - run: echo "${{ steps.docker-scan.outputs.total }} total vulnerabilities"

