name: Build & Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      workingDirectory:
        description: Working directory for the build context
        required: true
        type: string
        default: ./
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - dev
          - prod
        default: dev
      version:
        description: Version tag (only relevant for dev. For prod, semver git ref tag is used)
        required: false
        type: string
        default: v.0.0.0-dev

# Required for authentication through GitHub OIDC
permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read   # This is required for actions/checkout
  packages: read   # This is required for pulling GitHub Packages dependencies

env:
  latestTag: 'latest'
  versionTag: ${{ (github.event_name == 'push' || inputs.environment == 'prod') && github.ref_name || inputs.version }}
  commitHash: ${{ github.sha }}
  workingDirectory: './'
  projectName: 'veworld'
  imagePlatform: 'linux/arm64'
  environment: ${{ inputs.environment || 'prod' }}

jobs:
  build-and-publish:
    runs-on: docker-build-arm64
    strategy:
      matrix:
        packageName: ["api", "indexer"]
    defaults:
      run:
        working-directory: ${{ env.workingDirectory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ env.environment == 'dev' && secrets.DEV_AWS_ACC_ROLE || secrets.AWS_ACC_ROLE }}

      - name: Login To Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@19d944daaa35f0fa1d3f7f8af1d3f2e5de25c5b7 # v2.1.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build images and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          file: Dockerfile
          platforms: ${{ env.imagePlatform }}
          build-args: |
            PACKAGE_NAME=${{ matrix.packageName }}
            APP_VERSION=${{ env.versionTag }}
          push: true
          context: ${{ env.workingDirectory }}
          provenance: false
          cache-from: type=gha,scope=${{ matrix.packageName }}-ecr
          cache-to: type=gha,mode=max,scope=${{ matrix.packageName }}-ecr
          secrets: |
            "gradle_props=gpr.user=${{ github.actor }}
            gpr.key=${{ secrets.GITHUB_TOKEN }}"
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.projectName }}/${{ matrix.packageName }}:${{ env.versionTag }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.projectName }}/${{ matrix.packageName }}:${{ env.latestTag }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.projectName }}/${{ matrix.packageName }}:${{ env.commitHash }}

      - name: Scan Docker image
        id: docker-scan
        uses: alexjurkiewicz/ecr-scan-image@23adad502f48a23cf2acf8a6dda2c34e194df8e0 # v1.7.1
        with:
          repository: ${{env.projectName}}/${{ matrix.packageName }}
          tag: ${{ env.versionTag }}
          fail_threshold: medium

      - name: On Scan Failure
        if: failure() && steps.docker-scan.outcome == 'failure'
        run: |
          aws ecr batch-delete-image \
            --repository-name ${{env.projectName}}/${{ matrix.packageName }} \
            --image-ids versionTag=${{ env.versionTag }} versionTag=${{ env.latestTag }}
