name: DEV Build & Publish Docker Image

on:
  push:
    branches:
      - yellow-env

    paths:
      - terraform/devnet**
      - packages/**
      - .github/workflows/publish-ecr-image-dev.yml
# Required for authentication through GitHub OIDC
permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read   # This is required for actions/checkout

env:
  latestTag:  'latest'
  versionTag: ${{ github.ref_name }}
  commitHash: ${{ github.sha }}
  workingDirectory:  './' 
  projectName:  'veworld'
  imagePlatform: 'linux/arm64' 

jobs:
  build-and-publish:
    runs-on: docker-build-arm64
    strategy:
      matrix:
        packageName: ["api", "indexer"]
    defaults:
      run:
        working-directory: ${{ env.workingDirectory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.DEV_AWS_ACC_ROLE }}

      - name: Login To Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          platforms: ${{ env.imagePlatform }}
          build-args: |
            PACKAGE_NAME=${{ matrix.packageName }}
            APP_VERSION=${{ env.versionTag }}
          push: true
          context: ${{ env.workingDirectory }}
          provenance: false
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.projectName }}/${{ matrix.packageName }}:${{ env.versionTag }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.projectName }}/${{ matrix.packageName }}:${{ env.latestTag }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.projectName }}/${{ matrix.packageName }}:${{ env.commitHash }}

      - name: Scan Docker image
        id: docker-scan
        uses: alexjurkiewicz/ecr-scan-image@v1.7.1
        with:
          repository: ${{env.projectName}}/${{ matrix.packageName }}
          tag: ${{ env.versionTag }}
          fail_threshold: medium

      - name: On Scan Failure
        if: failure() && steps.docker-scan.outcome == 'failure'
        run: |
          aws ecr batch-delete-image \
            --repository-name ${{env.projectName}}/${{ matrix.packageName }} \
            --image-ids versionTag=${{ env.versionTag }} versionTag=${{ env.latestTag }}
