name: Publish Application Images to ECR

on:
  workflow_call:
    inputs:
      imageTag:
        required: true
        type: string
      latestTag:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  publish-application-images:
    name: Publish Application Images
    secrets: inherit
    permissions:
      id-token: write
    strategy:
      matrix:
        application: [ indexer, api ]
    uses: ./.github/workflows/publish-ecr-image.yml
    with:
      latestTag: ${{ inputs.latestTag }}
      imageTag: ${{ inputs.imageTag }}
      buildArgs: |
        VEWORLD_PACKAGE=${{ matrix.application }}
      workingDirectory: ./
      packageName: ${{ matrix.application }}
      imagePlatform: linux/arm64
      env: ${{ inputs.env }}