name: Push Images to ECR and Scan

on:
  push:
    branches:
      - "*"
  workflow_call:
    inputs:
      imageTag:
        required: true
        type: string
      latestTag:
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [api, indexer]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: eu-west-1

      - name: Login To Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64
          build-args: |
            VEWORLD_PACKAGE=${{ matrix.package }}
          push: true
          provenance: false
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/veworld/${{ matrix.package }}:${{ inputs.imageTag }}
            ${{ steps.login-ecr.outputs.registry }}/veworld/${{ matrix.package }}:${{ inputs.latestTag }}

      - name: Scan Docker image
        id: docker-scan
        uses: alexjurkiewicz/ecr-scan-image@v1.7.1
        with:
          repository: ${{ steps.login-ecr.outputs.registry }}/veworld/${{ matrix.package }}
          tag: ${{ inputs.imageTag }}
          fail_threshold: high

      - name: On Scan Failure
        if: failure() && steps.docker-scan.outcome == 'failure'
        run: |
          aws ecr batch-delete-image \
            --repository-name veworld/${{ matrix.package }} \
            --image-ids imageTag=${{ inputs.imageTag }} imageTag=${{ inputs.latestTag }}          
