name: restore non live prod cluster

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to restore - dev or dead colour on prod"
        required: true
        type: choice
        options:
          - dev
          - dead-prod

concurrency: 1

# Required for authentication through GitHub OIDC
permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read   # This is required for actions/checkout

jobs:
  identify-live-color:
    name: "Identify live and dead colors"
    uses: ./.github/workflows/identify-live-color.yml
    with:
      dns_record_mainnet_name: mainnet.live.prod.veworld.vechain.org.
      dns_record_testnet_name: testnet.live.prod.veworld.vechain.org.
      hosted_zone_id: Z08093993BM56HB3DD4U4
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  set-cluster:
    name: "set restore cluster to not prod live"
    runs-on: ubuntu-latest
    needs: [identify-live-color]
    outputs:
      sourcecluster: ${{ steps.setcluster.outputs.sourcecluster }}
      targetcluster: ${{ steps.setcluster.outputs.targetcluster }}
    steps:
      - name: set restore cluster
        id: setcluster
        run: |
          sourcecluster=${{ needs.identify-live-color.outputs.mainnet_live_color }}
          if [ ${{ inputs.environment }} == "dead-prod" ]; then
            targetcluster=${{ needs.identify-live-color.outputs.mainnet_dead_color }}
          else
            targetcluster=${{ inputs.environment }}
          fi
          echo "sourcecluster=$sourcecluster"
          echo "sourcecluster=$sourcecluster" >> $GITHUB_OUTPUT
          echo "targetcluster=$targetcluster"
          echo "targetcluster=$targetcluster" >> $GITHUB_OUTPUT

  restore:
    name: stop ecs services restore db and restart
    needs: [set-cluster]
    runs-on: ubuntu-latest
    outputs:
      svc_restart: ${{ steps.check-is-down.outputs.svc_restart }}
    env:
      sourcecluster: ${{ needs.set-cluster.outputs.sourcecluster }}
      targetcluster: ${{ needs.set-cluster.outputs.targetcluster }}
      ecscluster: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-cluster
      testidxsvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-test-indexer-service
      testapisvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-test-api-service
      mainidxsvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-main-indexer-service
      mainapisvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-main-api-service
      project: ${{ secrets.MONGO_PROJECT_ID }}
    steps:
      - name: Determine AWS account ID and role
        id: account
        run: |
          if [ "${{ inputs.environment }}" == "dead-prod" ]; then
            echo "role_arn=${{ secrets.PROD_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
          else
            echo "role_arn=${{ secrets.DEV_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ steps.account.outputs.role_arn }}


      - name: Check cluster is down, restore and restart services
        id: check-is-down
        run: |
          if [ $(aws ecs describe-clusters --cluster $ecscluster --query \
            'clusters[].clusterName' --output text| wc -l) -eq 0 ]; then
            echo "FYI $ecscluster not set up!"
            echo "svc_restart=false"
            echo "svc_restart=false" >> "$GITHUB_OUTPUT"
          else
           initial_services=$(aws ecs describe-services --cluster $ecscluster \
             --services $testidxsvc $testapisvc $mainidxsvc $mainapisvc \
             --query 'services[].runningcount' --output text |grep -v 0|wc -l)
           if [ $initial_services -gt 0 ]; then
             echo "svc_restart=true"
             echo "svc_restart=true" >> "$github_output"
             echo "the $targetcluster cluster $initial_services services with \
              running tasks, stopping"
             aws ecs update-service --cluster $ecscluster --service \
               $testidxsvc --desired-count 0
             aws ecs update-service --cluster $ecscluster --service \
               $testapisvc --desired-count 0
             aws ecs update-service --cluster $ecscluster --service \
               $mainidxsvc --desired-count 0
             aws ecs update-service --cluster $ecscluster --service \
               $mainapisvc --desired-count 0
             echo "Waiting 1 minute to let changes apply"
              sleep 60
             running_services=$(aws ecs describe-services --cluster \
               $ecscluster --services $testidxsvc $testapisvc $mainidxsvc \
               $mainapisvc --query 'services[].runningCount'| grep -c '\d')
             if [ $running_services -gt 0 ]; then
               echo "The $ecscluster cluster still running services - halting!"
               exit 1
             fi
           else
             echo "svc_restart=false"
             echo "svc_restart=false" >> "$GITHUB_OUTPUT"
           fi
          fi

      - name: Atlas setup
        id: atlas-setup
        uses: mongodb/atlas-github-action@v0.2.0
        env:
          sourcecluster: ${{ needs.set-cluster.outputs.sourcecluster }}
          targetcluster: ${{ needs.set-cluster.outputs.targetcluster }}
          ecscluster: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-cluster
          testidxsvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-test-indexer-service
          testapisvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-test-api-service
          mainidxsvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-main-indexer-service
          mainapisvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-main-api-service
          MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGO_PUBLIC_KEY }}
          MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGO_PRIVATE_KEY }}
          # default organisation ID
          MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGO_ORG_ID }}
          # default project ID
          MONGODB_ATLAS_PROJECT_ID: ${{ secrets.MONGO_PROJECT_ID }}

      - name: Restore DeadEnv DB from last prod snapshot
        id: restore-dead-env-db
        env:
          sourcecluster: ${{ needs.set-cluster.outputs.sourcecluster }}
          targetcluster: ${{ needs.set-cluster.outputs.targetcluster }}
          ecscluster: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-cluster
          testidxsvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-test-indexer-service
          testapisvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-test-api-service
          mainidxsvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-main-indexer-service
          mainapisvc: ${{ needs.set-cluster.outputs.targetcluster }}-veworld-main-api-service
          MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGO_PUBLIC_KEY }}
          MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGO_PRIVATE_KEY }}
          # default organisation ID
          MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGO_ORG_ID }}
          # default project ID
          MONGODB_ATLAS_PROJECT_ID: ${{ secrets.MONGO_PROJECT_ID }}
        run: |
          sourceMainDB="$sourcecluster-Mainnet"
          targetMainDB="$targetcluster-Mainnet"
          sourceTestDB="$sourcecluster-Testnet"
          targetTestDB="$targetcluster-Testnet"
          if [ "$targetcluster" == "dev" ]; then
            targetProject="${{ secrets.MONGO_DEV_PROJECT_ID }}"
          else
            targetProject="${{ secrets.MONGO_PROJECT_ID }}"
          fi
          echo "TestDB"
          atlas backups snapshots list $sourceTestDB | true
          testSnapshot=$(atlas backup snapshots list $sourceTestDB --projectId \
            $project | grep "completed" | sort -r -k4 | head -1 | \
            awk '{print $1}')
          echo "$sourceTestDB snap $testSnapshot restoring to $targetTestDB"
          # Note: cross project restores can be specified with target as
          # clustername, snapshotId is key, but watched from source
          testJobid=$(atlas backups restores start automated --clusterName \
                $sourceTestDB --snapshotId $testSnapshot --projectId $project \
                --targetClusterName $targetTestDB --targetProjectId \
                $targetProject )| awk '{print $3}'
          echo "Restore job id $testJobid"
          testRestore=$(atlas backups restores list $sourceTestDB \
                --projectId $project | tail -1 | awk '{ print $1 }')
          echo "Restore $testRestore"
          atlas backups restores watch --clusterName $sourceTestDB \
                $testRestore --projectId $project

          echo "MainDB"
          mainSnapshot=$(atlas backup snapshots list $sourceMainDB --projectId \
            $project | grep "completed" | sort -r -k4 | head -1 | \
            awk '{print $1}')
          echo "$sourceMainDB snap $mainSnapshot restoring to $targetMainDB"
          mainJobid=$(atlas backups restores start automated --clusterName \
            $sourceMainDB --snapshotId $mainSnapshot --projectId $project \
            --targetClusterName $targetMainDB --targetProjectId \
            $targetProject )| awk '{print $3}'
          echo "Restore job id $mainJobid"
          mainRestore=$(atlas backups restores list $sourceMainDB --projectId \
            $project | tail -1 | awk '{ print $1 }')
          echo "Restore $mainRestore"
          atlas backups restores watch --clusterName $sourceMainDB \
            $mainRestore --projectId $project

      - name: start Indexing
        id: start-dead-indexing
        if: ${{ steps.check-is-down.outputs.svc_restart }}
        env:
          svc_restart: ${{ steps.check-is-down.outputs.svc_restart}}
        run: |
          if [ $svc_restart == "true" ]; then
            running_services=$(aws ecs describe-services --cluster $ecscluster \
              --services $testidxsvc $testapisvc $mainidxsvc $mainapisvc \
              --query 'services[].runningCount' --output text |grep -v 0|wc -l)
            if [ $running_services -gt 0 ]; then
              echo "Warning ! Unexpected activity - $targetcluster has \
               $running_services running services"
            fi
            aws ecs update-service --cluster $ecscluster --service \
              $testidxsvc --desired-count 1
            aws ecs update-service --cluster $ecscluster --service \
              $testapisvc --desired-count 1
            aws ecs update-service --cluster $ecscluster --service \
              $mainidxsvc --desired-count 1
            aws ecs update-service --cluster $ecscluster --service \
              $mainapisvc --desired-count 1
            echo "Waiting 1 minute to let changes apply"
            sleep 60
            running_services=$(aws ecs describe-services --cluster \
              $ecscluster --services $testidxsvc $testapisvc $mainidxsvc \
              $mainapisvc --query 'services[].runningCount' --output text \
              | grep -v 0|wc -l)
            if [ $running_services -lt 1 ]; then
              echo "The $ecscluster not started running services, check!"
              exit 1
           fi
          fi
