name: 'Security Checks'
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  checkov:
    uses: vechain/github-actions-public/.github/workflows/checkov.yaml@f54f69d33344b241b5ec901d3d5e1b02d44a1b96 # v2.3.0

  infracost:
    uses: vechain/github-actions-public/.github/workflows/infracost.yaml@f54f69d33344b241b5ec901d3d5e1b02d44a1b96 # v2.3.0
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      TERRAFORM_SSH_KEY: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}
