name: 'Security Checks'
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  checkov:
    uses: vechain/github-actions-public/.github/workflows/checkov.yaml@c8645e5723b09ce657b865f78924b87a357df036 # v2.3.1

  infracost:
    uses: vechain/github-actions-public/.github/workflows/infracost.yaml@c8645e5723b09ce657b865f78924b87a357df036 # v2.3.1
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      TERRAFORM_SSH_KEY: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}
