name: Switch Route 53 Records

on:
  workflow_call: 
    
  workflow_dispatch:
   inputs:
    current_record:
      description: 'Current active record (testnet.live.prod.veworld.vechain.org or testnet.dead.prod.veworld.vechain.org)'
      required: true
      default: 'testnet.live.prod.veworld.vechain.org'
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
  

jobs:
  switch-records:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    env:
      HOSTED_ZONE_ID: Z074702037Q8JBHKIAYSD
      LIVE_RECORD: testnet.live.prod.veworld.vechain.org
      DEAD_RECORD: testnet.dead.prod.veworld.vechain.org

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        role-to-assume: ${{ secrets.PROD_AWS_ACC_ROLE }}

    - name: Switch Route 53 Records
      id: switch
      run: |
        HOSTED_ZONE_ID=${{ env.HOSTED_ZONE_ID }}
        LIVE_RECORD=${{ env.LIVE_RECORD }}
        DEAD_RECORD=${{ env.DEAD_RECORD }}
        
  
        CURRENT_IP=$(aws route53 list-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --query "ResourceRecordSets[?Name == '$DEAD_RECORD.'].ResourceRecords[0].Value" --output text)
        NEW_IP=$(aws route53 list-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --query "ResourceRecordSets[?Name == '$LIVE_RECORD.'].ResourceRecords[0].Value" --output text)
        
        echo "Switching $CURRENT_RECORD (IP: $CURRENT_IP) with $NEW_RECORD (IP: $NEW_IP)"

        aws route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --change-batch "{
          \"Changes\": [
            {
              \"Action\": \"UPSERT\",
              \"ResourceRecordSet\": {
                \"Name\": \"$CURRENT_RECORD\",
                \"Type\": \"A\",
                \"TTL\": 300,
                \"ResourceRecords\": [{\"Value\": \"$NEW_IP\"}]
              }
            },
            {
              \"Action\": \"UPSERT\",
              \"ResourceRecordSet\": {
                \"Name\": \"$NEW_RECORD\",
                \"Type\": \"A\",
                \"TTL\": 300,
                \"ResourceRecords\": [{\"Value\": \"$CURRENT_IP\"}]
              }
            }
          ]
        }"

    - name: Confirm Switch
      run: |
        echo "Verifying switch..."
        aws route53 list-resource-record-sets --hosted-zone-id ${{ env.HOSTED_ZONE_ID }} --query "ResourceRecordSets[?Name == '${{ env.LIVE_RECORD }}.']"
        aws route53 list-resource-record-sets --hosted-zone-id ${{ env.HOSTED_ZONE_ID }} --query "ResourceRecordSets[?Name == '${{ env.DEAD_RECORD }}.']"
