name: Switch Live Environment

on:
  workflow_dispatch:
    inputs:
      testnet_only:
        description: "Switch testnet ONLY?"
        required: false
        type: boolean
      mainnet_only:
        description: "Switch mainnet ONLY?"
        required: false
        type: boolean

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read   # This is required for actions/checkout

jobs:

  identify-live-color:
    name: Identify live color
    uses: ./.github/workflows/identify-live-color.yml
    with:
      dns_record_mainnet_name: mainnet.live.prod.veworld.vechain.org.
      dns_record_testnet_name: testnet.live.prod.veworld.vechain.org.
      hosted_zone_id: Z08093993BM56HB3DD4U4
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  fetch-lb-dns-names:
    name: Fetch load balancer DNS names
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.PROD_AWS_ACC_ROLE }}

      - name: Get load balancer DNS names
        id: get-lb-dns-names
        run: |
          blue_main_dns=$(aws elbv2 describe-load-balancers --names prod-blue-main-api-veworld-alb --query 'LoadBalancers[0].DNSName' --output text) ||
          { echo "Error: Failed to fetch blue mainnet load balancer dns. Please ensure the dead environment is deployed and ready to receive traffic"; exit 1; }
          blue_test_dns=$(aws elbv2 describe-load-balancers --names prod-blue-test-api-veworld-alb --query 'LoadBalancers[0].DNSName' --output text) ||
          { echo "Error: Failed to fetch blue testnet load balancer dns. Please ensure the dead environment is deployed and ready to receive traffic"; exit 1; }
          green_main_dns=$(aws elbv2 describe-load-balancers --names prod-green-main-api-veworld-alb --query 'LoadBalancers[0].DNSName' --output text) ||
          { echo "Error: Failed to fetch green mainnet load balancer dns. Please ensure the dead environment is deployed and ready to receive traffic"; exit 1; }
          green_test_dns=$(aws elbv2 describe-load-balancers --names prod-green-test-api-veworld-alb --query 'LoadBalancers[0].DNSName' --output text) ||
          { echo "Error: Failed to fetch green testnet load balancer dns. Please ensure the dead environment is deployed and ready to receive traffic"; exit 1; }

          echo "blue_main_dns=$blue_main_dns" >> $GITHUB_OUTPUT
          echo "blue_test_dns=$blue_test_dns" >> $GITHUB_OUTPUT
          echo "green_main_dns=$green_main_dns" >> $GITHUB_OUTPUT
          echo "green_test_dns=$green_test_dns" >> $GITHUB_OUTPUT

    outputs:
      blue_main_dns: ${{ steps.get-lb-dns-names.outputs.blue_main_dns }}
      blue_test_dns: ${{ steps.get-lb-dns-names.outputs.blue_test_dns }}
      green_main_dns: ${{ steps.get-lb-dns-names.outputs.green_main_dns }}
      green_test_dns: ${{ steps.get-lb-dns-names.outputs.green_test_dns }}

  deploy-vpc-stack:
    name: Deploy VPC stack & switch DNS
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/vpc

    needs: [fetch-lb-dns-names, identify-live-color]
    env:
      environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check test_only
        id: check-test-only
        run: |
          if [ "${{ github.event.inputs.testnet_only }}" == "true" ]; then
            echo "test_only=true" >> $GITHUB_OUTPUT
            echo "main_only=false" >> $GITHUB_OUTPUT
            echo "network=testnet" >> $GITHUB_OUTPUT
            echo "Switching only the testnet environment"
            echo "Current testnet live color: ${{ needs.identify-live-color.outputs.testnet_live_color }}"
            echo "New testnet live color: ${{ needs.identify-live-color.outputs.testnet_dead_color }}"
            echo "Preparing to switch testnet live environment from ${{ needs.identify-live-color.outputs.testnet_live_color }} to ${{ needs.identify-live-color.outputs.testnet_dead_color }}"

          elif [ "${{ github.event.inputs.mainnet_only }}" == "true" ]; then
            echo "test_only=false" >> $GITHUB_OUTPUT
            echo "main_only=true" >> $GITHUB_OUTPUT
            echo "network=mainnet" >> $GITHUB_OUTPUT
            echo "Switching only the mainnet environment"
            echo "Current mainnet live color: ${{ needs.identify-live-color.outputs.mainnet_live_color }}"
            echo "New mainnet live color: ${{ needs.identify-live-color.outputs.mainnet_dead_color }}"
            echo "Preparing to switch mainnet live environment from ${{ needs.identify-live-color.outputs.mainnet_live_color }} to ${{ needs.identify-live-color.outputs.mainnet_dead_color }}"

          else
            echo "test_only=false" >> $GITHUB_OUTPUT
            echo "main_only=false" >> $GITHUB_OUTPUT
            echo "network=all" >> $GITHUB_OUTPUT
            echo "Switching both the testnet and mainnet environments"
            echo "Current mainnet live color: ${{ needs.identify-live-color.outputs.mainnet_live_color }}"
            echo "New mainnet live color: ${{ needs.identify-live-color.outputs.mainnet_dead_color }}"
            echo "Preparing to switch mainnet live environment from ${{ needs.identify-live-color.outputs.mainnet_live_color }} to ${{ needs.identify-live-color.outputs.mainnet_dead_color }}"
            echo "Current testnet live color: ${{ needs.identify-live-color.outputs.testnet_live_color }}"
            echo "New testnet live color: ${{ needs.identify-live-color.outputs.testnet_dead_color }}"
            echo "Preparing to switch testnet live environment from ${{ needs.identify-live-color.outputs.testnet_live_color }} to ${{ needs.identify-live-color.outputs.testnet_dead_color }}"
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.PROD_AWS_ACC_ROLE }}

      - name: Check Dead ENV is Ready
        id: check-dead-env-is-ready
        run: |
          if [ "${{ github.event.inputs.testnet_only }}" == "true" ]; then
              cluster_services=$(aws ecs list-services --cluster ${{ needs.identify-live-color.outputs.testnet_dead_color }}-veworld-cluster --query 'length(serviceArns)' --output text)
              if (( $cluster_services > 3 )); then
                echo "env_ready=true" >> $GITHUB_OUTPUT
                echo "The ${{ needs.identify-live-color.outputs.testnet_dead_color }} cluster is ready, proceeding with deployment"
              else
                echo "env_ready=false" >> $GITHUB_OUTPUT
                echo "The ${{ needs.identify-live-color.outputs.testnet_dead_color }} cluster has no services running. Please ensure the environment is ready for traffic"
                exit 0
              fi
          elif [ "${{ github.event.inputs.mainnet_only }}" == "true" ]; then
              cluster_services=$(aws ecs list-services --cluster ${{ needs.identify-live-color.outputs.mainnet_dead_color }}-veworld-cluster --query 'length(serviceArns)' --output text)
              if (( $cluster_services > 3 )); then
                echo "env_ready=true" >> $GITHUB_OUTPUT
                echo "The ${{ needs.identify-live-color.outputs.mainnet_dead_color }} cluster is ready, proceeding with deployment"
              else
                echo "env_ready=false" >> $GITHUB_OUTPUT
                echo "The ${{ needs.identify-live-color.outputs.mainnet_dead_color }} cluster has no services running. Please ensure the environment is ready for traffic"
                exit 0
              fi
          else
              cluster_services=$(aws ecs list-services --cluster ${{ needs.identify-live-color.outputs.mainnet_dead_color }}-veworld-cluster --query 'length(serviceArns)' --output text)
              if (( $cluster_services > 3 )); then
                echo "env_ready=true" >> $GITHUB_OUTPUT
                echo "The ${{ needs.identify-live-color.outputs.mainnet_dead_color }} cluster is ready, proceeding with deployment"
              else
                echo "env_ready=false" >> $GITHUB_OUTPUT
                echo "The ${{ needs.identify-live-color.outputs.mainnet_dead_color }} cluster has no services running. Please ensure the environment is ready for traffic"
                exit 0
              fi
              cluster_services=$(aws ecs list-services --cluster ${{ needs.identify-live-color.outputs.testnet_dead_color }}-veworld-cluster --query 'length(serviceArns)' --output text)
              if (( $cluster_services > 3 )); then
                echo "env_ready=true" >> $GITHUB_OUTPUT
                echo "The ${{ needs.identify-live-color.outputs.testnet_dead_color }} cluster is ready, proceeding with deployment"
              else
                echo "env_ready=false" >> $GITHUB_OUTPUT
                echo "The ${{ needs.identify-live-color.outputs.testnet_dead_color }} cluster has no services running. Please ensure the environment is ready for traffic"
                exit 0
              fi
          fi

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3
          terraform_wrapper: true

      - name: Terraform Initialize
        id: init
        run: terraform init -backend-config="../api/environments/${{ needs.identify-live-color.outputs.testnet_dead_color }}.config"

      - name: Terraform Workspace
        id: workspace
        run: terraform workspace select $(echo ${{ env.environment }} | awk -F- '{print $1}')

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        if: steps.check-dead-env-is-ready.outputs.env_ready == 'true'
        run: terraform plan -out "apply.plan" --var=live_color_mainnet=${{ needs.identify-live-color.outputs.mainnet_dead_color }} --var=live_color_testnet=${{ needs.identify-live-color.outputs.testnet_dead_color }} --var=network=${{ steps.check-test-only.outputs.network }}

      - name: Terraform Apply
        if: steps.check-dead-env-is-ready.outputs.env_ready == 'true'
        id: apply
        run: terraform apply "apply.plan"
