name: Sync Datadog Config

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Prod Deployment Workflow"]
    types: [completed]

permissions:
  contents: read

jobs:
  push:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: pip install -r metrics/datadog/scripts/requirements.txt

      - name: Push pipeline to Datadog
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DD_SITE: ${{ secrets.DD_SITE }}
        run: python metrics/datadog/scripts/manage_pipeline.py push-pipeline

      - name: Push app pipeline to Datadog
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DD_SITE: ${{ secrets.DD_SITE }}
        run: python metrics/datadog/scripts/manage_pipeline.py push-app-pipeline

      - name: Push WAF pipeline to Datadog
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DD_SITE: ${{ secrets.DD_SITE }}
        run: python metrics/datadog/scripts/manage_pipeline.py push-waf-pipeline

      - name: Push dashboard to Datadog
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DD_SITE: ${{ secrets.DD_SITE }}
        run: python metrics/datadog/scripts/manage_pipeline.py push-dashboard
