name: Test E2E

# on push to all branches
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ENV_FILE_NAME=.env.example; make start