name: Tests (Gradle)

on:
  pull_request:
  push:
    branches:
      - 'main'
env:
  COMPOSE_BAKE: "true"

permissions:
  contents: read
  id-token: write
  packages: write
  checks: write

concurrency:
  group: ${{ github.head_ref || github.ref_name }}-build-test
  cancel-in-progress: true

jobs:
  check-formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "21"
          cache: "gradle"

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Gradle Spotless
        run: ./gradlew spotlessCheck

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ api, common, indexer ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Unit Test
        run: make test-${{ matrix.package }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: packages/${{ matrix.package }}/build/test-results/test/TEST-*.xml

      - name: Copy HTML Test Report
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p static/${{ matrix.package }}
          if [ -d "packages/${{ matrix.package }}/build/reports/jacoco/test/html" ]; then
            cp -r packages/${{ matrix.package }}/build/reports/jacoco/test/html static/${{ matrix.package }}/coverage
            cp -r packages/${{ matrix.package }}/build/reports/tests/test static/${{ matrix.package }}/tests
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: test-results-${{ matrix.package }}-${{ github.head_ref || github.ref_name }}
          retention-days: 1
          path: static/${{ matrix.package }}

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: E2E Test
        run: make test-e2e

      - name: Debug E2E
        if: failure()
        run: |
          echo "ℹ️ Docker and compose versions"
          docker --version
          docker compose version
          echo "ℹ️ Networks"
          docker network ls
          docker network inspect vechain-database || true
          docker network inspect vechain-thor-e2e || true
          echo "ℹ️ Containers"
          docker ps -a
          echo "ℹ️ Thor Script Logs"
          docker logs thor-thor-tx-script-1
          echo "ℹ️ API Logs"
          docker logs vechain-indexer-api
          echo "ℹ️ Indexer Logs"
          docker logs vechain-indexer

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: packages/e2e/build/test-results/test/TEST-*.xml

      - name: Copy HTML Test Report
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p static/e2e
          if [ -d "packages/e2e/build/reports/jacoco/test/html" ]; then
            cp -r packages/e2e/build/reports/jacoco/test/html static/e2e/coverage
            cp -r packages/e2e/build/reports/tests/test static/e2e/tests
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: test-results-e2e-${{ github.head_ref || github.ref_name }}
          retention-days: 1
          path: static/e2e