name: Test (Gradle)

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  id-token: write
  packages: write
  checks: write

jobs:
  check-formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "21"

      - name: Gradle Spotless
        run: ./gradlew spotlessCheck

  test-gradle:
    name: Gradle Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [api, common, e2e, indexer]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Gradle Test
        run: ./gradlew :package:${{ matrix.package }}:cleanTest :package:${{ matrix.package }}:test

      - name: Debug E2E
        if: failure() && matrix.package == 'e2e'
        run: |
          export INDEXER_ENV_FILE_NAME=packages/indexer/.env.example
          export API_ENV_FILE_NAME=packages/api/.env.example
          docker network ls
          docker ps
          docker ps -a
          docker network inspect vechain-database || true
          docker network inspect vechain-thor || true
          docker network inspect vechain || true
          docker compose -f database/docker-compose-mongo.yaml logs
          docker compose -f database/docker-compose-mongo-setup.yaml logs
          docker compose -f thor/docker-compose.yaml logs
          docker compose logs

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: packages/${{ matrix.package }}/build/test-results/test/TEST-*.xml

      - name: Copy HTML Test Report
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p static/${{ matrix.package }}
          if [ -d "packages/${{ matrix.package }}/build/reports/jacoco/test/html" ]; then
            cp -r packages/${{ matrix.package }}/build/reports/jacoco/test/html static/${{ matrix.package }}/coverage
            cp -r packages/${{ matrix.package }}/build/reports/tests/test static/${{ matrix.package }}/tests
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: test-results-${{ github.head_ref || github.ref_name }}
          retention-days: 1
          path: static
