name: Validate PR Label
on:
  pull_request:
    branches: main
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check version labels
        run: |
          num_major=$(jq '.pull_request.labels[] | select(.name == "major") | length' "$GITHUB_EVENT_PATH")
          num_minor=$(jq '.pull_request.labels[] | select(.name == "minor") | length' "$GITHUB_EVENT_PATH")
          num_patch=$(jq '.pull_request.labels[] | select(.name == "patch") | length' "$GITHUB_EVENT_PATH")

          total=$(($num_major + $num_minor + $num_patch))

          if [ "$total" != 1 ]; then
            echo "Please apply exactly one version label (patch/minor/major) to the PR"
            exit 1
          fi
