name: Validate PR Label
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
  workflow_dispatch:

permissions: {}

jobs:
  validate:
    uses: vechain/github-actions-public/.github/workflows/validate-pr-label.yaml@f54f69d33344b241b5ec901d3d5e1b02d44a1b96 # v2.3.0
    with:
      FAIL_IF_MISSING_LABEL: true
