name: VeWorld Indexer Stack

on:
  # trigger deployment manually
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy"
        required: true
        default: dev
        type: choice
        options:
            - dev
            - prod
  workflow_call:
    inputs:
      environment:
        description: Which environment to plan/deploy to ('dev' or 'prod')
        required: true
        default: dev
        type: string

# Required for authentication through GitHub OIDC
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    name: "Plan/deploy VeWorld Indexer to ${{ inputs.environment }}"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/api

    env:
      WORKSPACE: "${{ inputs.environment }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine AWS account ID and role
        id: account
        run: |
            if [ "${{ github.event.inputs.target_environment }}" == "prod" ]; then
              echo "role_arn=${{ secrets.PROD_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
            else
              echo "role_arn=${{ secrets.DEV_AWS_ACC_ROLE }}" >> $GITHUB_OUTPUT
            fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: eu-west-1
            role-to-assume: ${{ steps.account.outputs.role_arn }}

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}
      - name: Debug Path
        run: |
          pwd
          ls -la
          ls environments

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3
          terraform_wrapper: true

      - name: Terraform format
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform initialize
        id: init
        run: terraform init

      - name: Terraform workspace
        id: workspace
        run: terraform workspace select ${{ env.WORKSPACE }}

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out "apply.plan"

      - name: Check environment exists
        id: check-env
        run: |
          state_list=$(terraform state list)
          if [ -z "$state_list" ]; then
            echo "state_empty=false" >> $GITHUB_OUTPUT
          else
            echo "state_empty=true" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && steps.check-env.outputs.state_empty == 'false'
        id: apply
        run: terraform apply "apply.plan"

      - name: Slack Notification
        if: github.ref == 'refs/heads/main' && steps.check-env.outputs.state_empty == 'false'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Deployed Veworld Indexer to *${{ inputs.environment || 'dev' }}* environment
          SLACK_TITLE: VeWorld Indexer Deployment
