name: VeWorld Indexer Stack

on:
  # trigger deployment manually
  workflow_dispatch:
    inputs:
      environment:
        description: Which environment to deploy to ('dev' or 'prod')
        required: true
        default: dev
      imageTag:
        description: The docker image tag to deploy
        required: true
        default: dev-latest
  workflow_call:
    inputs:
      environment:
        description: Which environment to deploy to ('dev' or 'prod')
        required: true
        default: dev
        type: string
      imageTag:
        description: The docker image tag to deploy
        required: true
        default: dev-latest
        type: string

# permissions: allow to create PRs to main branch
permissions:
  pull-requests: read
  contents: read

jobs:
  deploy:
    name: "Deploy VeWorld Indexer to ${{ inputs.environment || 'dev' }}"
    runs-on: ubuntu-latest

    #This environment sets up the following 'vars' and 'secrtes'
    environment: ${{ inputs.environment || 'veworld-dev' }}

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      TF_AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
      TF_AWS_PROFILE_NAME: ${{ vars.TF_AWS_PROFILE_NAME }}
      TF_WORKSPACE_NAME: ${{ vars.TF_WORKSPACE_NAME }}
    defaults:
      run:
        working-directory: terraform/api

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VECHAINCI_SSH_PRIVATE_KEYS }}
      - name: Debug Path
        run: |
          pwd
          ls -la
          ls environments

      - name: Update ENV Yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "terraform/api/environments/${{ vars.TF_WORKSPACE_NAME }}.yaml"
          propertyPath: "image_tag"
          value: ${{ inputs.imageTag || 'dev-latest' }}
          message: "Update VeWorld image tag to ${{ inputs.imageTag || 'dev-latest' }}"
          createPR: true
          title: "Update VeWorld image tag to ${{ inputs.imageTag || 'dev-latest' }}"
          targetBranch: main
          masterBranchName: main
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-veworld-image-tag-${{ inputs.environment || 'dev' }}

      # production requires terraform to operate across account via an AWS_PROFILE, so use $TF_variants, if set, default to $AWS_ otherwise
      - name: Init AWS
        run: |
          mkdir ~/.aws && cat <<EOM > ~/.aws/credentials
            [$TF_AWS_PROFILE_NAME]
            aws_access_key_id = $AWS_ACCESS_KEY_ID
            aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
          EOM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3
          terraform_wrapper: true

      - name: Terraform Init
        id: init
        run: OS_DEBUG=1 TF_LOG=DEBUG terraform init

      - name: Terraform select workspace
        id: workspace
        run: terraform workspace select ${{ vars.TF_WORKSPACE_NAME }}

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Check environment exists
        id: check-env
        run: |
          state_list=$(terraform state list)
          if [ -z "$state_list" ]; then
            echo "state_empty=false" >> $GITHUB_OUTPUT
          else
            echo "state_empty=true" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && steps.check-env.outputs.state_empty == 'false'
        id: apply
        run: terraform apply -auto-approve

      - name: Slack Notification
        if: github.ref == 'refs/heads/main' && steps.check-env.outputs.state_empty == 'false'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: Deployed Veworld Indexer to *${{ inputs.environment || 'dev' }}* environment
          SLACK_TITLE: VeWorld Indexer Deployment
